### ISSUE TITLE
Disable manual input

### ISSUE THREAD

**Issue by gmesnard** [jonthornton/jquery-timepicker#109]
I don't know if this has already been discussed, but can we disable manual input timepicker?

Because I use off times slots (with disableTimeRanges) but you can override these unavailable slot times by writing manually in the input.

I tried to add the html property 'readonly' (works with datepicker), but that does not seem to work on timepicker.

Do you have a solution? 

Thx a lot;)

**Comment by NILESHOMSBPL** [comment]
Hello,
Just put below line of code either on class or Id, the following code won't let the user type new characters.

<strong>$("#my_txtbox").keypress(function(event) {event.preventDefault();});</strong>

**Comment by jonthornton** [comment]
@NILESHOMSBPL that disables the arrow keys as well.

**Comment by NILESHOMSBPL** [comment]
No it won't, as I have checked it right now, please try it once.

**Comment by jonthornton** [comment]
My mistake - you're right. There is a weird side effect of the currently selected row being deselected when you type a numeric key, but this can most likely be fixed. Thanks for the suggestion.

**Comment by NILESHOMSBPL** [comment]
welcome :)

**Comment by dburr** [comment]
Here's another take on the `readonly` conundrum. I am using this time picker on a web app that will be used by both desktop and mobile browsers. The time picker itself works fine on both desktop and mobile browsers (have tested with both iOS/Safari and Android/Chrome) However, without `readonly` set to `true`, on mobile browsers, tapping in the text box will cause the phone keyboard to pop up, which seems to cancel out the time picker popup (i.e. causes it to disappear) I also don't want the keyboard on screen for other reasons, so on all other text fields (I am using another soft keyboard with other textfields) I have `readonly` set to `true`. I have commented out the `readonly` check in the time picker code and that does the trick for me, however I just wanted to bring this additional side to the issue to your attention.

**Comment by Krishnankk** [comment]
Instead of adding `readonly` you can also use `onkeypress="return false;"`
