### ISSUE TITLE
Time list options in reverse order

### ISSUE THREAD

**Issue by slorandus** [jonthornton/jquery-timepicker#166]
Sometime it would be very usefull to have the options in reverse order. Thank you.

**Comment by HoldOffHunger** [comment]
Please! =)

I almost opened a new ticket --

Great project, things have been working perfectly for me.  This is a total feature-request.

Current Behavior -- The `showDuration` option is excellent.  It works correctly and shows "8:00 PM (1 hour), 9:00 PM (2 hours), etc."  This makes sense when picking the ~end~ time.

Requested Behavior -- I want to use for a START time field, not an end time field.  If something starts at 8:00 and ends at 9:00, then event is (1 hour), then if I push it back to 7:00, that means the event becomes actually (2 hours long).  So, choosing an earlier time, with START-type fields, means these numbers should be reversed.

P.S. I tried setting timeDuration() as a function, but it seems to run once and not per-row, which makes sense in optimization.

**Comment by jonthornton** [comment]
@HoldOffHunger what happens if you set `durationTime` to the end time value?

**Comment by HoldOffHunger** [comment]
After setting `durationTime` to the endtime, it now lists the Duration in reverse order!  Thank you, this works perfectly. 

I was considering adding the feature myself, thankfully I tried out your suggestion first.  I guess I just didn't fully wrap my head around the durationTime() functionality. 

Anyway, thanks again!

**Comment by LrntL** [comment]
Hi!

Tahnks for your work.

I have a durationTime equal to YYYY-MM-DD 16:00.
I would like to have in my timepicker these results:

- 15:30 (30 min)
- 15:40 (20 min)
- 15:50 (10 min)
- 16:00 (0 min)

Please! How can I achieve that?
