### ISSUE TITLE
Disable time range using jquery array dynamically

### ISSUE THREAD

**Issue by adibMosharrof** [jonthornton/jquery-timepicker#167]
I am trying to disable certain times in my time picker, and the documentation tells us to use this method.
disableTimeRanges Disable selection of certain time ranges. Input is an array of time pairs, like `[['3:00am', '4:30am'], ['5:00pm', '8:00pm']] default: []

Now, the problem that i am having is that, i want to put this part 
['3:00am', '4:30am'], ['5:00pm', '8:00pm']

in a jquery array, so that i can dynamically handle which time periods i want to disable, i want to do sth like this

var pair = [ ['3:00am', '4:30am'], ['5:00pm', '8:00pm'] ]
mytimepicker.timepicker( 'option', {
                'disableTimeRanges':[
                    pair
                ]
            });

instead of

mytimepicker.timepicker( 'option', {
                'disableTimeRanges':[
                    [ ''3am","4am" ],
                                       [ "5pm", "8pm" ]
                ]
            });

**Comment by ckatarpawar** [comment]
Hi Jonthornton,
I am facing the same issue while providing a dynamic array string to disableTimeRanges option of timepicker. Please refer the below code for more clearification

var actualOccupiedTimes = $("#actualoccupiedtimes").val();
$(".timingsdiv .actualtime").timepicker({ 
	'timeFormat': 'h:i A',
	'scrollDefault': 'now',
	'disableTimeRanges': [actualOccupiedTimes],
	'step':1
});

actualOccupiedTimes  values is : ['12:00 AM','01:00 AM'],['01:32 PM','02:35 PM'].

Please Help me on this issue. 

Thanks

**Comment by rajeshnanda33** [comment]
Any solution to this? I am also facing the same issue.
