### ISSUE TITLE
Close on Window Scroll Issue

### ISSUE THREAD

**Issue by joshua5822** [jonthornton/jquery-timepicker#202]
closeOnWindowScroll did not work for me when the element that scrolls is not the body. It was an easy fix for me, since I have jQuery UI and can use scollParent on self. 

<code>$(document).on('scroll.ui-timepicker', _closeHandler);</code>
I changed it to this:
<code>self.scrollParent().on('scroll.ui-timepicker', _closeHandler);</code>

I know it is not a valid solution though to include jQuery UI as a requirement simply to fix a small issue. I don't have any other solutions right now, but I thought it would be best to at least inform you.

**Comment by QuentinFchx** [comment]
Suggestion:
Rename `closeOnWindowScroll` into `closeOnScroll`
Value: boolean | css selector | HTMLelement
If the value is a boolean and is equal to `true` set the selector to `document`
```js
// handle boolean case in _parseSettings()
if (settings.closeOnScroll) {
	$(settings.closeOnScroll).on('scroll.ui-timepicker', _closeHandler);
}
```
