### ISSUE TITLE
Binding timepicker to readonly control

### ISSUE THREAD

**Issue by shaziafatima88** [jonthornton/jquery-timepicker#249]
am unable to bind the timepicker to a readonly textbox.
can u help me with that?

**Comment by mossgreen08** [comment]
I think you can mimic the behavior of a readonly input by using this workaround: 
                            
<input type="text" **style="color:transparent; text-shadow:0 0 0 #000; outline:none;"** onkeydown="OnKeyDown(event)" />

**function OnKeyDown(event) { event.preventDefault(); };**
