### ISSUE TITLE
disableTextInput() not working

### ISSUE THREAD

**Issue by nageebt** [jonthornton/jquery-timepicker#250]
In a previous issue (#109), a user requested a solution to prevent users from typing via the keyboard.  Apparently the result was a new parameter 'disableTextInput'.  I've tried using this and it doesn't seem to do anything.  Has this been implemented yet?  

For the time being, I'm using the timeFormatError/timeRangeError events to clear out any text typed in, but preventing text from being typed would be a much cleaner solution.

**Comment by rtxing** [comment]
Thank You jonthornton. Your timepicker was very useful
