### ISSUE TITLE
Dinamic disableTimeRanges?

### ISSUE THREAD

**Issue by ghost** [jonthornton/jquery-timepicker#317]
hi!... i need deactivated a few ranges in timepicker. First i get time ranges from php script and thrown json i put it in jquery script like this:

$.ajax({
            url:'./inc/getOcuapados.php',
            type:'POST',
            data:{
                dia:'L',
                gpo: cgpo
            },
            success:function(json){
                json=$.parseJSON(json)
                for(var i=0;i<json.length;i++){
                    ini[i]=json[i].inicio;
                    fin[i]=json[i].fin;
                    //alert("Inicio: "+ini[i]+" fin: "+fin[i]);
                    $('.lun').timepicker({
                        'minTime': '7:00am',
                        'maxTime': '2:00pm',
                        'timeFormat': 'h:i A',
                        'step': 60,
                        'disableTimeRanges': [
                            [ini[0], fin[0]],  
                            [ini[1], fin[1]],
                            [ini[2], fin[2]],
                            [ini[3], fin[3]],
                            [ini[4], fin[4]],
                            [ini[5], fin[5]],
                            [ini[6], fin[6]],
                            [ini[7], fin[7]]
                        ]
                    });
                }
            }
        });

...but this not resolv mi issue..only when 
 'disableTimeRanges': [
                            [ini[0], fin[0]],  
                            [ini[1], fin[1]] ]

then the issue is resolved...

please help!

**Comment by IrineBrank** [comment]
Hi.. I need to disable time if the date selected is equal to today's date else I'm not disabling them, and below is the code..Need your help
$(".datepicker").datepicker({
	onSelect: function(el, inst) {
		var today 		= $(this).val().split('-');
		var todayDate 	= new Date();
		var odate 	= new Date(today[2],today[1]-1,today[0]);
		var inputDate	= odate.getDate() + '-' + odate.getMonth() + '-' + odate.getFullYear();
		var inputDate2	= todayDate.getDate() + '-' + todayDate.getMonth() + '-' + todayDate.getFullYear();
		
		
		if(inputDate == inputDate2) {
			var time_plus_2 = new Date(todayDate.getTime()+2*3600*1000);
		} else {
			var time_plus_2 = new Date(odate.getTime());
		}
		
		$('.timepicker').timepicker({
			'step': 30,
			'forceRoundTime': true,
			'timeFormat': 'h:i A',
			'disableTimeRanges': [
				['12:00am', self.formatAMPM(time_plus_2)]
			]
		});
		$('.timepicker').timepicker('setTime', time_plus_2);
	}
});
function formatAMPM(date) {
	var hours 	= date.getHours();
	var minutes = date.getMinutes();
	var ampm 	= hours >= 12 ? 'pm' : 'am';
	hours 		= hours % 12;
	hours 		= hours ? hours : 12; // the hour '0' should be '12'
	minutes 	= minutes < 10 ? '0'+minutes : minutes;
	var strTime = hours + ':' + minutes + '' + ampm;
	return strTime;
}

**Comment by henriklundahl** [comment]
Does it work if you change your if statement to...

    if(inputDate == inputDate2) {
        var time_plus_2 = new Date(todayDate.getTime()+2*3600*1000);
        var disableTimeRanges = [['12:00am', self.formatAMPM(time_plus_2)]];
    } else {
        var time_plus_2 = new Date(odate.getTime());
        var disableTimeRanges = [];
    }

...and then use `disableTimeRanges` when creating the timepicker?

**Comment by IrineBrank** [comment]
that didn't work for me...but, the below code works 
$('.timepicker').on('click',function(e){
			if(inputDate != inputDate2) {
				if($('.ui-timepicker-am').hasClass('ui-timepicker-disabled')) {
					$('.ui-timepicker-am').removeClass('ui-timepicker-disabled');
					$('.ui-timepicker-pm').removeClass('ui-timepicker-disabled');
				}
			} else{
				$('.ui-timepicker-list li').each(function(i, li) {
					$(li).addClass('ui-timepicker-disabled');
					if($(li).text() == $('#timepicker3').val()){
						return false;
					}  
				});
			}
		});
