### ISSUE TITLE
Width of the ui-timepicker-wrapper

### ISSUE THREAD

**Issue by psnma** [jonthornton/jquery-timepicker#321]
How to set to the width of the ui-timepicker-wrapper become equal to the width of the input automatically?

**Comment by eliotjoe** [comment]
How to set to the width of the ui-timepicker-wrapper become equal to the width of the input automatically?

Editing jquery.timepicker.css would set for all input field

**Comment by jonthornton** [comment]
Use the `className` option to provide unique CSS selectors. You can accomplish the same thing with the `appendTo` option.

**Comment by eliotjoe** [comment]
Thanks for the reply
