### ISSUE TITLE
How to can I hide o remove "disabled time ranges"

### ISSUE THREAD

**Issue by murkein** [jonthornton/jquery-timepicker#336]
Hi, I want to hide "disabled time ranges" in my select timepicker? You disabled correctly "time ranges", but I want to hide o remove them from my select timepicker.

**Comment by murkein** [comment]
Hi, searching on web, I did this: http://jsfiddle.net/geekonspace/t6DXm/6/

**Comment by jonthornton** [comment]
CSS would be the easiest way to accomplish this.

```css
.ui-timepicker-disabled { display: none; }
```

**Comment by murkein** [comment]
better solution, thanks
