### ISSUE TITLE
Problems when I try to disable 11:59 PM in my timepicker

### ISSUE THREAD

**Issue by murkein** [jonthornton/jquery-timepicker#338]
Hi jon, I am trying to disable two time ranges in my time picker

http://jsfiddle.net/geekonspace/deynqy79/5/

{"rangos":[{"horaMinima":"12:00 AM","horaMaxima":"04:43 AM"},{"horaMinima":"08:00 AM","horaMaxima":"11:59 PM"}],"mensaje":"success","code":"success"}

[12:00 AM - 04:43 AM] and [08:00 AM - 11:59 PM]

my problem is that 11:59 PM is not disabled and I know it because in your documentation it is indicated.

How can I disable 11:59 PM? I try also with range [08:00 AM - 12:00 AM] but it not working :(

**Comment by jonthornton** [comment]
Try using `24:00` instead of `11:59PM`.
