### ISSUE TITLE
forceRoundTime with custom timeFormat

### ISSUE THREAD

**Issue by chenjenping** [jonthornton/jquery-timepicker#341]
Is forceRoundTime compatible with timeFormat like 'a h:i' ?

**Comment by jonthornton** [comment]
Yes

**Comment by chenjenping** [comment]
but when i try the format "am 09:11" it can't auto round to "am 09:00", only if it's "09:11 am" it will round to "09:00 am"

**Comment by jonthornton** [comment]
That would be a bug with the time string parser. I'll look into it.

**Comment by chenjenping** [comment]
thanks!

**Comment by chenjenping** [comment]
cool~
I have pulled the new version and it works so nice!
