### ISSUE TITLE
Clicking on a typeahead option triggers the click event on the body.

### ISSUE THREAD

**Issue by juankiz** [jonthornton/jquery-timepicker#343]
I think it would make much more sense for the event.target to be the clicked li element. I have some handlers bound to the body and it's conflicting with them so I'd like to know if do you have some general info on where can I change this behavior?

**Comment by jonthornton** [comment]
Can you provide a jsFiddle that demonstrates the problem?

**Comment by maggerbo** [comment]
I think I experience this to. I just upgraded from 1.2.9 where this was working fine, but now at 1.5.2 it seems like the click event has changed behaviour. However I only experience it in Chrome. Not Firefox or Safari.

I get the error when I click on a list in the ui-timepicker-list. I have this code:

$(document).click(function(e){
   if (!$(e.target).is('.add-time-block, .block, .block *, .ui-timepicker-list *, .edit-shift-box, .edit-shift-box *')) {
           console.log("triggers click event on document")
           $(".edit-shift-box").hide();
   }
});

When I choose a list item in chrome I the "triggers click event on document" fires. Again, only in Chrome.

I hope you have an idea for what I can do.

Thanks for a great plugin!

**Comment by jonthornton** [comment]
@maggerbo thanks for providing that test case!
