### ISSUE TITLE
Calling changeTime

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#346]
Is there a way to call the `changeTime` event? Like in jQuery you can call `change()`

**Comment by jonthornton** [comment]
`.on('changeTime', function(e) { ... })`

**Comment by KrunchMuffin** [comment]
ya, I do that, but that only listens for the event, I need to call the event manually. `$("timepicker").changeTime()`

**Comment by jonthornton** [comment]
`$('#timepicker').trigger('changeTime')`

**Comment by KrunchMuffin** [comment]
THanks.
