### ISSUE TITLE
minTime == maxTime

### ISSUE THREAD

**Issue by vmanjunath** [jonthornton/jquery-timepicker#347]
I'm dealing with a situation where in some cases minTime and maxTime are both set to the same thing (say 11:00 pm). There are two reasonable things that one can expect timepicker to do with that:
1. show 24 hours of times starting at 11:00 pm and ending at 11:00 pm.
2. show a singleton consisting of 11:00 pm.

The first of these two is the expected behavior, right?

Is there a way to make it do the second instead?

Thanks much.

**Comment by vmanjunath** [comment]
I guess I answered my own question, but on the off chance you cared to know, the following (line 433) is where the answer was:
		if (end <= start) {
			// make sure the end time is greater than start time, otherwise there will be no list to show


While end < start  means that the list is empty, end == start would mean that the list is a singleton, which (at least in my case) is a reasonable thing to have.

While not setting maxTime would yield the first behavior (which is what happens if minTime == maxTIme), there's no way (that I know of) to achieve a singleton list unless one changes the condition to (end < start).

Thanks.

V
PS. Thanks for jquery-timepicker.

**Comment by jonthornton** [comment]
That's not a user-case I had considered. Glad you got it working!
