### ISSUE TITLE
Feature: forceRoundDirection

### ISSUE THREAD

**Issue by sclausen** [jonthornton/jquery-timepicker#348]
`forceRoundTime` is **really** great, but a `forceRoundTimeDirection` would be great for usecases where you have time slices which aren't rounded mathematically but always up/down.

**Comment by jonthornton** [comment]
Here's an example of how to use the new option:

```javascript
$('#example').timepicker({
    forceRoundTime: true,
    roundingFunction: function(seconds, settings) {
        if (!seconds) return seconds;
        return seconds - (seconds % (settings.step*60))
    }
});
```

**Comment by sclausen** [comment]
:+1: many thanks!
