### ISSUE TITLE
Maniplating the dropdown select

### ISSUE THREAD

**Issue by donpro2** [jonthornton/jquery-timepicker#349]
Hi,

When I create the timepicker object, I use the option: 'useSelect':'true'.  I need to set the default selected index to the option value that matches a hidden field vaule. However, when the timepicker object is created, there is no ID attached to the Select.  Can I request in a future update, the ability to attach an ID value the the Select?

Thanks / Don

**Comment by jonthornton** [comment]
Can you set the value of the `<input>` element you're attaching the timepicker to?

**Comment by donpro2** [comment]
Hi,

Thanks for the suggestion. It did work but nor with the default format.

When I used the default, 3:00am,.., 3:00pm, it did not set the drop-downs that were pm.
When I included the option: 'timeFormat':'H:i:s', it worked for all drop-downs.

Thanks / Don
