### ISSUE TITLE
DisableTimeRange and Max/Min Time Conflict

### ISSUE THREAD

**Issue by jheymii** [jonthornton/jquery-timepicker#350]
Hello Sir. I'm using your Jquery Time Picker with DisableTimeRange and my time ranges are from my database, which I put in arrays and I use AJAX to get my time ranges from my PHP file.

    $('#Ttime').timepicker({ 
      'timeFormat': 'h:i A'
      'disableTimeRanges': unavailableTime 
    });

    $("#Ttime").focus(function(){
            $.ajax({
                url: '../admin/thname.php',
                data: "q="+id,
                dataType: 'json', 
                async : false,
                success: function(data){
                  unavailableTime = data;
                }
            });
        });

It all works but when I try to put MAX/MIN Time, my DisableTimeRanges doesn't work. It's like the codes are overlapping or having conflicts with each other.

    $('#Ttime').timepicker({ 
          'minTime': '2:00am',
          'maxTime': '2:00pm',
    });

Even if my Time Ranges are within the Max and Min Time. 
Like for example, this is my ajax data:

        [["2:00am","3:00am"],["4:00am","5:00am"],["6:00am","7:00am"]]

Is there a fix for my problem ? Thank You Sir.

**Comment by jonthornton** [comment]
I'll need to see a fully working example to help. Can you post a jsFiddle?

**Comment by neethukc** [comment]
I have the same issue. 
Please find it in the fiddle
http://jsfiddle.net/neethukcbsb/95hpwcfw/1/
