### ISSUE TITLE
minTime == maxTime shows times from minTime to minTime+1day

### ISSUE THREAD

**Issue by ReachGz** [jonthornton/jquery-timepicker#351]
Hi,

I think the title is self-describing but here's more info:

The following options:
minTime: '09:00pm',
maxTime: '09:00pm',
step: 120,
useSelect: true

This is the result:

![image](https://cloud.githubusercontent.com/assets/10906778/6096131/da2e5fc0-af46-11e4-8ab7-90e174167f7e.png)

IMHO the expected result should be just one option (09:00pm).

My use case is this: if I want the user to schedule something to certain hour today, and not let him to schedule it to an hour in the past, minTime would be calculated according to current time. Let's say that the valid hours are 3:00pm, 5:00pm, 7:00pm and 9:00pm, and currently are the 8:30pm, the only option i have left is 9:00pm and not 11:00pm, 1:00am, 3:00am, etc.

In the case my reasoning is correct, the solution is trivial, changing this condition (around line 445):
```javascript
if (end <= start) {
    // make sure the end time is greater than start time, otherwise there will be no list to show
    end += _ONE_DAY;
}
```

**Comment by jonthornton** [comment]
I agree. This will be fixed in the next minor version. Thanks!
