### ISSUE TITLE
Link the available time with the jQuery UI datepicker

### ISSUE THREAD

**Issue by Andalia** [jonthornton/jquery-timepicker#353]
Hello!

I wonder if it is possible to link the timepicker with the datepicker from JQuery Ui (http://jqueryui.com/datepicker/)

I'd like to have different times available to pick depending on the week-day I selected in the datepicker. Is there a way to do that?

Best regards,
Andalia

**Comment by jonthornton** [comment]
Yes, that is possible. You'd need some sort of map between dates and available times. Here's a rough example:

```javascript
var times = {
    '01/01/2015': { minTime: '9am', maxTime: '6pm' },
    '01/02/2015': { minTime: '6am', maxTime: '10pm' },
    '01/03/2015': { minTime: '9am', maxTime: '6pm' },
    ...
};

$('#timeInput').timepicker();
$('#dateInput').datepicker({
    onChange: updateAvailableTimes,
    ...
});

function updateAvailableTimes(date) {
    $('#timeInput').timepicker('option', times[date]);
}
```

**Comment by Andalia** [comment]
Hey, thanks for the reply.
Is it also possible to link the time to weekdays rather to just days of the month?

Per example, from 1pm to 8 pm on mondays, but 10 am to 7 pm on thuesdays.

**Comment by jonthornton** [comment]
That probably possible, but beyond the scope of what I'm able to help with.
