### ISSUE TITLE
Timepicker does not round to values in list

### ISSUE THREAD

**Issue by isharacomix** [jonthornton/jquery-timepicker#358]
I'm trying to make a timepicker with times that occur every 3 hours from 0:59.

    $('#endtime').timepicker({ 'timeFormat': 'H:i', 'step': 180, 'minTime': '00:59', 'forceRoundTime': true });

However, whenever I enter a time, it rounds to 0:00, 3:00, 6:00, etc rather than rounding to the times contained in the picker.

Here is a modification I made to make it work:

    function roundToNearest(seconds, settings) {
      if (seconds === null) {
        return null;
      } else {
        //console.log(settings.minTime);

        var offset = (seconds-settings.minTime) % (settings.step*60); // step is in minutes

        if (offset >= settings.step*30) {
          // if offset is larger than a half step, round up
          seconds += (settings.step*60) - offset;
        } else {
          // round down
          seconds -= offset;
        }

        return seconds;
      }
    }

**Comment by jonthornton** [comment]
Fixed by #359
