### ISSUE TITLE
If input is readonly the list is not displayed

### ISSUE THREAD

**Issue by axelitus** [jonthornton/jquery-timepicker#360]
The subject may be misleading as to what I mean with this issue. It seems reasonably to think that when the input field is readonly then we don't need to display the times as the value in the field cannot change. But what if we don't want the user to be able enter the times directly into the input? I know there's an option to render as a select control, but if we want to use an input text as the control then there's no way to do this.

I have managed to overcome this by commenting the lines between [L100](https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.js#L100) and [L102](https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.js#L102) but I don't know if this would be correct from a conceptual point of view, though it would be useful to achieve this:

![image](https://cloud.githubusercontent.com/assets/732441/6466051/98655e6c-c18a-11e4-9e4e-73a4d40a248a.png)

**Comment by jonthornton** [comment]
This behavior has been debated pretty extensively - you can see my side of the argument in #109. For now `useSelect` is recommended if you want to prevent text input.

**Comment by axelitus** [comment]
I missed that and I agree with you. The control should play along what's "semantically correct". My issue with the useSelect option is that it does not play along well with bootstrap styles and breaks the design or at least I haven't dig so far into the code.

Is there a way to define a class to add to the form controls in the timepicker? So it get's styled as bootstrap form-control as an example.

**Comment by jonthornton** [comment]
Yup! The `<select>` should pick up whatever you specify for the `className` option.

**Comment by axelitus** [comment]
Nice! It works, thanks... the only downside I see is that with the useSelect option the showDuration option is useless... but that's what we face in this business: trade-offs ;)

Nice work and thanks for the help!
