### ISSUE TITLE
Hide dropdown on keypress

### ISSUE THREAD

**Issue by dceddia** [jonthornton/jquery-timepicker#365]
I like that this time picker behaves very much like the Google Calendar one, and the only problem I see is that it auto-selects a predefined time when hitting 'enter'. The problem is that if you type in "123p" and hit enter, it automatically selects "1:30pm" even though forceRoundTime is false. Tabbing or clicking away works properly, but that's a little less intuitive.

Google Calendar solves this by simply hiding the dropdown as soon as any keys are pressed, other than up and down. I could try to fix it with a new "hideOnKeypress" option and create a PR if you like.

**Comment by jonthornton** [comment]
That's a good suggestion. I'd rather not clutter the code with options so I plan to make this the default and only behavior. Should have something posted this weekend.

**Comment by jonthornton** [comment]
I just realized there's the `typeaheadHighlight` option. Set that to false and it should solve your problem.
