### ISSUE TITLE
disable

### ISSUE THREAD

**Issue by martinschenk** [jonthornton/jquery-timepicker#366]
can't get the timepicker field disabled.

**Comment by jonthornton** [comment]
Could you post a jsFiddle with your code and explain the expected behavior?

**Comment by martinschenk** [comment]
Hi Jon,

thanks for your fast answer.
http://jsfiddle.net/martin_schenk/ugrtf4xv/


Regards, Martin

2015-03-06 16:29 GMT+01:00 Jon Thornton <notifications@github.com>:

**Comment by jonthornton** [comment]
I still don't understand. The jsFiddle you posted contains JS errors (due to missing libraries).

**Comment by martinschenk** [comment]
sorry,
http://jsfiddle.net/martin_schenk/Gczvz/227/

just wanted to now how to "disable" or "hide" the timepicker.
Regards, Martin

2015-03-06 17:15 GMT+01:00 Jon Thornton <notifications@github.com>:

**Comment by jonthornton** [comment]
`$('#removeExample').timepicker('remove');`

Or set the `disabled` or `readonly` attributes of the input that timepicker is bound to.
