### ISSUE TITLE
Showing double all 

### ISSUE THREAD

**Issue by mhepekiz** [jonthornton/jquery-timepicker#367]
![screen shot 2015-03-06 at 13 46 41](https://cloud.githubusercontent.com/assets/11349252/6524852/fbbcd746-c406-11e4-9787-26ed99d40c7b.png)
I'm new user of timepicker but when i use it as 

<script type='text/javascript'>//<![CDATA[ 
$(document).ready(function(){
    $('#OrderTime').timepicker({ timeFormat: 'h:mm' });
}); 

</script>

comes double all times and :mm why?

Thank you for your help

**Comment by jonthornton** [comment]
There's a problem with your `timeFormat` setting. Please double check the documentation.
