### ISSUE TITLE
Do not allow inputs like '112:00 am'

### ISSUE THREAD

**Issue by hardikvohra** [jonthornton/jquery-timepicker#368]

**Comment by jonthornton** [comment]
Why?

**Comment by hardikvohra** [comment]
I am sorry, I meant to say 'Do not allow inputs like 13:00 AM or 112:00 AM'.

**Comment by hardikvohra** [comment]
Right now, user can enter this input. You can try it on any of the demo examples.

**Comment by hardikvohra** [comment]
Doing something like this would help : 
https://github.com/jonthornton/jquery-timepicker/compare/master...hardikvohra:inputTimeInRange?expand=1

**Comment by jonthornton** [comment]
I suggest using the `timeFormatError` and `timeRangeError` events for stuff like this:

```javascript
$('#someInput').on('timeFormatError timeRangeError', function(e) {
    // handle invalid input
});
```

I try to keep the timepicker code as lightweight as possible, so this functionality won't be integrated into the plugin itself.
