### ISSUE TITLE
Multiple display question

### ISSUE THREAD

**Issue by bondz** [jonthornton/jquery-timepicker#371]
I would like the timpicker to show in the dropdown times like (4:00:00 PM ...) but when the user selects it, writes (16:00:00) in the textfield. I have tried using the ```timeFormat``` function but I can't seem to get anywhere. Is there another way to achieve this?

**Comment by jonthornton** [comment]
You'd have to reformat the time values yourself when the user selects. Here's how you could do it using [Moment.js](http://momentjs.com/):

```javascript
$('#someTimeInput').on('changeTime', function(e) {
    var $this = $(this);
    var timeObject = $this.timepicker('getTime');
    var formattedTime = Moment(timeObject).format('HH:mm:ss');
    $this.val(formattedTime);
});
```

**Comment by bondz** [comment]
Thanks :+1:
