### ISSUE TITLE
mintime/maxtime adjusted dynamically

### ISSUE THREAD

**Issue by ambicoder** [jonthornton/jquery-timepicker#373]
Is there a way  mintime/maxtime can be set/adjusted dynamically?
I have create two inputs....my goal is that when for example in the first input 10:00 is selected...in the second input the time presented for  the user to select is no less than 10:30.

I hope you understand what I am truing to achieve here.

**Comment by jonthornton** [comment]
mintime/maxtime can adjusted dynamically using the `option` method.

**Comment by ambicoder** [comment]
I do not understand how option will help here....
My goal is that the second input's timepicker menu(the mintime) starts always half an hour later than the time selected from the user, in the first input....

**Comment by ambicoder** [comment]
I found a solution...thanks
