### ISSUE TITLE
Problem with "useSelect: true", angular-jquery-timepicker and displaying initial time value

### ISSUE THREAD

**Issue by chirillc** [jonthornton/jquery-timepicker#376]
Hi,
I am not sure if I'm doing something wrong but this is what happens.
When "useSelect" setting is set to "true", "forceRoundTime" is set to "false", and correct Date is passed as value, selectbox is rendered properly but the selected  value is always "12:00am".

I was looking into this code in "jquery.timepicker.js":

	function _setTimeValue(self, value, source)
	{
		if (self.is('input')) {
			self.val(value);

			var settings = self.data('timepicker-settings');
			if (settings.useSelect && source != 'select' && source != 'initial') {
				self.data('timepicker-list').val(_roundAndFormatTime(value, settings));

As an experiment I've changed it to:

	function _setTimeValue(self, value, source)
	{
		if (self.is('input')) {
			self.val(value);

			var settings = self.data('timepicker-settings');
			if (settings.useSelect && source != 'select' && source != 'initial') {
				//self.data('timepicker-list').val(_roundAndFormatTime(value, settings));
                                if (settings.forceRoundTime) {
                                        var prettyTime = _roundAndFormatTime(_time2int(value), settings)
                                } else {
                                        var prettyTime = _int2time(_time2int(value), settings);
                                }                            

                                self.data('timepicker-list').val(prettyTime);   

and it started working correctly.

Please advise if this seem to be a bug or user error?

Thank you,
Chirill

**Comment by jonthornton** [comment]
I'm not able to reproduce the problem. Can you post a jsFiddle?

**Comment by chirillc** [comment]
@jonthornton Please see 2 jsFiddles attached. The only difference is "useSelect: true/false" setting.

1. https://jsfiddle.net/crfbkqxn/1/    - works as expected (date is defaulted to "11:00 AM")
2. https://jsfiddle.net/n1v2e4sz/ - does not work (date is defaulted to "12:00 AM")

**Comment by jonthornton** [comment]
Thanks! Your "does not work" example will work using Timepicker 1.6.7.

**Comment by chirillc** [comment]
Thank you for quick turnaround!
