### ISSUE TITLE
getting the attribute

### ISSUE THREAD

**Issue by ambicoder** [jonthornton/jquery-timepicker#377]
I am trying to get the ID attribute of an input element where timepicker has been attached to.
jquery methods like ckeched or selected I do not think they work here...but to be more specific look at this jsbin here:http://jsbin.com/qudaro/9/
Focus your attention on the upper left input element...when a value/time is picked from the menu the from function is called(line 38)....I am trying to write some code there that will print the ID of the input box whose value was changed...which is the upper left in this case 

What complicates things is backbone...timepicker is not related to backbone so you do not need to answer this.

**Comment by jonthornton** [comment]
Change your `from` function to look like this:

```javascript
from:function(e)
{
    alert($(e.target).attr('id'));
},

**Comment by ambicoder** [comment]
thanks...it works now
