### ISSUE TITLE
Report invalid input string for validation purposes

### ISSUE THREAD

**Issue by stevenickels** [jonthornton/jquery-timepicker#378]
I'm looking to use this timepicker control in an AngularJS application, using the https://github.com/Recras/angular-jquery-timepicker wrapper. It works nicely, except that when a user enters invalid data into the timepicker input field the control ignores the invalid string and simply returns the original reference date unaltered. This seems to prevent me from being able to recognize the invalid state of the input field and alert the user to fix it.

I propose that the `getTime()` function be updated to return `null` if `_time2int()` returns a null offset value due to the input string being unparseable. This behavior could be based on a new setting, such as `reportInvalidInput=true` (`false` by default to not break existing behavior).

If this sounds reasonable, let me know if you want me to generate a PR for it. Otherwise, is there another way I should be determining the validity of the user's input in this control?

**Comment by jonthornton** [comment]
That does sound reasonable. I think the existing behavior of getTime() is undesirable, so no need to hide the fix behind a new setting. I can have a patch up in < 48hrs.

The `timeFormatError` event can be used for validation. I'm not sure whether it's helpful for this particular Angular integration though.
