### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#379]
I wrote a node script that checks releases for any github plugins I am using. Uses the API and I will grab the first  one in the release list since it is usually the latest. But with yours it doesn't because your very first version is marked with a "v" and the rest are not, so the script always says the latest is the v1.0.0. Any way you can relabel that first release? If not, no worries, just have to manually check for updates or hack the script.

Thanks.

**Comment by jonthornton** [comment]
Yikes, sorry about that. I'll get that corrected by tomorrow.

**Comment by KrunchMuffin** [comment]
thanks!

**Comment by jonthornton** [comment]
Boom.

![screen shot 2015-04-01 at 7 24 26 pm](https://cloud.githubusercontent.com/assets/196831/6954884/c1c34716-d8a4-11e4-9b09-c0987e1a7b3e.png)

**Comment by KrunchMuffin** [comment]
perfect!
