### ISSUE TITLE
Trailing space in input causes time to be treated as invalid

### ISSUE THREAD

**Issue by rafalyesware** [jonthornton/jquery-timepicker#381]
To repro:

1. Tab into the control
2. Type a valid time.
3. Enter a space after the time.
4. Tab out of the control (or click out)
5. Note that 'getTime' returns a `null` value.

(yes, I'm specifically interested in keyboard input and allowing non-rounded times to be entered, much as the gcal time pickers allow).

Note also that the picker does not appear to have any way of showing error states -- the Gcal picker sets the background to red to indicate an invalid entry.

See fiddle here: http://jsfiddle.net/9xLryruc/

**Comment by rafalyesware** [comment]
Playing around with keyboard input I noticed that an input of '12am' then tabbing out also causes a `null` return value from `getDate`.

**Comment by jonthornton** [comment]
Related to #382

**Comment by rafalyesware** [comment]
Thanks, @jonthornton! (And for the picker in general, enjoying using it!)

**Comment by jonthornton** [comment]
Regarding showing error states, you can do that with event handlers. Here's a one way:

```javascript
var timepickers = $('input.time'); // some selector identifying your timepickers
timepickers.on('timeFormatError timeRangeError', function(e) {
    $(this).addClass('error');
});
timepickers.on('changeTime', function(e) {
    $(this).addClass('error');
});
```

**Comment by rafalyesware** [comment]
Thanks for the tip... why also on `changeTime`?

**Comment by jonthornton** [comment]
Whoops, sorry. That should have been `removeClass()`. I've updated the code.
