### ISSUE TITLE
getTime return null for 0:0

### ISSUE THREAD

**Issue by cAhmad** [jonthornton/jquery-timepicker#382]
Hi, firstly thank you for you work ! 

I got an issue when selecting 00:00 the getTime function return null.
The function _time2int return 0 which sound ok
but the check at https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.js#L259 resolve to false which return null

Is it an expected behavior.

**Comment by jonthornton** [comment]
Yes, this is a bug. Will have a fix posted asap!

**Comment by cAhmad** [comment]
Thank you for this quick fix!
