### ISSUE TITLE
Datepair's timepicker allows invalid input

### ISSUE THREAD

**Issue by abarbaspring** [jonthornton/jquery-timepicker#383]
Hi, I'm having a problem with the timepicker in the Datepair.

Actually, it is allowing invalid input such as 'kdgjlsklfdj' and this input is automatically converted into 00:00 hrs. I need that the timepicker does not allow such input, maybe invalidating the control.

Besides, once the invalid input is typed in the first timepicker, the datepair stops updating the second timepicker with the delta, even I put a valid time in the first timepicker.

**Comment by jonthornton** [comment]
Related to https://github.com/jonthornton/Datepair.js/issues/39

**Comment by jonthornton** [comment]
Handling invalid values is up to the developer. Use the `timeFormatError` and `timeRangeError` events.
