### ISSUE TITLE
Small docs error

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#384]
In the getTime Method in the github docs, there is a misplaced comma.

`$('#getTimeExample').timepicker('getTime'[, new Date()]);`
should be
`$('#getTimeExample').timepicker('getTime', [new Date()]);`

**Comment by jonthornton** [comment]
The brackets were supposed to imply that the second param is optional - it was a confusing example. Thanks for pointing it out!
