### ISSUE TITLE
Enhancement: onBeforeChangeTime

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#385]
This would be a welcomed event.

**Comment by jonthornton** [comment]
How could this even be used?

**Comment by KrunchMuffin** [comment]
one instance would be to grab the value before it is changed in order to revert.

**Comment by jonthornton** [comment]
It's better to use a more general solution for something like that. Here's an example: http://stackoverflow.com/a/1910161/3250
