### ISSUE TITLE
1.6.10 error in _time2init

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#387]
At some point the `timeString` param is actually a function so the `timeString.toLowerCase()` throws an error.

    function () {
        return settings.roundingFunction(_time2int(settings.scrollDefault), settings);
    }
    Uncaught TypeError: timeString.toLowerCase is not a function
    _time2int @ jquery.timepicker.js:1065
    settings.scrollDefault @ jquery.timepicker.js:356
    methods.show @ jquery.timepicker.js:161

**Comment by jonthornton** [comment]
Can you provide steps to reproduce this error?

**Comment by KrunchMuffin** [comment]
Ya, here you go.

http://jsfiddle.net/fv9m5my0/6/
Just click start time.

**Comment by hamzabinamin** [comment]
@jonthornton I am facing the same issue if I use min or max time, is there any fix for it?

**Comment by jonthornton** [comment]
@hamzabinamin I don't understand. Can you provide more explanation?

**Comment by hamzabinamin** [comment]
@jonthornton If I use min/max time or disabledTimeRanges I get the following error

```
index.js?175a:52 Uncaught TypeError: timeString.toLowerCase is not a function
    at Timepicker.time2int (index.js?175a:52)
    at Timepicker.parseSettings (index.js?175a:180)
    at HTMLInputElement.eval (jquery.timepicker.js?ffa3:260)
    at Function.each (jquery-3.3.1.min.js:2)
    at w.fn.init.each (jquery-3.3.1.min.js:2)
    at w.fn.init.option (jquery.timepicker.js?ffa3:248)
    at w.fn.init.$.fn.timepicker (jquery.timepicker.js?ffa3:1140)
```
I've tried using the following ways:

```
$('#time_1 .time').timepicker({
  "minTime": '6am',
  'showDuration': true,
  'timeFormat': 'g:ia'
});
```
`$('#time_1 .time').timepicker('option', {'maxTime':  '11:00pm'});`

`$('#time_1 .time').timepicker('option', {'disableTimeRanges':  [['12:00am', '6:00am']]});`

But I get the same error. If I don't use any options then the picker works fine but I need to remove some of the times between 12am-6am

**Comment by jonthornton** [comment]
Sorry, I can't reproduce the problem. Can you share a working demo of the problem?

**Comment by hamzabinamin** [comment]
@jonthornton I made a video to showcase the issue. I have discovered that this only happens if I use maxTime or the disableTimeRanges options. If I just use minTime, then it seems to work fine.

Just to explain a bit further, the issue only occurs after I select a time from the first time picker.

Here's the video link [](https://streamable.com/1cnqz)

**Comment by jonthornton** [comment]
@hamzabinamin thanks for the video! Is it possible to share the source code for the demo? I'm still having trouble reproducing the error for myself.

**Comment by hamzabinamin** [comment]
@jonthornton I tried updating to 1.11.15 and it seems to have solved the problem. But it definitely occurs on 1.11.14 so you might want to alert other users as well.
