### ISSUE TITLE
timepicker display not next to input element

### ISSUE THREAD

**Issue by tshad** [jonthornton/jquery-timepicker#389]
Timepicker always shows in bottom left corner of screen.

Using bootstrap and sitefinity,

It works correctly and puts the time into the input object specified.

The div section that gets added to the bottom of the screen is:

<div class="ui-timepicker-container ui-timepicker-no-scrollbar ui-timepicker-standard ui-helper-hidden ui-timepicker-hidden" style="left: 452.78px; top: 332px; width: 121px; height: 1356px; display: none; z-index: auto; cursor: default;"><div class="ui-timepicker ui-widget ui-widget-content ui-menu ui-corner-all" style="width: 119px;"><ul class="ui-timepicker-viewport" style="width: 119px; padding-right: 40px;"><li class="ui-menu-item" style="width: 119px;"><a class="ui-corner-all">12:00 AM</a></li><li class="ui-menu-item" style="width: 119px;"><a class="ui-corner-all">12:30 AM</a></li><li class="ui-menu-item" style="width: 119px;"><a class="ui-corner-all">01:00 AM</a></li><li class="ui-menu-item" style="width: 119px;"><a class="ui-corner-all">01:30 
...

Thanks,

Tom

**Comment by tshad** [comment]
The div didn't shoe so I am adding a screenshot of it.
![timetracker](https://cloud.githubusercontent.com/assets/12076957/7289010/dccc11d4-e91e-11e4-838d-dffd552ec602.jpg)

**Comment by tshad** [comment]
Not sure how I closed this but it is still an issue.

thanks,
Tom

**Comment by jonthornton** [comment]
Did you include the [timepicker CSS](https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.css)?

**Comment by tshad** [comment]
Yes.

I tried some of your samples and they didn't seem to work, such as having a scrollbar.  The list is there but no scrollbar.

Is there some way to tell if the ,css file is having an issue?

Thanks,

Tom

**Comment by jonthornton** [comment]
> Is there some way to tell if the ,css file is having an issue?

Yes, you'll have exactly the problems you're describing. There's not much more help I can offer without seeing a working demo of your app.
