### ISSUE TITLE
How to calculate length of time

### ISSUE THREAD

**Issue by Jed-Lehmann** [jonthornton/jquery-timepicker#391]
I would like to use two inputs to select a range of times, and then have it output the length of time, as per this example:

Start time: 8am
End time: 9am
Total time: 1 hour

I have created this fiddle as an example. 
http://jsfiddle.net/po2bgsuq/

Is this possible with jQuery Timepicker?

**Comment by jonthornton** [comment]
Yup, that's possible. Use the `getTime` function:

```javascript
var difference_ms = $('#end').timepicker('getTime') - $('#start').timepicker('getTime');
```
