### ISSUE TITLE
Time sync

### ISSUE THREAD

**Issue by kitsune7** [jonthornton/jquery-timepicker#394]
There is an issue where if you move the end date at least one day after the start date, change the end date time to a time before the start date time, and then change the end date to the same day as the start date, then the end time ends up being before the start time.

Ex:
Start date   start time     End date    end time
  5-12-15     9:00am       5-12-15      10:00am
  5-12-15     9:00am       5-13-15      10:00am
  5-12-15     9:00am       5-13-15       2:00am
  5-12-15     9:00am       5-12-15       2:00am ******PROBLEM*******

**Comment by jonthornton** [comment]
What behavior would you expect here?

**Comment by kitsune7** [comment]
I would expect it to not allow the end date and time to come before the start date and time.  It might work well if the start date on the calendar was grayed out for the end date if the end time is before the start time.
