### ISSUE TITLE
Dynamic DisableTimeRanges issue

### ISSUE THREAD

**Issue by ckatarpawar** [jonthornton/jquery-timepicker#397]
Hi Jonthornton,
I am facing the issue while providing dynamic array string to disableTimeRanges option of timepicker. Please refer the below code for more clearification

var actualOccupiedTimes = $("#actualoccupiedtimes").val();
$(".timingsdiv .actualtime").timepicker({
'timeFormat': 'h:i A',
'scrollDefault': 'now',
'disableTimeRanges': [actualOccupiedTimes],
'step':1
});

actualOccupiedTimes values is : ['12:00 AM','01:00 AM'],['01:32 PM','02:35 PM'].

Please Help me on this issue.

Thanks

**Comment by mdettmer01** [comment]
I'm trying to set disabledTimeRanges dynamically when the user selects a new date.  It fails with "TypeError: b.disableTimeRanges.sort is not a function".  I would consider this functionality to be vital to this plugin.  Please help!

**Comment by jonthornton** [comment]
@ckatarpawar `actualOccupiedTimes` is an array but you're wrapping it in another array with `'disableTimeRanges': [actualOccupiedTimes],`. Do this instead `'disableTimeRanges': actualOccupiedTimes,`.

**Comment by jishnu2292** [comment]
I did as 'disableTimeRanges': actualOccupiedTimes,
but its not working and showing error as TypeError: b.disableTimeRanges.sort is not a function

**Comment by jonthornton** [comment]
@jishnu2292 it sounds like `actualOccupiedTimes` is not an array. You need to pass an array to `disableTimeRanges`.

**Comment by jishnu2292** [comment]
Thank you for your reply.
i had given as var timeRangesToDisable = new Array();
timeRangesToDisable = "[['11.00 am','11.15 am'],['11.30 am','11.45 am'],['11.45 am','12.00 pm']]"; Then in timepicker option, i given as
 'disableTimeRanges': timeRangesToDisable

if i give the value directly to option, its working.

**Comment by Niranjan-N-Raju** [comment]
@jonthornton , can u please provide an example for this... Im facing same issue. My disabled values will come in an value of an hidden field in json format.

**Comment by jonthornton** [comment]
@Niranjan-N-Raju please provide a code sample that demonstrates the problem.
