### ISSUE TITLE
Match Element Width

### ISSUE THREAD

**Issue by jessehouchins** [jonthornton/jquery-timepicker#400]
I'm not seeing any way to match the list with to the target element's width. Is this possible and I'm just not seeing it? Or is it a feature that could be added? I'm using custom CSS adn the `appendTo: 'body'` option.

**Comment by jonthornton** [comment]
See #399

**Comment by jessehouchins** [comment]
My inputs are not a fixed width, but a percentage width AND I'm using the `appendTo: 'body'` option, therefore I need a JS solution.

**Comment by xl97** [comment]
Was this ever addressed?  Through a legit class/plugin update or even just a work-around posted to be added?  I dont even see any appendTo() examples?  (If this is supposed to be used as a 'fix')?

**Comment by jonthornton** [comment]
@xl97 what use case would you like to see an example for?
