### ISSUE TITLE
improve document, example have full code

### ISSUE THREAD

**Issue by 1c7** [jonthornton/jquery-timepicker#402]
1. document not clear enough
![image](https://cloud.githubusercontent.com/assets/1804755/8052683/7e825200-0ebc-11e5-9e58-fc83948abe64.png)
please write full code. which js,css should include. and everything

**Comment by jonthornton** [comment]
Include `jquery.timepicker.js` or `jquery.timepicker.min.js` along with `jquery.timepicker.css` and the jQuery library.
