### ISSUE TITLE
Dropdown does not scroll with input when using `appendTo` option

### ISSUE THREAD

**Issue by jessehouchins** [jonthornton/jquery-timepicker#404]
Right now, the support for scrollable containers (other than the window) seems lacking. If i have a time picker (open) in a scrollable div and scroll without clicking (trackpad/mouse wheel) the input moves, but the dropdown stays where it was:

![screen shot 2015-06-15 at 8 30 38 am](https://cloud.githubusercontent.com/assets/402873/8160912/d6d39baa-1338-11e5-8029-e066220042cd.png)

The solution involves setting event handlers on the inputs scrollable parent(s) to reposition (or close) it when they scroll. Unfortunately, the `.scrollParent()` method is not part of base jQuery, so we would need to write a custom method to support the feature without requiring jQuery UI. Another option might be to bind to scroll events on all ancestor elements.

**Comment by jonthornton** [comment]
Does this happen when the picker is appended to something inside the scrollable container, or only when it's appended outside the container (like `body`)?

**Comment by jessehouchins** [comment]
probably only outside the container.

**Comment by CoralSilver** [comment]
This is happening to me even when appended to the form which the timepicker input is inside of.

**Comment by jonthornton** [comment]
The containing element referenced by `appendTo` needs to have the `position: relative` CSS rule set.
