### ISSUE TITLE
Issue with new showOn

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#406]
My settings are
`		showOnFocus: true,
		showOn: 'focus',`

    $(".ui-timepicker-input").timepicker({
        disableTouchKeyboard: true,
        useSelect: false,
        className: 'timepickerWidth',
        step:15
    });

now, after selecting a start and end time and clicking a button, i have a modal come up asking for some info. after closing that modal, the timepicker is no longer showing on click, i have to click away and come back to it for it to show.` e.type` is always `click` in these instances.
If I revert that [one line](https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.js#L82) it goes back to working fine.  I know ur going to ask for code sample, but I don't have time right now. Just wanted you to be aware.

UPDATE: ok, lied, I did have time to repro it. [Here is a fiddle](http://jsfiddle.net/fv9m5my0/9/)
Just click start time, then try clicking start time again.

**Comment by jonthornton** [comment]
Sorry for the delay. Should be working now.
