### ISSUE TITLE
New version issue, does not open suggestion some time

### ISSUE THREAD

**Issue by eliotjoe** [jonthornton/jquery-timepicker#407]
First of all, Thanks man! It is a great plugin.
Now, the problem is, i have updated my version to the latest version to use 'noneOption' feature which was not working with my older version.

But after updating, i am facing an issue sometimes after selecting a option from the list then clicking outside the input field then focusing the text field doen not opens the suggestion. I was not having such issue in the older version.

**Comment by jonthornton** [comment]
Do you still have the problem with v1.8.1?

**Comment by scurker** [comment]
@eliotjoe I was having the same issue with v1.8.0, but updating to the latest version fixed the issue.

**Comment by eliotjoe** [comment]
@jonthornton Great! The issue is fixed now.
