### ISSUE TITLE
it stopped working with Google Caja sometimes last week

### ISSUE THREAD

**Issue by arturboszczyk** [jonthornton/jquery-timepicker#409]
Hi,

The library stopped working with Google Caja. It was working fine till last week. You can check this with Caja Playground or by following this link:

http://caja.appspot.com/#http://jonthornton.github.io/jquery-timepicker/

Looking forward to solve this problem as we rely heavily on this library.

CHeers,
Arthur

**Comment by jonthornton** [comment]
Hi Arthur, I'm unfamiliar with Google Caja and not sure what I'm looking at in that link. Are there errors outputted anywhere? Any way to confirm the previous versions of timepicker worked?

**Comment by arturboszczyk** [comment]
You can click on this link
http://caja.appspot.com/#http://jonthornton.github.io/jquery-timepicker/
and then click CAJOLE and the source tab. Tab will change to RENDERED RESULTS on which you can see that none of the timepicker boxes works.

**Comment by arturboszczyk** [comment]
I have also reported issue here:
https://code.google.com/p/google-caja/issues/detail?id=1969&can=4&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary

**Comment by jonthornton** [comment]
Yes, I can see that the timepicker doesn't work. I need to confirm that it did work at one time and identify when it broke so I know where to look for the fix. If you post a working Cajole with a previous version of timepicker I can look into this further.

**Comment by arturboszczyk** [comment]
It could be the issue with Caja as all previously working fine pages, stopped working. See new comment here: https://code.google.com/p/google-caja/issues/detail?id=1969

**Comment by jonthornton** [comment]
OK, I'm going to close this for now. If you can isolate the problem to a specific version of Timepicker please reopen.
