### ISSUE TITLE
Trying to select textbox in gridview at edititemtemplate in javascript

### ISSUE THREAD

**Issue by kyabroudi** [jonthornton/jquery-timepicker#410]
using ASP.net , I'm trying to call timepicker for textbox within edit template gridview  but getting 'NullReferenceException ' 
I can't get the id for that text box to assign time picker ..

$('#<%=gvView_test.FindControl("tb_test").ClientID%>')

any help..

**Comment by jonthornton** [comment]
Sorry, I don't have any experience with ASP.net.
