### ISSUE TITLE
getTime returns null when a formatting function is provided

### ISSUE THREAD

**Issue by CharlesMoore** [jonthornton/jquery-timepicker#411]
Providing a formatting function, rather than a PHP-style format string, causes the getTime method to always return null. Here's some sample code:

```javascript
<html>
   <head>
      <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.6.8/jquery.timepicker.css">

      <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.6.8/jquery.timepicker.js"></script>
   </head>
   <body>
      Here's a time entry box: 
      <input type='text' id='timepick' />

      <script>
         var $tp = $("#timepick");
         $tp.timepicker({ timeFormat: DisplayTimeFromDate });
         $tp.on("change", null, null, processChange);

         function processChange()
            {
            var result = $tp.timepicker("getTime", new Date());
            }

         function DisplayTimeFromDate(date)
            {
            var hours = date.getHours();
            var mins = date.getMinutes();
            return hours + " hours and " + mins + " minutes";
            }

      </script>
      
   </body>
</html>
```

**Comment by jonthornton** [comment]
This isn't specific to using a function for `timeFormat`; it can happen with a PHP-style string:

```javascript
$tp.timepicker({ timeFormat: "G \\h\\o\\u\\r\\s \\a\\n\\d i \\m\\i\\n\\u\\t\\e\\s" });
```

Timepicker would need ability to override the default time parsing to support `timeFormat`s like this. This probably won't make it into any 1.x releases. It'll get serious consideration for 2.0.

**Comment by CharlesMoore** [comment]
Okay, but then I guess I'm confused as to why the description of the timeFormat option in the Usage section for the timepicker says this:
> Alternatively, you can specify a function instead of a string, to use completely custom time formatting. In this case, the format function receives a Date object and is expected to return a string.

**Comment by jonthornton** [comment]
It says that because you can in fact use a function for formatting. 

The issue here is the `getTime` method. As you've pointed out, it's broken for non-standard time formattings, regardless of whether that formatting is specified with a function or a string. I agree that it severely limits the usefulness of specifying a function for timeFormat.

The issue will not be fixed in the 1.x version of Timepicker because it requires significant refactoring of the Timepicker internals. I work full-time and maintain this project as a hobby; unfortunately I haven't had enough time to make such extensive changes.

**Comment by CharlesMoore** [comment]
Ah okay, I misunderstood. It certainly *appears* initially that non-standard formattings work because they appear correctly in the drop-down. Anyway, I don't mean to be critical. I certainly understand that this is not your first priority. And to be clear, I really like the timepicker; it's working great for me. (I just wish I could do a slightly different format. *Not* the goofy one in my sample code.)

**Comment by jonthornton** [comment]
No worries. This issue needed to be pointed out. It's helpful feedback.

Just curious - what's that "slightly different format"?

**Comment by CharlesMoore** [comment]
I like "a.m." and "p.m." (note the periods). I realize it's kind of old-style, but I just think it's more elegant.

**Comment by jonthornton** [comment]
http://jsfiddle.net/jonthornton/f9a84sq3/

**Comment by CharlesMoore** [comment]
Oh, that's such a good idea. Using the lang option. Thank you for suggesting that!
