### ISSUE TITLE
multiple timepicker inputs with scroll

### ISSUE THREAD

**Issue by raghavendra-kulkarni** [jonthornton/jquery-timepicker#414]
Time picker doesnot get its position updated with scroll , to fix this i added the timepicker as sibling to input. where it scroll with input . but the problem is when dialog having timepicker input has tiny scroll, mousewheel event on timepicker is not recievied. hence mousewheel event fails.
![screenshot 19](https://cloud.githubusercontent.com/assets/10195024/9191607/e98f4fe0-4020-11e5-99a5-5180233965a4.png)

**Comment by raghavendra-kulkarni** [comment]
related to: Dropdown does not scroll with input when using `appendTo` option

**Comment by jonthornton** [comment]
I can't help without an example of the problem. Please post a jsFiddle or some other link that demonstrates the problem and I'll take a look.
