### ISSUE TITLE
documentation seems wrong for timeFormat

### ISSUE THREAD

**Issue by chilipepper987** [jonthornton/jquery-timepicker#415]
In the docs for `timeFormat`, when you make it a function, the doc seems to say that your custom function should be returning a format string.

However, the custom function should be returning the actual time string, not a format string, ie...

    if ($.type(settings.timeFormat) === "function") {
			return settings.timeFormat(time);
	}

**Comment by jonthornton** [comment]
Good point. Thanks!

**Comment by chilipepper987** [comment]
NP. I love this plugin! Made it ridiculously easy to implement a time picker when I needed one. Thanks for writing back so quickly and keep up the great work!
