### ISSUE TITLE
'scrollDefault': 'now' property not working effectively

### ISSUE THREAD

**Issue by Sonal824** [jonthornton/jquery-timepicker#416]
It doesn't make sense to show a time that has just recently passed.  For example, if it is 10:19, even though it is closer to 10:15 than it is to 10:30, we don't want the top value in the dropdown list to be 10:15.
here is fiddle for it. http://jsfiddle.net/sona824/gpex91mk/1/

**Comment by jonthornton** [comment]
That's deliberate. The timepickers in Google Calendar do the same thing.
