### ISSUE TITLE
Problem with readonly input

### ISSUE THREAD

**Issue by quaertym** [jonthornton/jquery-timepicker#417]
I am trying to use this library with a large ember.js app and I need to disable text editing for the input that triggers timepicker. I know this has been discussed in https://github.com/jonthornton/jquery-timepicker/issues/109 but my opinion is that an input being readonly does not imply timepicker should not work. Also `useSelect` is not an option for me.

I have a few solutions for this:
* Add an option to opt-out (like `allowReadonly`)
* Check `disabled` attribute instead of `readonly`
* If timepicker should be readonly for some use cases, another option can be added to the timepicker object itself.

It is really a burden to maintain a fork just for a single line change. I hope you can help.

If you agree with any of these solutions, or have another solution I can work on a PR.

**Comment by jonthornton** [comment]
The `disableTextInput` option should meet your needs.

**Comment by quaertym** [comment]
Thanks :+1: , I was using an old version.
