### ISSUE TITLE
Fix for 'now'

### ISSUE THREAD

**Issue by gregand1977** [jonthornton/jquery-timepicker#418]
In v1.6.8 in _time2int (object) you're multiplying hours by 3600 and minutes by nothing.  Flip it and it works now.

**Comment by jonthornton** [comment]
Timepicker is now on version 1.8.1. There may have been a bug in 1.6.8 but it's since been fixed. I'm not sure I understand the problem.

**Comment by gregand1977** [comment]
Well I’m happy to see that the version number keeps going up but even
so in line 1082 you multiply hours by 3600 and seconds by nothing.  I’m
not a math wiz but that causes problems.  For us, calling timepicker with
“now” as specified by doc grabbed a new Date() then did the faulty math
and came up with a number that had the wrong am/pm.  Perhaps your
bug-fixed fixed it someplace else or compensated somehow.  Either way I’m
happy with my patched copy for now, works pretty well.

Nice plug-in, just didn’t work for us till we debugged it.

**Comment by jonthornton** [comment]
This is the code you're referring to.
```javascript
if (typeof(timeString) == 'object') {
	return timeString.getHours()*3600 + timeString.getMinutes()*60 + timeString.getSeconds();
}
```

The code returns the number of seconds past midnight. There are 3600 seconds in an hour, 60 seconds in a minute, and 1 second in every second.
