### ISSUE TITLE
Jqery Time picker 

### ISSUE THREAD

**Issue by mmsdhinesh** [jonthornton/jquery-timepicker#419]
How to change jquery select timepicker step value dynamically form database?

**Comment by jonthornton** [comment]
This is beyond the scope of what I can help with.

**Comment by mmsdhinesh** [comment]
*MR. Jonthornton / jquery - time picker,*


   I am working jquery select time picker using ajax with set step value 
dynamically , i want change the doctor name with corresponding time 
duration showing for patient appointment login but
   time picker doesn't refresh already given value display for the step 
, did you help me to resolve that problem.

Thank you
