### ISSUE TITLE
On first click the dropdown is not aligned correctly with the textbox

### ISSUE THREAD

**Issue by mmiller678** [jonthornton/jquery-timepicker#420]
I tested this in IE and Chrome on Windows and on the first click the dropdown is misaligned with the textbox (it is about 15px to far left).  When its invoked a second time it aligns correctly.  The issue doesn't seem to be present in FF.  Attached is an image of the issue.

![timepicker issue](https://cloud.githubusercontent.com/assets/3980108/9151126/0b9a2560-3de7-11e5-9ea1-dc6ae2075628.png)

http://jsfiddle.net/qxgwk3wj/6/

**Comment by mmiller678** [comment]
I tried to reproduce this in JSFiddle but couldn't so its probably an issue with how its parented or something else in the markup.  Closing.

**Comment by jonthornton** [comment]
I can't see the error with the jsFiddle in Chrome on a Mac. (This includes on the first click)

![screen shot 2015-08-09 at 9 05 04 pm](https://cloud.githubusercontent.com/assets/196831/9157841/60811bda-3eda-11e5-863a-700c338f1ac5.png)

**Comment by mmiller678** [comment]
It seems to have to do with the height of the window when its rendered.  If you make the window height close to the value specified for the min-height it occurs on Chrome.  I played around with the window height in the fiddle a bit to reproduce it tonight but was able to as you can see below.   

![untitled](https://cloud.githubusercontent.com/assets/3980108/9158304/795a92be-3ee2-11e5-98bd-93dc47fb3687.png)

**Comment by jonthornton** [comment]
Sorry, I'm still not able to reproduce this bug. I'll have to try to get my hands on a PC to test with.

**Comment by raimi6** [comment]
Hey, I have the same problem, can't find a solution. I am using Boostrap 3.
On the first click the dropdown is misaligned with the textbox(~15px), bootstrap has for rows margin-right, left:-15 px. And col has  padding-right,left:15px 
```
<div class="col-md-3">
     <div class="form-group">
           <label class="control-label">Time</label>
           <v-time class="input-sm form-control" name="time"> </v-time>
     </div>
</div> 
```

![image](https://user-images.githubusercontent.com/7153091/29057310-1ddaf70c-7c12-11e7-8cc5-bcd540c73976.png)

**Comment by jonthornton** [comment]
@raimi6 can you post a working example? It's tough to debug this without the stylesheets.
