### ISSUE TITLE
Type ahead problem

### ISSUE THREAD

**Issue by cwurld** [jonthornton/jquery-timepicker#422]
Hi,

I use scrollDefault to get the widget close to the time I expect the user will want. For example on a labor time sheet, the day usually starts at 8:00am. 

The problem is when the default is near 8:00am and the user types a 6 to get to 6:00am, it jumps to 6:00pm. I would expect that as the user is inputting free text, the auto select choices would update to the nearest time. 

I can see this same issue on your demo page in the Scroll Default example. It's 9:00am now. If I type a 7, it jumps to 7:00pm. I would expect it to jump to 7:00am.

Thanks

**Comment by jonthornton** [comment]
My thinking when I built it that way was that `scrollDefault` would be set to the earliest time most users would be interested in. If you set it to 6am, 8am is still visible to users in the dropdown, but if you set it to 8am users have to scroll up to see 6am. Along those lines typeahead jumps to values in the future from the `scrollDefault` time.

You could set an input default of 8am and still set the `scrollDefault` to something earlier, like 5 or 6am. If no `scrollDefault` is set the typeahead defaults to am values until the user types "p".

I understand it's confusing to have `scrollDefault` coupled to the typeahead behavior. I plan on re-evaluating this for v2 of the plugin.
