### ISSUE TITLE
Modifying timepicker from ajax 

### ISSUE THREAD

**Issue by catalinfeier** [jonthornton/jquery-timepicker#424]
I want to modify the options of a timepicker based on the result of a ajax result. However, when i call the timepicker function from the ajax success function i get this error: 'Uncaught TypeError: $(...).timepicker is not a function'.

```javascript
//Initialisation
$('#timepicker').timepicker({
                'timeFormat': 'H:i',
                'step': 15,
                'minTime' : '08:00',
                'maxTime' : '23:00',
                'forceRoundTime' : true
            });
//ajax request
function ajaxCall(newValue){
            $.ajax({
                url: '/search/url',
                type: 'POST',
                data: { query : newValue },
                dataType: 'JSON',
                success: function(response){
                    console.log(response);
                    $('#timepicker').timepicker('option', 
                           'disableTimeRanges',[["08:00", "08:30"]]);//tried this, doesn't work
                    $('#timepicker').timepicker('option', 
                          'disableTimeRanges',response);//doesn't work either
                }
            });
        }
```

```html
//html element
<input autocomplete="off" id="timepicker" class="time ui-timepicker-input "
                                type="text" style="width:120px" name="timepicker">
```

Maybe this is something obvious, but i am not seeing it. Any pointers would be appreciated.

**Comment by jonthornton** [comment]
Can you post this as a jsFiddle? I don't see any obvious errors in the code you posted, so my best guess is that there's something else on the page that's interfering with it.

**Comment by catalinfeier** [comment]
When i tried it in jsFiddle it worked. Apparently, my issue is not directly related to the timepicker, but to the fact that i call it after the document is ready in a @section of a laravel blade view (last part won't make sense if you are not familiar with the Laravel framework). I don't know how to solve it, but given the same use case works in jsFiddle, the problem must stem from somewhere else. So unless there is someone around here familiar with Laravel and has a solution, this issue can be closed.

**Comment by jonthornton** [comment]
Sorry, I don't have any experience with Laravel. Best of luck.
