### ISSUE TITLE
Setting input as readonly breaks showOn "click"

### ISSUE THREAD

**Issue by jpgilchrist** [jonthornton/jquery-timepicker#425]
Obviously readonly would break the showOn "focus". However, you would not expect it to break showOn "click". I have seen that you have disableInputText, which I'm currently using, but I don't want the user to focus the input at all.

**Comment by jonthornton** [comment]
Setting the input to readonly disables timepicker completely. This is deliberate.

Perhaps a developer wants to use the readonly attribute as intended. Maybe part of their form gets dynamically set to readonly in certain situations. If timepicker remains active despite the readonly attribute, the developer has the do the extra step of binding/unbinding timepicker every time their form toggled readonly on/off.

Setting `document.ontouchstart` to some value and enabling `disableTouchKeyboard` in the timepicker options will trick timepicker into blurring as soon as a user clicks an input. Messing with  `document.ontouchstart` is global and may confuse other code. You might be better off forking and hardcoding `_hideKeyboard()` to return `true`.

**Comment by jwee6** [comment]
As mentioned readonly disables timepicker completely, I tried using disableTextInput however it doesn't seem to be disabling me from manually typing into the input. What may I be missing here?


      $('#reservation_start_time').timepicker({
         'disableTextInput': true
      });

Thanks

**Comment by jonthornton** [comment]
Can you post a jsFiddle demo?

**Comment by jwee6** [comment]
Sorry, I was forking from a ROR gem it must have been faulty. It's working great now, thanks for your work!

**Comment by lsintampa** [comment]
However, if you do disableTextInput - the user can still focus the field, delete values and end up posting invalid information.  Any fix - work around to stop users from entering the field at all so they have no choice but to select a valid entry?

**Comment by matheusjardimb** [comment]
`tab` to next field does not work if `'disableTextInput': true`. Shouldn't it?

**Comment by jonthornton** [comment]
@matheusjardimb indeed it should! Thanks for pointing that out.

**Comment by pronexo-odoo** [comment]
This works for me

<input id="myDatePicker" class="readonlyjm"/>


$('#myDatePicker').datepicker({
/* options */
});

$('.readonlyjm').on('focus',function(){
$(this).trigger('blur');
});

**Comment by ajtruckle** [comment]
I am confused by this conversation. Does `disableTextInput': true` work? I would like the user to click and select a time but not type a time. Either that, or have a built-in mechanism where if the user types a time that at validation stage it prevent processing if the value is outside the min/max values.
