### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by barabaka** [jonthornton/jquery-timepicker#426]
Got TypeError when trying to select field with existing value, using with latest jquery 1.11.3. 

![typeerror](https://cloud.githubusercontent.com/assets/103233/9394427/27e9c8c0-4791-11e5-9bdb-17a53441e7ac.PNG)

**Comment by jonthornton** [comment]
Can you post a jsFiddle that demonstrates the problem?

**Comment by barabaka** [comment]
I tried to make a simple demo but unfortunately I can't reproduce it anymore. However, it still gives me an error in my project where there are other libraries and css files. So this could be the result of some combination of js libraries and/or CSS files that causes this. I will try to investigate more.

**Comment by jonthornton** [comment]
K. Reopen the issue if you manage to find something.
