### ISSUE TITLE
The "changeTime" event does not always fire when a value changes

### ISSUE THREAD

**Issue by dswitzer** [jonthornton/jquery-timepicker#428]
I'm using timepicker w/the datepair.js and I've noticed that the "changeTime" event does not always fire when the value is updated.

The problem appears that in some cases, only the "selectTime" event gets triggered. What I'm seeing is when I use the datepair plugin in conjunction w/the default datepicker, if I set a date/time, but then go and change the time to something invalid (like "aaaa"), the datepair resets the time, but only the "selectTime" is triggered when the "setTime" method is called.

What happens is the logic only hits line 787 of the code, which is just:

```
self.trigger('selectTime');
```
I would like to see the "changeTime" event fired any time the value changes--so there's a single event we can listen to that will always fire when the time changes.

In the meantime, I'm having to have my code listen to changeTime and selectTime so that it correctly works--which means my logic is usually getting triggered multiple times, so I'm having to debounce the call.

**Comment by jonthornton** [comment]
I'm having trouble reproducing this issue (latest Chrome and Firefox on OS X). Here's my methodology:

1. On demo page use devtools to log the `changeTime` event for one of the pickers:
`$('#datepairExample .time').on('changeTime', function(){ console.log('changeTime') });`
2. Set the start date and start time. Datepair will fill in end date and time.
3. Set end time to 3 hours after start.
4. Manually change end time to 'aaa'. Datepair resets it to default value and `changeTime` fires.
