### ISSUE TITLE
valudation on 00:00:00 value 

### ISSUE THREAD

**Issue by amera7md** [jonthornton/jquery-timepicker#429]
i need to insure the user will enter data inside time picker and not leving it 0's  , i use knockoutjs to bind and set data inside the control , Kindly i would like to know if is there a build in validaiton to insure the time filled not left 00:00:00 
if (jQuery().timepicker) {
        $('.timepicker-default').timepicker({
            autoclose: true
        });
        $('.timepicker-24').timepicker({
            autoclose: true,
            minuteStep: 1,
            showSeconds: true,
            showMeridian: false
        });
    }

**Comment by jonthornton** [comment]
jquery-timepicker doesn't have an `autoclose` option. I think you're looking for http://jdewit.github.io/bootstrap-timepicker/
