### ISSUE TITLE
disableTimeRanges

### ISSUE THREAD

**Issue by dharmagk** [jonthornton/jquery-timepicker#430]
i want to use the disableTimRanges like this. but its not supporting please help me...
i am having morethan 5 break timings . i have generate the string like mentioned below in for loop....
breakeList		+= "['"+bStartTime+"','"+bEndTime+"']"+",";

breakeList				= breakeList.slice(0,-1) ;
and finally i placed the breakeList	variable in disableTimeRanges like disableTimeRanges : [breakeList].
i have used eval also. its displaying last value only.
var times= "['9:00am', '10:00am'],['10:30am', '12:30am']";
$('#test').timepicker(
    {
       'minTime': '8:00am',
        'maxTime': '6:00pm',
        'disableTimeRanges': [times],
        'step': 30
    }
);

**Comment by jonthornton** [comment]
Sorry, I'm not able to help without seeing a complete demo. Can you post a jsFiddle?

**Comment by dharmagk** [comment]
thanks for your reply dude.This is the great script. i got the solutions. I convert the string to two dimensional array now its working fine.
like  $("#test").timepicker({'disableTimeRanges': eval(breakeList)})
 thanks for your time dude.
