### ISSUE TITLE
Basic functionality question

### ISSUE THREAD

**Issue by ricktig** [jonthornton/jquery-timepicker#431]
Hello - I'm setting up a very simple date picker and would like the format to display at 9:99am or 9:99pm.  When I look at the very basic example on the project website, I set up my object as follows:

$('#eventtime').timepicker({	
	minTime:'7:00am', //minimum time 7am
	maxTime:'10:00pm' //maximum time 10pm
});

This gives me something pretty close (99:99AM) but in 16 or 20 point font and no scroll bar in the list.  I'm unable to see the drop down styling in Firebug.  Do you have info on how to change the styling of this input to be smaller and display the scroll bar?

Rick R.

**Comment by jonthornton** [comment]
All of the styling is set in `jquery.timepicker.css`. Refer to the [theming](https://github.com/jonthornton/jquery-timepicker#theming) section of the documentation.
