### ISSUE TITLE
A problem of disableTextInput is set to true

### ISSUE THREAD

**Issue by constant0924** [jonthornton/jquery-timepicker#433]
Found a small problem, when I input status is at the time of Chinese input method, according to a few letters, casually with input directly fast shortcuts "shift", the text has been added in the input box.
![bug1](https://cloud.githubusercontent.com/assets/3156863/9806920/ff5a8ac2-587d-11e5-886a-433ebd8fb946.png)
![bug2](https://cloud.githubusercontent.com/assets/3156863/9806922/0643c754-587e-11e5-9ea5-02fe486468e4.png)

**Comment by jonthornton** [comment]
I apologize but I don't understand. Can you post step-by-step instructions to reproduce the problem?

**Comment by constant0924** [comment]
@jonthornton 
1, use the sogou input method, switch input in Chinese
2, input box to get focus
3 any letters, keyboard input, displays text input method directly use sogou input method switch shortcut shift in both Chinese and English
4, found that after 1 ~ 3, input box has input the result is not what I want
