### ISSUE TITLE
I have an angular table where each row has a timepicker object, always updates first row

### ISSUE THREAD

**Issue by mikeerickson** [jonthornton/jquery-timepicker#434]
The code to setup picker

$('.timepicker').timepicker({
      'step':         5,
      'showDuration': true,
      'timeFormat':   'g:ia'
    });

The input field which contains the current time value (user can select field here) all works as expected.

However, placing on a bootstrap button icon, I can get the picker to display, however, cant figure how to get the selected value.

````

<button type="button" class="timepicker btn btn-default" ng-model="ts[$index]" ng-change="updateTime(subQuery, $index)" ng-hide="subQuery.isLookingForEmpty()">
<i class="timepicker glyphicon glyphicon-time"></i>
</button>

````

**Comment by jonthornton** [comment]
You'll need to use the `getTime` method.

```javascript
var timeObj = $(buttonElement).timepicker('getTime');
```
