### ISSUE TITLE
jquery-timepicker only allow to enter 23.5 hours if interval is 30 mins

### ISSUE THREAD

**Issue by ashokghoghari** [jonthornton/jquery-timepicker#435]
Hi,

Thanks for this awesome control.

I was testing this control and found i could not enter 24 hours if i set 30 min interval.

can you please guide me or fix this issue?

Thank you.

Warm Regards,
Ashok Ghoghari

**Comment by jonthornton** [comment]
Hi Ashok, I'll need more information to help. Can you post a jsFiddle that demonstrates the problem?
