### ISSUE TITLE
Error in jquery.timepicker.js

### ISSUE THREAD

**Issue by jetyamato** [jonthornton/jquery-timepicker#438]
When I used it for the first time, it works fine. There are no issues in the console. However, when I tested the webpage I am working on, the console threw this back at me:

TypeError: timeString.getHours is not a function

Not only that, the timepicker won't work anymore.

**Comment by jonthornton** [comment]
I'll need more information to help. Can you link to a jsFiddle or some other example that demonstrates the problem?
