### ISSUE TITLE
Change Event Triggered Twice

### ISSUE THREAD

**Issue by danielson317** [jonthornton/jquery-timepicker#439]
Attaching an onChange event to a timepicker triggers the change event twice when a new value is selected.

    <div class="form-item type-time name-start_time">
        <label for="start_time"> Start Time          </label>
        <input type="textfield" name="start_time" maxlength="8" size="10" class="timepicker once ui-timepicker-input processed" autocomplete="off">
        <div class="description">Use the format: 11:59 PM.</div>
    </div>

    $(".name-start_time input").not(".once").addClass("once").timepicker({"step":"15","minTime":"12:00 AM","maxTime":"11:59 PM","timeFormat":"h:i A","scrollDefault":"now"}).mask("b9:t9 pm");    
    $('.name-start_time input').on('change', scheduleTemplateUpdateStartTime);
    function scheduleTemplateUpdateStartTime()
    {
        console.log('hello (I'm printed twice');
    }

A brief look at the code I see that `_setTimeValue` is called by onChange and triggers an onChange event: `self.trigger('selectTime').trigger('changeTime').trigger('change', 'timepicker');`

Removing `.trigger('change', 'timepicker')` seems to fix it for me.

**Comment by jonthornton** [comment]
I couldn't reproduce this on the Timepicker demo page. It's possible that the mask() call could be interacting with Timepicker to cause weird results. Could you post a jsFiddle that demonstrates the problem?
