### ISSUE TITLE
hightlight text issue

### ISSUE THREAD

**Issue by ohiowebpro** [jonthornton/jquery-timepicker#440]
In firefox 40 (not sure with others) if you slightly move pointer when selecting a time it highlights most of the text on the page, and can confuse the user. I am using bootstrap 3. Adding this to the CSS seems to help:

.ui-timepicker-list li {
     -webkit-touch-callout: none;
     -webkit-user-select: none;
     -khtml-user-select: none;
     -moz-user-select: none;
     -ms-user-select: none;
     user-select: none;
 }

**Comment by jonthornton** [comment]
I wasn't able to reproduce the problem on the Timepicker demo page. (Using FF 41; it upgraded itself when I checked the current version.)

Perhaps it's caused by some interaction between Timepicker and Bootstrap? This ticket will help anyone else who runs into the issue.
