### ISSUE TITLE
Time selections not being captured

### ISSUE THREAD

**Issue by schatridge** [jonthornton/jquery-timepicker#442]
I have imported the css and js files, and have called the timepicker function in code. On my page, the timepicker scroller appears, including the 15-minute step I initialized it with, but whenever I click on a time, it is not captured into my text field. Am I missing a step in implementation?

**Comment by jonthornton** [comment]
It's hard for me to tell without code or a working example. Could you share a link or jsFiddle that demonstrates the problem?
