### ISSUE TITLE
TypeError: self.on is not a function

### ISSUE THREAD

**Issue by eknoerr** [jonthornton/jquery-timepicker#443]
I am trying to use the Datepair project, but am getting an error in the init on the timepicker code.  I am working in a .NET 4.5.1/MVC/C# environment.  We put the jQuery include (currently version 1.9.1) within a master Layout page so not directly on the page.  We have many jQuery calls with the page that work as expected.  

When I wire up the timepicker, I am getting the error with the following line of code

![image](https://cloud.githubusercontent.com/assets/14874858/10221789/62c1c508-681e-11e5-99a0-9c03dc8989f3.png)

Which seems to indicate that the code does not think jQuery is loaded.  When I add a reference to the main jQuery file within the cshtml page itself, then the timepicker/Datepair code works as expected, but including the file a second time causes errors with other jQuery calls.

Have you run into anything like this before?  And is there something specific I should be looking for within my setup in order to resolve this issue?

**Comment by jonthornton** [comment]
That's a very strange error. `$.prop()` would get called before `$.on()`; both are jQuery methods so I'd expect it to throw an error.

My best guess would be that the timepicker script is loading before the jQuery script, but I don't have enough context to speculate more. I don't have any experience with .NET.
