### ISSUE TITLE
different format for text and value on time dropdown

### ISSUE THREAD

**Issue by eaponiente** [jonthornton/jquery-timepicker#444]
is this possible? I need to have a different format for the value and the text that is being shown to users. 

say, 

i have a dropdown 
12:00 AM
1:00 AM

then if I choose 12:00 AM the value underlying it is 00:00:00 not 12:00 am, I'm looking into the docs and it seems Its not implemented, timeFormat option is for both what about different values?
Thanks
here is my code
$('.timepicker').timepicker({ 'timeFormat': 'h:i A' });

**Comment by jonthornton** [comment]
Sorry, that functionality is not supported. Your best be is to have a hidden input that gets updated on the time input's `change` every, and convert time formats in the event handler.
