### ISSUE TITLE
Why does useSelect not appear as a default setting?

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#445]
Only reason I noticed is because I got this error in from rollbar.com
`TypeError: Cannot read property 'useSelect' of undefined`
and I set it one place, but not in others.

Maybe it doesn't need to be there?

    // Global defaults
    $.fn.timepicker.defaults = {
        className: null,
        minTime: null,
        maxTime: null,
        durationTime: null,
        step: 30,
        showDuration: false,
        showOnFocus: true,
        showOn: ['click', 'focus'],
        timeFormat: 'g:ia',
        scrollDefault: null,
        selectOnBlur: false,
        disableTextInput: false,
        disableTouchKeyboard: false,
        forceRoundTime: false,
        roundingFunction: function(seconds, settings) {
            if (seconds === null) {
                return null;
            } else {
                var offset = seconds % (settings.step*60); // step is in minutes

                if (offset >= settings.step*30) {
                    // if offset is larger than a half step, round up
                    seconds += (settings.step*60) - offset;
                } else {
                    // round down
                    seconds -= offset;
                }

                return seconds;
            }
        },
        appendTo: 'body',
        orientation: 'l',
        disableTimeRanges: [],
        closeOnWindowScroll: false,
        typeaheadHighlight: true,
        noneOption: false,
        show2400: false,
        stopScrollPropagation: false
    };

**Comment by jonthornton** [comment]
Can you post a jsFiddle that demonstrates the problem?

**Comment by KrunchMuffin** [comment]
No, cause it's not happening to me. I use rollbar.com to report errors from users.
I was mainly just asking a question. "Why does useSelect not appear as a default setting?"

**Comment by jonthornton** [comment]
Good point!. Fixed in https://github.com/jonthornton/jquery-timepicker/commit/e3c7638386c94a79e2bd0a278cfd6f55ff1f1d52
