### ISSUE TITLE
24:00 shown in options when show2400 is false

### ISSUE THREAD

**Issue by low** [jonthornton/jquery-timepicker#448]
With the `show2400` option set to `false`, I still saw the 24:00 in the time options. I made this change (line #1049):

    if (seconds === _ONE_DAY) hour = settings.show2400 ? 24 : 0;

...which seems to have fixed it.

**Comment by jonthornton** [comment]
Closed in https://github.com/jonthornton/jquery-timepicker/commit/21b504ae646777fc8f22152d3e83e1ecbd4059e2
