### ISSUE TITLE
durationTime docent work as i expect

### ISSUE THREAD

**Issue by Widda** [jonthornton/jquery-timepicker#449]
I can't get the durationTime and showDuration to show time från maxTime. If maxTime is set to 11:00 i would lik the time picker to show:
10:00 (1 hr)
10:15 (45 min)
10:30 (30 min)
10:45 (15 min)
11:00

Now it always calculate after the minTime.
I have set 'minTime': '10:00', 'maxTime': '11:00', 'durationTime': 'maxTime', 'showDuration': true
Is this a bug or can't this be done?
Best regards

**Comment by jonthornton** [comment]
You're close. Try  `'durationTime': '11:00'`;

**Comment by Widda** [comment]
Thanks!
