### ISSUE TITLE
End time list not hiding on single click

### ISSUE THREAD

**Issue by tonymanuel** [jonthornton/jquery-timepicker#451]
Hello,
After adding the datepair plugin to my page ,the end time list is not closing after selecting the time. When i select the time from the list  the selected time gets highlighted and is shown in my input box but the list remains open until i click on it again. Once the list gets closed  every thing is normal and works fine without clicking the list twice to close it. When the page is refreshed i face the same problem that i need to click twice on the  end time list to close/hide it. If am manually typing the input then i have to press the enter key twice ,that is one press to complete the time and the other to close the list.

**Comment by jonthornton** [comment]
Can you post a jsFiddle that demonstrates the problem?

**Comment by tonymanuel** [comment]
Hi,
jsFiddle- http://jsfiddle.net/28uvg/493/

**Comment by jonthornton** [comment]
Thanks! It was actually a bug in the Datepair library.

**Comment by tonymanuel** [comment]
It works now. Thanks for your quick response.
