### ISSUE TITLE
Support callback function

### ISSUE THREAD

**Issue by mwkang** [jonthornton/jquery-timepicker#452]
```javascript
var t = $("#time").timepicker({
    'timeFormat': 'H:i',
    'showDuration': false,
    'scrollDefault': 'now',
    'step': 1,
    'forceRoundTime': true,
    'disableTextInput': true
});
console.log(t.val());
```
t.val() returns previous value.
But I want to current value when Immediately user selected time.
So, If timepicker supports callback function.
I try to like this.
```javascript
$("#time").timepicker({
    'timeFormat': 'H:i',
    'showDuration': false,
    'scrollDefault': 'now',
    'step': 1,
    'forceRoundTime': true,
    'disableTextInput': true
}, function(t){
    console.log(t.val());
});
```
So, Do you have a plan that this library support callback function?

**Comment by jonthornton** [comment]
Use [events](https://github.com/jonthornton/jquery-timepicker#events). See the [demo page](http://jonthornton.github.io/jquery-timepicker/) for an example.
