### ISSUE TITLE
disableTextInput is not working in version 1.7

### ISSUE THREAD

**Issue by shmdhussain** [jonthornton/jquery-timepicker#454]
disableTextInput is not working in v1.7 but working in 1.8

see the fiddle in v 1.8: http://jsfiddle.net/shmdhussain/rz8a0ntu/ 

see the fiddle in v 1.7: http://jsfiddle.net/shmdhussain/5q1mwxjk/

Is Updating timepicker in our application to 1.8 from 1.7 will affect any functionality like any obsolete ones?

**Comment by shmdhussain** [comment]
I think the issue is with the minified version. working well with normal version.

Working good with 1.8.5 min and normal ones

**Comment by jonthornton** [comment]
Updating from 1.7 to 1.8 won't break anything.
