### ISSUE TITLE
Backspace detection on disableTextInput

### ISSUE THREAD

**Issue by QuentinFchx** [jonthornton/jquery-timepicker#456]
Currently you're preventing the `keypress` event to disable the input.
But it does not work with the `backspace/delete` key, as [it does not produce a character](http://stackoverflow.com/questions/4843472/javascript-listener-keypress-doesnt-detect-backspace)
We want to use `keydown/up` instead.

**Comment by jonthornton** [comment]
Backspace and delete are caught by the keyup handler: https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.js#L893

**Comment by QuentinFchx** [comment]
@jonthornton in the snippet of code you linked, you `return true` when `settings.disableTextInput` is enabled.
But, according to [the jQuery documentation](http://api.jquery.com/on/)
> Returning `false` from an event handler will automatically call `event.stopPropagation()` and `event.preventDefault()`.

I recorded a small video showing its behaviour when using the `backspace` key on my timepicker
![](http://f.cl.ly/items/2a0J0e0a211y282j0M0L/Screen%20Recording%202015-11-09%20at%2010.57%20AM.gif)

You can reproduce it on a webkit based browser (the keypress event seems to be fired on Firefox, I'm using Chromium)
- Go to https://www.getbannerman.com/book-security
- Select `x:30pm` on a timepicker
- Set your cursor between `3` and `0`
- Press backspace

**Comment by jonthornton** [comment]
Thanks for being persistent! Of course, I had been testing on Firefox ;)
