### ISSUE TITLE
request: ability to add classes to li elements

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#459]
Reason I ask, and may this is something you could add as enhancement, I noticed some users are finding it hard to differentiate between am and pm times. Would handy to be able to make the background of the li different colors. say a light blue for pm and light yellow for am.

**Comment by jonthornton** [comment]
Check out [Theming](https://github.com/jonthornton/jquery-timepicker#theming) in the readme for docs.

**Comment by KrunchMuffin** [comment]
never really noticed that before. You have to really look at the example to figure it out. thanks tho.
