### ISSUE TITLE
getTime returns 1 Feb 1970 instead 1 Jan 1970

### ISSUE THREAD

**Issue by molodyukov** [jonthornton/jquery-timepicker#463]
Docu: Get the time using a Javascript Date object, relative to a Date object (default: Jan 1, 1970).

example on http://jonthornton.github.io/jquery-timepicker/
$('#basicExample').timepicker('setTime', '04:00am');
$('#basicExample').timepicker('getTime'); // Date {Sun Feb 01 1970 04:00:00 GMT+0100 (CET)}
```javascript
function _generateBaseDate()
{
    return new Date(1970, 1, 1, 0, 0, 0);  // 0 - Jan, 1 - Feb etc.
}
```

**Comment by jonthornton** [comment]
Closed by https://github.com/jonthornton/jquery-timepicker/commit/9571d4d9a432c622bb736ddfe1f62399b390fdbb

Thanks for reporting!
