### ISSUE TITLE
Timepicker opens when clicking on left below timepicker input

### ISSUE THREAD

**Issue by eagle0042** [jonthornton/jquery-timepicker#468]
I'm not sure what causes this, but using the most recent jquery-timepicker and Bootstrap 3.3.6 on a input text field, with a class of "form-control", causes a weird issue where clicking to the left gutter-ish area (anywhere after the input element) causes the timepicker to open.

https://jsfiddle.net/22gsavLm/

Anywhere in the yellow area highlighted below causes this only on Chrome. (tested in v47) Neither Firefox nor MS Edge show this. This area gets larger, based on screen size also.

![image](https://cloud.githubusercontent.com/assets/3215663/12102046/ef0019fa-b2fd-11e5-95aa-619a107f474d.png)

Not sure if this is just a odd combination of Bootstrap and jquery-timepicker, or if this is based on something changed in Chrome.

**Comment by jonthornton** [comment]
This appears to be strictly a Bootstrap+Chrome issue. You'll notice that if you remove Timepicker from your example, clicking the yellow area still focuses the input. This focus event is what's triggering Timepicker.
