### ISSUE TITLE
missing 'var' in for-in causes error in strict mode

### ISSUE THREAD

**Issue by ron-wade** [jonthornton/jquery-timepicker#469]
Line 64 of jquery.timepicker.js is `for (i in settings.showOn) {`. It should be `for (var i in settings.showOn) {`, with the added 'var'.

This is the only occurrence of this mistake in the file.

In a related note, I would have made this simple change and sent the pull request, but I kept getting a warning from grunt-contrib-uglify: `Warning: Cannot assign to read only property 'subarray' of /*!`, so I didn't bother.

**Comment by jonthornton** [comment]
I wasn't able to reproduce the Uglify error using a freshly closed repo. If you have any more info I'd be interested in fixing it.
