### ISSUE TITLE
I can't get it to run

### ISSUE THREAD

**Issue by muroshi** [jonthornton/jquery-timepicker#473]
According to your example I can't get it to run:
https://jsfiddle.net/rnr2wgv6/6/

Can you spot the problem?

**Comment by jonthornton** [comment]
Your example is missing jQuery.

**Comment by muroshi** [comment]
Thanks.

2016-01-17 18:42 GMT+01:00 Jon Thornton <notifications@github.com>:

> Closed #473 <https://github.com/jonthornton/jquery-timepicker/issues/473>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonthornton/jquery-timepicker/issues/473#event-517317474>
> .
>



-- 
Herzlich
Yannick Hagmann
