### ISSUE TITLE
.timpicker('destroy')

### ISSUE THREAD

**Issue by rmott78** [jonthornton/jquery-timepicker#474]
I have a text field that I add timepicker to based on a checkbox group value. I am looking for a way to remove timepicker from the text field if a different checkbox is selected.

```
$('input[name="X"]').change(function(){
      if ($(this).val()=="A"){
        $('#text-field').timepicker();
      } else {
        $('#text-field').timepicker("destroy");
      }
    }).change();

**Comment by jonthornton** [comment]
[`$.timepicker('remove');`](https://github.com/jonthornton/jquery-timepicker#methods)
