### ISSUE TITLE
Render on first touch (Mobile / Android)

### ISSUE THREAD

**Issue by espen** [jonthornton/jquery-timepicker#475]
By default jquery-timepicker does not render when touching the input for the first time on Android (Chrome). I have to tap the input one more time for jquery-timepicker to show. This can fixed by setting disableTouchKeyboard to true but the problem then is that the keyboard is completely disabled so it is not possible to manually enter a value.

Ideally I want jquery-timepicker to render on first touch and any subsequent touch will open the keyboard for manual entry.

**Comment by robjens** [comment]
Same problem in Chrome on Linux...
