### ISSUE TITLE
typing 10pm into field and tabbing shows 9pm

### ISSUE THREAD

**Issue by Glutnix** [jonthornton/jquery-timepicker#484]
I'm in New Zealand, we're currently in DST right now, making us UTC+13.

Right now, with `1.8.9` and with `master`, picking times with the mouse is fine, but typing a time in the afternoon causes a problem: 

Steps to reproduce.
* Be in NZDT timezone (unconfirmed if this matters)
* Type `10a` into a timepicker field and see `10:00am` in the dropdown. Press Tab or Enter and see `10:00am` in the field, as expected.
* Type `12p`, see `12:00pm`, as expected.
* Type `1p`, see `12:00pm`, expect `1:00pm` (afternoons don't work)
* Type `12:59pm`, see `12:59pm`, as expected
* Type `1:00pm`, see `12:00pm`, expect `1:00pm`
* Type `11p` see `10:00pm`, expect `11:00pm`
* Type `15` see `2:00pm`, expect `3:00pm`

Currently the [Github.io](http://jonthornton.github.io/jquery-timepicker/) page is running `1.8.7` and doesn't have this problem.

On a side note`1.8.7` is not available on npm `timepicker` package.

**Comment by Glutnix** [comment]
Had someone in a different timezone (Portugal) confirm it's not happening to them, making me think it's something to do with being in UTC+13.

**Comment by vbrendel** [comment]
I'm having this same issue, timezone is Melbourne (AEDT, UTC-11). Any time value in the afternoon jumps back by an hour. Also, the dropdown only populates time values up to 10:30pm.

**Comment by rupertbg** [comment]
Can confirm - looks like a daylight savings issue?

**Comment by jonthornton** [comment]
I suspect this is fixed by https://github.com/jonthornton/jquery-timepicker/commit/2fcde1617e5e2581eb945516293013d5ad7a0da7. I've tested by setting my laptop timezone to NZDT (I'm in NYC). Can anyone else confirm?

**Comment by Glutnix** [comment]
1.9.0 seems good. Checked it in NZST (UTC+12, the current time) and NZDT (UTC+13) by going back in time to February. Thanks @jonthornton

**Comment by jonthornton** [comment]
Great news! Thanks.
