### ISSUE TITLE
Using scrollDefault and useSelect

### ISSUE THREAD

**Issue by gudeidea** [jonthornton/jquery-timepicker#485]
Using scrollDefault and useSelect, scrollDefault stop working. Is this an known issue?

`var starttime = '08:00'; 
$('#scrolldate_start').timepicker({ 'scrollDefault': starttime, 'minTime': '08:00', 'maxTime': '23:00','timeFormat': 'H:i' , 'useSelect': true, 'step': 30});`

**Comment by jonthornton** [comment]
Yes, this is noted in the documentation for `useSelect`.
