### ISSUE TITLE
Timepicker doesn't work in Chrome for iOS

### ISSUE THREAD

**Issue by CoralSilver** [jonthornton/jquery-timepicker#486]
Using Chrome ver. 48 on iPad, on touch, timepicker drowndown shows for a fraction of a second and then disappears, so user cannot select time.  This is true on the demo page as well.

Setting ```useSelect: true``` it works, but I do not want to use that option if possible.

**Comment by KrunchMuffin** [comment]
Tracked it down to this line
https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.js#L218

If I comment that out, the picker stays up.

**Comment by KrunchMuffin** [comment]
there is another issue however, when you try to scroll, the list closes as you release touch.
