### ISSUE TITLE
Create timepicker on click wont show

### ISSUE THREAD

**Issue by Terroraapje** [jonthornton/jquery-timepicker#488]
I want to create a timepicker on click. But it won't show.
.time is an auto generated element

Code i (want to) use.
```
$('#date-list').on('focus', '.time', function(e){
      var $input = $(this);
      $input.timepicker();
      $input.timepicker('show');
});
```

**Comment by robjens** [comment]
Use `$('#date-list').triggerHandler('focus')` although in my case it doesn't solve anything since it is on a modal, it positions the dropdown top-left in the screen =/

**Comment by robjens** [comment]
Yeah...I'm gonna give up. Wasted too much time on this already. Now to explain why the timepicker won't show... is easier than getting it to work properly I recon. These kind of hacks are a solution to begin with.

**Comment by Terroraapje** [comment]
@robjens Thanks for trying!

**Comment by jonthornton** [comment]
@Terroraapje let the timepicker handing showing on focus. Just attach it to the input when you initialize the rest of your page.

```javascript
$('#date-list').timepicker();
```
