### ISSUE TITLE
noneOption bug

### ISSUE THREAD

**Issue by r3wt** [jonthornton/jquery-timepicker#492]
if setting a value of `-1` the plugin renders `11:59 PM`. also, the label is not shown.

repro:

```
$('.t-pickers').timepicker({
	'noneOption': [
		{'label':'All Day','value':-1}
	]
});
```

**Comment by jonthornton** [comment]
Thanks!

I wasn't able to reproduce the label not showing. Can you provide more info on how to reproduce that?
