### ISSUE TITLE
Unable to type 2400 military time

### ISSUE THREAD

**Issue by cscrudder** [jonthornton/jquery-timepicker#497]
Using the following configuration for time picker.
`$('.timepicker').timepicker({
                timeFormat: 'Hi',
                step: 5,
                ampm: false,
                show2400: true,
                minTime: '12:05am'
            });`

2400 is select-able on the drop-down however when the user attempts to type in 2400 the function _formatValue(e, origin) trips a rangeError.

**Comment by jonthornton** [comment]
Fixed by https://github.com/jonthornton/jquery-timepicker/commit/a2f08634aa23292ad44660299e2cc21f21d7ff5c
