### ISSUE TITLE
millisecond for the time picker

### ISSUE THREAD

**Issue by iccsi** [jonthornton/jquery-timepicker#501]
I have a timepicker and would like to set to a time to millisecond and using following code.
It gives me to hour, minute and second on the form.
I would like to have the time until millisecond.
Can you please advise how can I have the time with millisecond?
Your help and information is great appreciated,

 $('#MyTime').timepicker('setTime', new Date());

Regards,

Sourises,

**Comment by jonthornton** [comment]
jquery-timepicker doesn't support milliseconds.
