### ISSUE TITLE
Not possible to use French time format

### ISSUE THREAD

**Issue by henriklundahl** [jonthornton/jquery-timepicker#502]
It's not possible to use a French time format, i.e. `"G \\h i"`, since it wouldn't match the regex in the `_time2int` function.

**Comment by henriklundahl** [comment]
Would possibly be solved by https://github.com/jonthornton/jquery-timepicker/pull/472.

**Comment by sambapete** [comment]
I know your package is being used by https://github.com/edx/edx-platform.
How do I specify to use French instead of English in order to display the calendar?

**Comment by jonthornton** [comment]
Should be fixed now!
