### ISSUE TITLE
Wrong console.log....

### ISSUE THREAD

**Issue by Kr3m** [jonthornton/jquery-timepicker#505]
```
var date = new Date();
selTime = $('#time').timepicker('getTime', date);
console.log(selTime);
```

No matter what I do, the console is logging the correct UTC time, but the day before it is supposed to.

**Comment by Kr3m** [comment]
I'm actually passing selDate to the Date constructor prior by passing a date selected from a datepicker.

**Comment by jonthornton** [comment]
I can't reproduce this one. Please post a jsFiddle that demonstrates the problem and let me know which timezone you're in.
