### ISSUE TITLE
How to get the visible status?

### ISSUE THREAD

**Issue by P4trik** [jonthornton/jquery-timepicker#507]
How can I get the visible status of the timepicker element? Is there anywhere a method or property?

Best regards

**Comment by henriklundahl** [comment]
Perhaps like this?

    $(".ui-timepicker-wrapper:visible").length

1 means visible and 0 not visible.

**Comment by P4trik** [comment]
It's always 1... :-( Have you already tried it?

**Comment by jonthornton** [comment]
@P4trik can you give me an example of how you'd like to use this?

**Comment by henriklundahl** [comment]
@P4trik: Yes, I tried it and it worked fine for me. The issue might be that at the time when you do the check the picker has just become visible or is just to become invisible.

Another way would be to keep track of the `showTimePicker` and `hideTimepicker` events. Also here you need to look out for timing (no pun intended) issues.

@jonthornton: I would also like this as a property or method. In my case I'd like to listen for the escape key, but only when the picker isn't visible.

**Comment by jonthornton** [comment]
@henriklundahl I can add `$('#someInput').timepicker('isVisible')`, but it only checks if the timepicker for **a specific input** is visible. I'm not sure this is useful. Does it fit your use case?

For maintaining state for **all** timepickers on a page, I'd use events.
```javascript
var visible = false;
$(document).on('showTimepicker', function(){
    visible = true;
}).on('hideTimepicker', function(){
    visible = false;
});
```

**Comment by henriklundahl** [comment]
@jonthornton: Yes, I'm only interested in the state of specific timepickers. Since the keydown event is first caught by the timepicker code, the state would be correct when my keydown code is executed, right?

**Comment by P4trik** [comment]
I got a directive in angular that implements the time picker. 
There can be more then one time picker on a page. That's my implementation:

`module.directive('openTimePicker', function ($timeout) {
    return {
        restrict: 'A',
        link: function (scope, element, attrs) {

            element.on('click', function (e) {
                if ($('#' + attrs.openTimePicker + ":visible").length === 0) {
                    $('#' + attrs.openTimePicker).timepicker('show');
                } else {
                    $('#' + attrs.openTimePicker).timepicker('hide');
                }
            });
        },
    };
});`

attrs.openTimePicker is the unique id of the timepicker. The way that @henriklundahl suggestet does'nt work because length always returns 1.

If I try to handle the status with the suggested event handler, I came into that error (whyever) that the click event isn't no longer triggered.

**Comment by P4trik** [comment]
@henriklundahl 
Your suggested feature is exact that what I need.

**Comment by jonthornton** [comment]
Great! I'll work on getting this feature shipped this weekend. Thanks for
the feedback everyone.

**Comment by P4trik** [comment]
Thank's for your commitment! 
If I ask for "isVisible" by the browser with the developer-tools, it works great.
But if get the the Value in my "click" handler, the method always returns visible = false.
I think it's due to the fact that everytime I click on the Button, the event of the time-picker "fade-out" runs first and sets visibility to false. Then if I ask for visibility state in my click-event, its always "false"

**Comment by jonthornton** [comment]
Timepicker uses the `click` event to show/hide itself. Your click handler is probably being run before timepicker's click handler.

Event handlers are called in the order they're bound. Make sure you're initializing your timepicker before binding your click handler, and it _should_ fix the problem.
