### ISSUE TITLE
For 24 hour time format, when I add the option 'show2400' : true, It is not affecting on time format, Am I doing wrong?

### ISSUE THREAD

**Issue by mrnerbijay** [jonthornton/jquery-timepicker#508]

**Comment by henriklundahl** [comment]
You need to use a `timeFormat` that supports 24 hours, like e.g. `G:i`. Do you? In case you do, what other configuration do you use?

**Comment by mrnerbijay** [comment]
I want to remove AM PM format and show time in 24 hour format in dropdown as earlier.

**Comment by jonthornton** [comment]
@mrnerbijay you need to set the `timeFormat` option.

```javascript
$('#someInput').timepicker({
    timeFormat: 'G:i',
    show2400: true
});
```

**Comment by mrnerbijay** [comment]
thanks @jonthornton, I got it now :)
