### ISSUE TITLE
am/pm vs 24 hour question...

### ISSUE THREAD

**Issue by MYeager1967** [jonthornton/jquery-timepicker#509]
This isn't really an issue and may already be possible but I'd like to know if it's possible for the dropdown picker to show 1:30pm but pass the 24hr 13:30 to the backend? I'm coding a series of timers into a webpage and am/pm is easier for the end user, but 24hr time is much better for the timer code.

**Comment by jonthornton** [comment]
No, jquery-timepicker doesn't have built in functionality for that. I recommend using moment.js to convert am/pm to 24 hour.
