### ISSUE TITLE
Adding Multiple Instances of Picker

### ISSUE THREAD

**Issue by ferguson4848** [jonthornton/jquery-timepicker#516]
There might be a way to accomplish this, but I can't figure it out. I'd like to add several of the same Timepickers to a single php page. I realize I could do this by inserting the script over and over with different names, but the issue is the number of needed Timepickers can vary every time the page is loaded so I would prefer a more dynamic way to accomplish this.

**Comment by jonthornton** [comment]
That should be pretty easy to do without loading the script more than once. Consult the jquery documentation. Unfortunately it's beyond the scope of what I can help with.
