### ISSUE TITLE
IE issue

### ISSUE THREAD

**Issue by chiragshah-mb** [jonthornton/jquery-timepicker#519]
The picker does not show proper timezone value. It shows GMT values, but I want it to show GMT+5.30 value.

**Comment by jonthornton** [comment]
Which version of IE, and what is the timezone of the host OS?

**Comment by chiragshah-mb** [comment]
I'm using IE version 10 on windows 10. Timezone of the host OS is UTC.

**Comment by jonthornton** [comment]
Timepicker will always use the host timezone. If you want GMT+5.30, the host OS has to be using that timezone as well.
