### ISSUE TITLE
Mobile Issue

### ISSUE THREAD

**Issue by chiragshah-mb** [jonthornton/jquery-timepicker#520]
The dropdown disappears as soon as the time is selected

**Comment by jonthornton** [comment]
Which browser and OS version do you see this in?

**Comment by chiragshah-mb** [comment]
Google Chrome in Android 6. The dropdown disappears as soon the dropdown is touched

**Comment by KrunchMuffin** [comment]
just had a complaint about same issue. chrome and safari on ipad/iphone.

**Comment by KrunchMuffin** [comment]
Just saw this https://github.com/jonthornton/jquery-timepicker/issues/486
Any ETA?

**Comment by KrunchMuffin** [comment]
100 thank yous!
