### ISSUE TITLE
Clearify popup positioning options

### ISSUE THREAD

**Issue by rayzru** [jonthornton/jquery-timepicker#521]
Hardly trying to place popup inside container that not related to input. 
I'd prefer that position options `appendTo` and `orientation` was related to eachother. 

So what is the logic now: Append to some container, but i'ts position still relates to input. 

Isn't better option place followed to `appendTo` element with specified `orientation` in same container?

Sorry for my bad english.

**Comment by jonthornton** [comment]
Attach the timepicker to your container and use a `changeTime` event handler to update the input. 

```
<div id="someDiv"></div>
<input id="someInput" />
...
$('#someDiv').timepicker().on('changeTime', function(){
    var time = $('#someDiv').timepicker('getTime');
    var formattedTime = yourFormattingFunction(time);  // time will be a javascript Date object
    $('#someInput').val(formattedTime);
});
```
