### ISSUE TITLE
Pressing [Enter] at edit control forces the entered time to round

### ISSUE THREAD

**Issue by c-f** [jonthornton/jquery-timepicker#522]
I create the timepicker with {forceRoundTime: false}.

When I click to the edit control, I can enter any time I want (e.g. 11:28 am), which is good. If the edit control looses the focus, the entered time remains as is, which is also good.

But If I press the Enter key in the edit field (which is quite natural), the dropdown list disappears (good) and the time is rounded to the nearest dropdown list value (not good!).

What I would expect: Pressing Enter in the edit field should cause the dropdown list disappear and the entered value should be rounded or left as is depending on the forceRoundTime option.

The behaviour observed in FireFox and Chrome.

**Comment by jonthornton** [comment]
Pressing enter selects the highlighted time in the dropdown. By default, typing a time highlights the nearest time option in the dropdown. You can disable this by setting `typeaheadHighlight: false`. 

Changing this behavior would conflict with keyboard navigation for the dropdown.
