### ISSUE TITLE
`scrollDefault` is seemingly off by one

### ISSUE THREAD

**Issue by nwhittaker** [jonthornton/jquery-timepicker#524]
Not sure if this is by design, but I'm finding the time associated with the `scrollDefault` option is the second visible item in the drop-down list. Whereas, I'd expect it to be the first.

Please see, http://jsfiddle.net/2moky47k/1/

1. In the fiddle, note that `scrollDefault` is set to "1am".
2. Click the time picker field.

**Observed:** The first time in the list is "12:30am".
**Expected:** The first time in the list is "1am".

Probably has something to do with the decision behind subtracting the `outerHeight()` on [line 169](https://github.com/jonthornton/jquery-timepicker/blob/1.10.0/jquery.timepicker.js#L169).

```javascript
var topOffset = list.scrollTop() + selected.position().top - selected.outerHeight();
list.scrollTop(topOffset);
```

FWIW, this ends up with a negative `topOffset` if `scrollDefault` is set to 12am (admittedly an unlikely scenario).

**Comment by jonthornton** [comment]
Yep, that's by design.
