### ISSUE TITLE
timepicker works great on a desktop browser but having problems on a iphone

### ISSUE THREAD

**Issue by rss81** [jonthornton/jquery-timepicker#526]
having the following 2 problems when using timepicker on a iphone:

1) keyboard pops up the first time the input box is touched even with 'disableTouchKeyboard': 'true',

2) it's really difficult to scroll the timepicker. if you're at the end of the dropdown how do you get back to the start of the time picker?  As soon as your finger is lifted the dropdown disappears. There's no scrollbar on the right side

I've added a js fiddle [iphone example](https://jsfiddle.net/rss81/v5nc7npn/5/) butt really looks like this timepicker doesn't work well on mobile devices. Also, the stopScrollPropagation doesn't seem to be working.  The UI on a iphone just makes this really hard to use.  Are there other work arounds for making it easier to roll down the list and select a value?  Shouldn't we be able to select the time on one try with one finger?

**Comment by jonthornton** [comment]
There's a bug in the jsFiddle here. You're binding timepicker to the input in an `onclick` handler. That causes timepicker not to work on the first click, and causes multiple bindings on subsequent clicks, which will cause unpredictable behavior. Instead just bind it once on DOMready.

```javascript
$(document).ready(function() {
    $('.timedrop').timepicker({
      'minTime': '9:00 am',
      'maxTime': '9:00 pm',
      'timeFormat': 'h:i A',
      'disableTextInput': true,
      'disableTouchKeyboard':true,
      'stopScrollPropagation':true
    });
});```

**Comment by rss81** [comment]
Thanks Jon for the feedback. I tried your suggestion but on a iPhone I can't get your timepicker to provide a user friendly experience. It's just too difficult to select a time. I've gone with Willington Vega's timepicker instead as it provides a better user experience. 

Bob
