### ISSUE TITLE
show2400 doesent work?

### ISSUE THREAD

**Issue by abdelouahabb** [jonthornton/jquery-timepicker#527]
Hi, from the latest release, saw that this was fixed, but still nothing here

`
function tam(){
  $('#tm').timepicker({
    'minTime': '8:00',
    'maxTime': '17:00',
    'show2400': true
  })
}
`
the range works, but showing only using `am/pm`

**Comment by jonthornton** [comment]
You need to specify a 24-hour timeFormat.

```javascript
$('#tm').timepicker({ 
  'minTime': '8:00', 
  'maxTime': '17:00', 
  'show2400': true,
  'timeFormat': 'G:i'
});
```

**Comment by abdelouahabb** [comment]
ah thank you ^_^
