### ISSUE TITLE
mobile touch events do NOT work well

### ISSUE THREAD

**Issue by rss81** [jonthornton/jquery-timepicker#528]
This timepicker is great on a desktop or laptop but on a iphone it 's too difficult for the user to select a time.  The roll down times vanish as soon as you lift your finger so it's not possible to scroll from the top to the bottom of the list and then select a time.  Here's a fiddle [jsfiddle](https://jsfiddle.net/v5nc7npn/8/url)  but access it with a iphone and see how it behaves

**Comment by jonthornton** [comment]
The 1.11 version fixes some mobile bugs - give that a try.

**Comment by jmzbond** [comment]
Jon, I see that the Fiddle starting point (http://jsfiddle.net/jonthornton/28uvg/) uses 1.11.1, and it does fix the issue described here, which I'm having as well. Do you have that on a CDN? If not yet no worries, just wanted to check. Thanks!

**Comment by jonthornton** [comment]
Hmm, it seems like cdnjs hasn't picked up the latest version. That's all managed automagically by npm - unfortunately I can't fix it myself. Hopefully it'll update next time there's a release.
