### ISSUE TITLE
How to setTime in default input view

### ISSUE THREAD

**Issue by YeZhiqiuSev** [jonthornton/jquery-timepicker#535]
I find that set current time must handle by the click function. In another word, I trigger the 'setTime'  by 'click' or other functions. Is there any way to set current time without any function.The default view of time selection is just now time?

**Comment by YeZhiqiuSev** [comment]
for example :I put this code `$(this.refs.timePicker).timepicker('setTime',new Date());`  in React componentDidMount that will excute after html render ,but the 'setTime' doesn't work.

**Comment by jonthornton** [comment]
I haven't tested jquery-timepicker with React. You should try a different timepicker.

**Comment by dostiemat** [comment]
You can set it in your HTML
`<input id="clock_on_text" type="text" value="09:00"/>`

And in your JS (nothing to do)
`$("#clock_on_text").timepicker();`

The time picker will even set the dropdown at the right position for you.
