### ISSUE TITLE
Usage with Django

### ISSUE THREAD

**Issue by tmcintire** [jonthornton/jquery-timepicker#536]
I recommend adding a space between the time and the "am/pm" so it not run together like 8:00pm.  Not sure if if needs to be this way for other languages, but for Django at least, it won't take it unless its formatted "8:00 pm" with a space.  I fixed my code accordingly, just thought I'd bring it up. Awesome plugin!

**Comment by jonthornton** [comment]
Thanks for the kind words! The default timeformat is arbitrary - definitely a good idea to set the `timeFormat` option to ensure compatibility with your backend.
