### ISSUE TITLE
Doesn't work for input with readonly attribute

### ISSUE THREAD

**Issue by alexeyfadeev** [jonthornton/jquery-timepicker#537]
I want to deny keyboard text editing, to allow only selection from dropdown time list.
When I add a readonly attribute, timepicker doesn't woks.

Also I tried to replace input with label. But in this case label text isn't changed on time selection. And I don't understand how get time value in 'changeTime' callback function - $(this).val() doesn't work with label.

**Comment by jonthornton** [comment]
Use the `disableTextInput` option. [More info here.](https://github.com/jonthornton/jquery-timepicker/issues/425#issuecomment-133262458)
