### ISSUE TITLE
getSecondFromMidnight didnt work well..

### ISSUE THREAD

**Issue by iqbalpetet** [jonthornton/jquery-timepicker#539]
recently i've made my new form for my website. with timepicker so here's the code.

` 
					  $('#basicExample .time').timepicker({
						  'showDuration': true,
						  'timeFormat': 'g:ia'
					  });

					  $('#basicExample .date').datepicker({
						  'format': 'd/m/yyyy',
						  'autoclose': true
					  });

					  $('input.times').timepicker();
			  $('#basicExample .time').on('changeTime', function() {

				
				 var seconds = $('#time2').timepicker('getSecondsFromMidnight') - $('#time1').timepicker('getSecondsFromMidnight');
							 
							  // compensate for negative values;/
				  				if (seconds < 0) {
								 seconds += 86400;
							}
				  document.getElementById('lama').value = second/360;
					  });

					  // initialize datepair
					  var basicExampleEl = document.getElementById('basicExample');
					  var datepair = new Datepair(basicExampleEl);

				  </script>`

but it wont calculate the time, and also makes my datepair didn't works.
all i want to do is to get the variable of time duration that i've been set so i can put it on my database as a float variable. thank you.

**Comment by jonthornton** [comment]
Can you post a jsFiddle or some other live example of the problem?

**Comment by iqbalpetet** [comment]
hello, sorry for late replied, idk how to use jsFiddle but now i can calculate the time with my own logarithm like this.
` $('#basicExample .time').on('changeTime', function() {


				  var awal = document.getElementById('wktAwal').value.split(':');
				  var awalH = parseFloat(awal[0]);
				  var awalM = parseFloat(awal[1]);
				  var awalS = (awalH*3600)+(awalM*60);

				  var akhir = document.getElementById('wktAkhir').value.split(':');
				  var akhirH = parseFloat(akhir[0]);
				  var akhirM = parseFloat(akhir[1]);
				  var akhirS = (akhirH*3600)+(akhirM*60);

				  if(akhirS < awalS) {
					  akhirS += 86400;
				  }

				  var selisih = (akhirS - awalS)/3600;
				 // var seconds = $('#time2 .times').timepicker('getSecondsFromMidnight') - $('#time1 .times').timepicker('getSecondsFromMidnight');
							 // var seconds = (+a[0]) * 60 * 60 + (+a[1]);
							  // compensate for negative values;/
				  				//if (seconds < 0) {
							//	 seconds += 86400;
							//  }
//
				  document.getElementById('lama').value = selisih;
					  });




					  // initialize datepair
					  var basicExampleEl = document.getElementById('basicExample');
					  var datepair = new Datepair(basicExampleEl);



				  </script>`
thank youu
