### ISSUE TITLE
Do not force round time?

### ISSUE THREAD

**Issue by arlinsandbulte** [jonthornton/jquery-timepicker#540]
I have only played with the demo of jquery-timepicker at http://jonthornton.github.io/jquery-timepicker/

There, it demonstrates an option to forceRoundTime so that even when the user manually types in a time value, it gets rounded to the available times in the dropdown list.
HOWEVER, this seems to be default behavior in all of the other examples too.  Can this be disabled so the user can 'fine tune' the time manually?
For example, a user might type in 12:03pm

**Comment by jonthornton** [comment]
Yes, set the `forceRoundTime` option to `false`. https://github.com/jonthornton/jquery-timepicker#options
