### ISSUE TITLE
How to get value of selected option

### ISSUE THREAD

**Issue by shivam5x** [jonthornton/jquery-timepicker#541]
Hi,
  I have two case 
 1. I have bounded with span and div so how can i get selected time and in mobile when i select it should hide keypad.
 2. Same for input tag.

Thanks
Shivam

**Comment by jonthornton** [comment]
I'm sorry, I don't understand the question. Could you provide an example?

**Comment by dhara15101991** [comment]
@jonthornton i have same issue. i have binded timepicker to span. now when i select time from dropdown i want that selected time on select.

currently i don't know how to get selected time on selection of timeslot. Please see below code

`<span id="timepicker"></span>`
```
`$('#timepicker').timepicker();
 $('#timepicker).on('selectTime', function() {
                        alert("hi there"); // i want selected time here. suppose i have selected 12:00AM then i want this value here
 });`
```

**Comment by jonthornton** [comment]
```javascript
$('#timepicker').timepicker();
$('#timepicker).on('selectTime', function() {
  var time = $('#timepicker').timepicker('getTime'); // this will be a Date object that includes the time
 });
```
