### ISSUE TITLE
set min time

### ISSUE THREAD

**Issue by renjithp** [jonthornton/jquery-timepicker#542]
I have two time fields from time & to time. when a person selects the from time. i would like to set mintime option of to field to the selected time. 

i tried the code 

$('#DurFrom').timepicker();
$('#DurFrom').on('changeTime', function(){
$('#DurTo').timepicker("option", "minTime", $(this).val());
});

i would like to get time difference between DurFrom & DurTo to print in another field. how to do that also?
please guide me at the earliest. 

Thanks in advance.

**Comment by jonthornton** [comment]
[Datepair.js](https://github.com/jonthornton/Datepair.js) does exactly this!

**Comment by akashk92** [comment]
How do i do it exactly using datepair.js them???
my code:
`
  $('.timePicker').timepicker({'timeFormat': 'h:i A'});
  $('.timePair').datepair();
  $('.end-time').on('changeTime', function () {
    var minEndTime = $(this).val();
    console.log($(this).val());
   /* $(this).timepicker({
      'timeFormat': 'h:i A',
      'minTime': '05:30 AM',
      'showDuration': true
    });*/
    $('.timePicker').timepicker('option', { 'minTime': '02:00pm', 'timeFormat': 'h:i A' });
  });`
