### ISSUE TITLE
Pulling the final time value

### ISSUE THREAD

**Issue by Debuckne95** [jonthornton/jquery-timepicker#543]
I am implementing the time picker as a pop up page in order to reserve rooms, I am trying to use the users' input in a service file that pulls their time choice and displays it on another page. I am having a hard time doing so mainly because i don't know what to target in the picker files in order to grab the final times. Any suggestions would help immensely!

**Comment by jonthornton** [comment]
```javascript
$('#someTimeInput').timepicker().on('changeTime', function(e) {
  var timeValue = $(this).val();
});
```

**Comment by Debuckne95** [comment]
Thank you !
