### ISSUE TITLE
Mobile - prevent keyboard from popping up

### ISSUE THREAD

**Issue by jmzbond** [jonthornton/jquery-timepicker#544]
When keyboard pops up as the timepicker field gains focus, this is really bad UX because the keyboard occludes the select menu entirely. On datepicker, the standard answer (http://stackoverflow.com/questions/6911895/disable-setting-of-focus-for-jquery-ui-datepicker) is to set the field to readonly, but I realize that semantically, it is purposefully designed that in timepicker a readonly field cannot be amended. 

The provided workaround is to set `disableTextInput: true`. However, when one does this, the keyboard on mobile devices is still triggered.

Anyway to provide a better mobile experience?

**Comment by jonthornton** [comment]
Have you tried `disableTouchKeyboard`?

**Comment by jmzbond** [comment]
AH I feel silly AF, sorry yup that did the trick

James

---


Rent camping gear & snowsports apparel;
<https://www.lastmingear.com?utm_source=email&utm_medium=signature&utm_campaign=jdong8>
up to 1 hour before your trip!

**Comment by jonthornton** [comment]
No worries - good luck with your project!
