### ISSUE TITLE
How to disable a single time

### ISSUE THREAD

**Issue by pravin-d** [jonthornton/jquery-timepicker#546]
I'm using this plugin with 2 inputs to display a start and end time. I want to disable the time that is selected as start time in the endtime input.
The times have a step : 15
For eg : StartTIme : 3:00 AM, then endTime : 3:00 AM must be disabled. 
I'm able to do it if do use start Range : 3:00 AM and end Range : 3:01 AM. However for this I need to convert the time string to time, increment it by 1 and back to string. Is there a simpler way ?

**Comment by jonthornton** [comment]
You can get a DateTime from timepicker with `$('#someInput').timepicker('getTime')` and you can set `minTime` with a DateTime object, so no need to do string conversion on either end.

A simpler alternative may be to use [Datepair.js](https://github.com/jonthornton/Datepair.js) and show an error to users if `getTimeDiff() == 0`.
