### ISSUE TITLE
Nuget file versioning

### ISSUE THREAD

**Issue by mwpowellhtx** [jonthornton/jquery-timepicker#549]
Hello,

First, thanks for the time picker. I will be interested to use this in some of my projects.

The only comment I might have is to see the nuget-packaged files "versioned" when they are included, if possible. That will help differentiate them if any issues are encountered and during upgrade processes. i.e.

```
jquery.timepicker.1.11.2.js
```

While I'm here, the latest nuget is 1.9.0; will there be a new nuget pushed soon?

Otherwise, thanks, and keep on keeping on.

Regards,

Michael Powell

**Comment by jonthornton** [comment]
I'm hesitant to change the naming scheme because there may be people who have build processes that depend on unversioned filenames. This is a good idea however and I'll keep it in mind for the next breaking version change.

Are there any OS X tools for publishing to nuget? I'd be happy to publish an update but it's not easy from a Mac.

**Comment by mwpowellhtx** [comment]
Re: naming conventions, it's not a big deal, but thanks... I don't know about Mac, per se. Isn't it easy enough to include a Nuspec file?

**Comment by mwpowellhtx** [comment]
FYI, one note, I cannot speak for non-ASP.NET MVC usages, but I can bundle the config like this:

```C#
yield return new ScriptBundle("~/bundles/jquerytimepicker")
    .Include("~/Scripts/jquery.timepicker.{version}.js");
```

And not care about changes in version from one release to the next.

I'm sure there's probably a way to format the ``{version}`` in such a way as to anticipate a version naming convention in a future release.

**Comment by jonthornton** [comment]
I'm not familiar with the Nuspec format. If you'd like to make one and send a pull request I'd be happy to give it a look.

**Comment by mwpowellhtx** [comment]
I'm surprised by that. Would you mind clarifying, you are the [jonthornton](http://www.nuget.org/profiles/jonthornton) on the [Nuget project](http://www.nuget.org/packages/jquery-timepicker-jt/)?

**Comment by jonthornton** [comment]
That's me. A user name `bogatykh` had been assisting me with updates but it seems like they're no longer active.

**Comment by mwpowellhtx** [comment]
I can't promise when I will get to it, but if you'll set me up on NuGet, I'll look into submitting some PRs against the Github repo, and publish updates to NuGet.
