### ISSUE TITLE
Problem with z-index

### ISSUE THREAD

**Issue by joannadal** [jonthornton/jquery-timepicker#550]
I am having a problem trying to display the timepicker into a table. It seems the problem is with the z-index property.

Please, see the screenshot.

![issue_timepicker](https://cloud.githubusercontent.com/assets/3443169/17777059/5a1e3348-655f-11e6-8117-1fcd9ef2d8ec.png)

**Comment by jonthornton** [comment]
You can configure the z-index by overriding rules in `jquery.timepicker.css`.
