### ISSUE TITLE
Option "minDate" modifying the current choices to select

### ISSUE THREAD

**Issue by amrt0510** [jonthornton/jquery-timepicker#553]
I my case I have set up a timepicker with option to show it like

12:00 am
01:00 am
02:00 am
.
.
. 
....and so on. 

But when i pass minTime to "minTime":"13:39"

It converted to something like
01:39 pm
02:39 pm
03:39 pm
04:39 pm
05:39 pm
.
.
.

Please fix it.

**Comment by jonthornton** [comment]
That's expected behavior. `minTime` set the first available option in the dropdown. All subsequent dropdown options are `step` minutes past the preceding option.

**Comment by amrt0510** [comment]
Okay I get it. 
In my case I don't want to let user select the time which is less than the current time. 

So if default dropdown is  

12:00 am
01:00 am
02:00 am
.
.
. 
....and so on.

And current time is 2:15am then what I want is - 

12:00 am (Disabled/unavailable)
01:00 am (Disabled/unavailable)
02:00 am (Disabled/unavailable)
03:00 am
04:00 am

.
. 
....and so on.

Please guide how it can be achieved.

**Comment by jonthornton** [comment]
The `disableTimeRanges` option is your best bet. Something like this should meet your needs:

```javascript
$('#someInput').timepicker({
    'disableTimeRanges': [['12:00am', '2:15am']]
}).on('timeRangError', function() {
    // show error message to user
});
```

The timeRangeError handler will catch cases where the user manually typed a time into the input.

**Comment by amrt0510** [comment]
Thanks! That will work.
