### ISSUE TITLE
Dropdown width not matching input field

### ISSUE THREAD

**Issue by tylerwilson** [jonthornton/jquery-timepicker#555]
I am new to this component, so forgive me if this is a trivial question. I have an input field, which I then call timepicker() on. The dropdown that results does not match the width of the input. I would expect it to do this by default (I am using the default .CSS file).

I have also tried useSelect, and that works great, but I have another method I am using on all selects to style them the same (semanticSelect) and that causes the time to get reset to the first in the list.

I have used other plugins, and they often have a beforeShow option which allows me to dynamically size the dropdown based on the current size of the input. Is this something you could add, if there is no easier solution?

Thank you.

**Comment by jonthornton** [comment]
Timepicker doesn't try to match the width of the input, but it shouldn't be hard to customize for your needs.

Your best bet would be to edit or override the default timepicker styling to match your input widths. using the [markup documentation](https://github.com/jonthornton/jquery-timepicker#theming). Use the `className` option if you need different styling for different widths.
