### ISSUE TITLE
Issue in setting value when useSelect is On

### ISSUE THREAD

**Issue by amrt0510** [jonthornton/jquery-timepicker#556]
HI,

When useSelect mode is on, and i have a step size of let's say 30 minutes.
My dropdown looks like

==Select Time ==
00:00
00:30
01:00
01:30
...

In that scenario when i set time "00:25" it turned into blank select

Like this http://screencloud.net/v/c68

Could you be able to fix or provide me a workaround for it.

**Comment by jonthornton** [comment]
I wasn't able to reproduce this. Could you provide a working demo?

**Comment by amrt0510** [comment]
It was my mistake. Everything works fine! Apologies!
