### ISSUE TITLE
Choosing AM instead of PM

### ISSUE THREAD

**Issue by rselk** [jonthornton/jquery-timepicker#557]
Hello,

I am trying to do the following:

- Using 12 hour clock
- If a user begins to fill out the timepicker with the number 1-5, it auto suggests 1-5 PM
- If a user begins to fill out the timepicker with the number 6-12 it auto suggests 6-12 AM

Is this possible to do via configuration?

**Comment by jonthornton** [comment]
No, unfortunately the auto suggestion isn't configurable. It's such a "window dressing" feature that I didn't want to bloat the codebase by making it more complicated than it already is.
