### ISSUE TITLE
selectOnBlur implies forceRoundTime

### ISSUE THREAD

**Issue by damangio** [jonthornton/jquery-timepicker#558]
When the selectOnBlur option is true, it overrides what is in the input field, even if it's a custom time typed by the user. So effectively, selectOnBlur implies forceRoundTime, because it's impossible to enter a time not in the list. Unless I'm just missing something. Is there currently a way to do selectOnBlur and still be able to manually enter arbitrary times?

Thanks.

**Comment by jonthornton** [comment]
Yup! Set `typeaheadHighlight: false`.

**Comment by damangio** [comment]
Thanks!
