### ISSUE TITLE
integrating datepicker with timepicker

### ISSUE THREAD

**Issue by kumel619** [jonthornton/jquery-timepicker#559]
I have a form where user selects date from datepicker & then there is a timepicker after it.

Timepicker are in dropdown. I have this part ready.

Here is an example:
If today’s date is : 21-sep-2016
& Current time is : 09:00.
So when today’s date is choosen then i want timepicker to display hours after 4 hours. ie. 13:00 to 24:00
If date choosen was any other date then all time must be shown

So how can this be achieved?

This is my datepicker input code:

	<input type="text" id="StartDate" class="form-control" style="cursor:pointer; background:white;"  placeholder="Start Date" name="StartDate"  title="StartDate" readonly required/>

**Comment by jonthornton** [comment]
Use the option method.
`$('#someInput').timepicker('option', { minTime/maxTime options });`

**Comment by kumel619** [comment]
If today’s date is : 21-sep-2016
& Current time is : 09:00.
So when today’s date is choosen then i want timepicker to display hours after 4 hours. ie. 13:00 to 24:00
If date choosen was any other date then all time must be shown

**Comment by kumel619** [comment]
i m using datepicker from bootstrap-datepicker.min.js
