### ISSUE TITLE
Unable edit timepicker input in Chrome for old versions of JQuery

### ISSUE THREAD

**Issue by viy** [jonthornton/jquery-timepicker#560]
Hi everyone
For some reason I unable to edit input field for Chrome 53 and JQuery 1.11.3. See fiddle 
https://jsfiddle.net/viy123/b2yj0L83/6/
This bug also reproduced only on windows 10.

**Comment by raknjak** [comment]
I'm unable to reproduce this on Chrome 53 + windows 10; I can manually edit the input field with any date if that is what you mean.
