### ISSUE TITLE
Custom time while keypress enter

### ISSUE THREAD

**Issue by RexhepiEdon** [jonthornton/jquery-timepicker#561]
Hello, 

I appreciate the work, it really works smooth and no bugs till now, really.

I would like to put custom times, for example i have the step to 30, so it comes like 9:00, 9:30, etc.
When i write 9:20 and press enter, the value 9:30 comes in.

Would i be able to change that?

Thank you guys!

**Comment by jonthornton** [comment]
Pressing enter selects the highlighted option in the dropdown; by default it will highlight the nearest option as you type. Set 'typeaheadHighlight: false` to disable this.
