### ISSUE TITLE
showDuration Will not remove itself when the two dates don't match

### ISSUE THREAD

**Issue by 10featj** [jonthornton/jquery-timepicker#563]
I have a Create Event form for a calendar like any it has two dates and two times each using jquery pickers. The time picker is this one. If the two dates match i want the showDuration set to true if not matching set to false. 

                /* Duration function - Add the minutes of how long the event will be to the select options  */
                function dateCompare() {
                  if ( $('#id_end_0').val() === $('#id_start_0').val()){
                     /* Dates Match, Allow */
                    alert("They are the same!");
                    $('#id_end_1').timepicker({
                      'timeFormat': 'H:i',
                      'minTime': $('#id_start_1').val(),
                      'maxTime': '23:30',
                      'showDuration': true
                    });
                  }else{
                    /* Date do not match, Dont Allow Duration */
                    alert("They are not the same!");
                    $('#id_end_1').timepicker({
                       'timeFormat': 'H:i',
                       'showDuration': false,
                     });
                  }
                };
                /*Run function when ready and when clicked.*/
                setTimes();
                $('#get_time').click(setTimes);
                dateCompare();
                $('#id_end_0').change(dateCompare);
                $('#id_start_0').change(dateCompare);
              });

Why wont it just remove it, iv been trying to figure this out for a good 4/5 hours now and its killed me.

Please help.

**Comment by jonthornton** [comment]
`dateCompare()` is re-initializing the timepicker each time it's called. Try initializing timepicker only once, and then use `timepicker('option', {...});` in `dateCompare()`.
