### ISSUE TITLE
How can I defined event in options object in controller?

### ISSUE THREAD

**Issue by saritsegal** [jonthornton/jquery-timepicker#564]

**Comment by saritsegal** [comment]
I tried set the option object in my controller as follow:
myoptions = {
 step: 30,
 timeFormat: 'G:i',
 show2400: true,
}
I want to add the "onSelect" event to this object. I tried as "selectTime': (timeText) => {
                    this.mymethod(timeText);
                },
it does not work. Do you know the accurate syntax?

**Comment by henriklundahl** [comment]
I believe you can't add an event handler to the options object. Instead add it like this:

`myTimePicker.on('selectTime', () => {...});`

**Comment by jonthornton** [comment]
Thanks @henriklundahl !

**Comment by saritsegal** [comment]
Finally, I’ve used the ng-change angular directive in HTML. I think this is more “nice” way.

TNX for answering
Sarit
