### ISSUE TITLE
Data-attribute are override by jsobject at init

### ISSUE THREAD

**Issue by stefdelec** [jonthornton/jquery-timepicker#566]
Hi

(thanks for your plugin).

It may be a misunderstanding on my side or request for later. In myproject, I have default option for our timepicker. But sometime, it needs to be override. Usually in jquery plugin, data-attributes override default option. In your plugin, if there is default option, data-attribute settings are not taken into account.

example:
```

`<input class="custom-timepicker" data-min-time="8:00">
<script>
$(document).ready(function(){
var defaultoption={
  show2400: true,
        timeFormat: 'H:i',
        minTime:"7:00",
        maxTime: "20:00",
};
$(".custom-timepicker").timepicker(defaultoption);
}
<script>
`
```

Here, minTime will be 7 instead of 8.

**Comment by jonthornton** [comment]
Thanks for pointing that out!
