### ISSUE TITLE
Possible to Disable Time Ranges upon DatePicker update?

### ISSUE THREAD

**Issue by Soben** [jonthornton/jquery-timepicker#567]
Basically, as I swap out time ranges as the user selects a different day, I want to block out certain time frames based on some arbitrary setting set by our client (basically, if there are 3 orders for a time frame, disable the time from being selected)

I see disableTimeRanges, but can that work on the fly as the timepicker gets reset due to date selections?

About to experiment with this, but I figured a ticket would help :)

**Comment by jonthornton** [comment]
Sorry for the slow response here. You can definitely couple disableTimeRanges settings to a datepicker event. Check out Datepair.js for inspiration.
