### ISSUE TITLE
How to add space before time periods?

### ISSUE THREAD

**Issue by neutt22** [jonthornton/jquery-timepicker#568]
I'd like to have spacing like `10:30 pm` instead of `10:30pm`. Reason being Carbon library won't parse if the value is not in this format.

Thanks

**Comment by henriklundahl** [comment]
Perhaps related to #472. +1 for this.

**Comment by neutt22** [comment]
I solved the problem using this option `'timeFormat': 'H:i a'`. Thanks for the fast response!

**Comment by henriklundahl** [comment]
Ok, great. I thought I remembered that there was some problem with that. Either it's been fixed or I remembered wrongly.

**Comment by jonthornton** [comment]
If I remember correctly, #472 is about supporting less common formats like "am 7:32" or mm:ss (no hours) - those are currently really difficult to support.

Whitespace alone shouldn't break anything though!
