### ISSUE TITLE
Problem with dynamism

### ISSUE THREAD

**Issue by rocka13** [jonthornton/jquery-timepicker#569]
The values ​​it returns are resp = ['10: 00 ', '11: 00'] [ '15:00', '18: 00 '] [' 11:00 ', '12: 00'], To enter it to the code does not deactivate the hours.

  function SolicitarHora()
        {
            $('#fecha_servicio').change(function()
            {
            var valor = $('#fecha_servicio').val(); 
            var ruta = "/horas";

                $.get(ruta, function(resp)
                {

                   var rango = resp;
                    var tr = new Array();
                    var tr = [];
                    tr.push(rango);  
                    
                   console.log(resp);
                   $('#respuesta').html(rango);
                   $('.hora2').timepicker(
                   {   
                        'timeFormat': 'H:i',
                        'disableTimeRanges': [rango],
                        orientation: "r",
                        step: '60',
                    });
           

                });
            });

 }

**Comment by jonthornton** [comment]
`disableTimeRanges` needs a list of time pairs. 

In your example, `resp` is a string, which means you're passing in this: 
```javascript
["['10: 00 ', '11: 00'] [ '15:00', '18: 00 '] [' 11:00 ', '12: 00']"]
```
which is a string wrapped in an array.
