### ISSUE TITLE
Select date is not working in the inline mode on mobile

### ISSUE THREAD

**Issue by ukalpa** [jonthornton/jquery-timepicker#571]
Hi there,

When I was trying to select the date on the mobile, I encountered the issue that I could not select any date in the plugin, so, I assume it's a bug, I appreciate if you could have a look at when you are free. 

The script is:
`<div id="time_from"></div>`
`<script>`
`$('#time_from').datepicker({ inline:true, multidate: true })`
`</script>`

The environment is iPhone 6 and Chrome

![image](https://cloud.githubusercontent.com/assets/4927815/20868922/8b5595f6-bacc-11e6-9edb-2c70e7dbbb9d.png)

**Comment by jonthornton** [comment]
I think you might be looking for the [Bootstrap Datepicker](https://github.com/uxsolutions/bootstrap-datepicker) documentation.

**Comment by ukalpa** [comment]
Thank you for the reply, I will forward the issue to Bootstrap Datepicker
