### ISSUE TITLE
Including the maxTime after the last step

### ISSUE THREAD

**Issue by mfields3** [jonthornton/jquery-timepicker#574]
Consider the following:
```
minTime: '11:00',
maxTime: '14:10',
step: 30
```

Currently the last time shown is 14:00. I'd like the maxTime of 14:10 to show afterwards. How would I go about making this happen?

Thanks

**Comment by jonthornton** [comment]
You miiight be able to do that by specifying a custom function for `step`. It's gonna be complicated though. Unfortunately Timepicker wasn't designed to support that situation.

**Comment by mfields3** [comment]
Thanks, written a `step` function to do this. Unsure if this is desired behaviour, however the returned value for `i == 0` is ignored.

**Comment by jonthornton** [comment]
I'm not sure I understand the ignore value issue correctly. Can you post the step function?
