### ISSUE TITLE
timeRangeError not firing if maxTime set

### ISSUE THREAD

**Issue by mfields3** [jonthornton/jquery-timepicker#575]
The documentation says timeRangeError is "Called if a maxTime, minTime, or disableTimeRanges is set".

However in code, it's only called if _both maxTime & minTime_, or disableTimeRanges is set.

**Comment by mfields3** [comment]
Related to #531

**Comment by mfields3** [comment]
My suggested fix would be:
		if (settings.minTime !== null && seconds < settings.minTime) {
			rangeError = true;
		}

		if (settings.maxTime !== null && seconds > settings.maxTime) {
			rangeError = true;
		}

**Comment by jonthornton** [comment]
Apologies, the documentation is incorrect. What you're seeing is the desired behavior.

When minTime is set, 24 hours worth of options are still displayed in the dropdown - any value is valid. Both a minTime and maxTime need to be set.

**Comment by mfields3** [comment]
Thanks for confirming. How would you recommend setting minTime for the end of a time-only Datepair?

Tried setting minTime to $('#startTime').val(), however it appears to save this as a static value rather than check the new start time each time.

**Comment by jonthornton** [comment]
Can you post a jsFiddle or explain a bit more what you're trying to do? I don't understand.

**Comment by mfields3** [comment]
I have two Timepickers. One is #startTime, the other #endTime. 

I'm also using your Datepair library which works well. Now I'd expect rangeError to fire if someone types in an end time which is before the start time. However rangeError now won't fire unless the minTime has been set on #endTime. So what should it be set to since the minTime will vary based on the start time.

**Comment by jonthornton** [comment]
Have you tried setting a maxTime for both timepickers?
