### ISSUE TITLE
timeFormatError & timeRangeError not firing when updating time or settings programatically

### ISSUE THREAD

**Issue by mfields3** [jonthornton/jquery-timepicker#576]
I'm changing the maxTime programmatically (`$('#somePicker').timepicker('option', 'maxTime', '10:20');`) and was hoping to see the timeRangeError event thrown if it now clashes. One can hope!

The documentation says the events are fired when the time is updated, so I thought instead to set the time programmatically to kick off the validation. For example: `$('#somePicker').timepicker('setTime', $('#somePicker').val());`

However that doesn't work either.

**Comment by jonthornton** [comment]
Good catch - thanks for reporting the issue!

**Comment by ibnbay00** [comment]
Hi @jonthornton ,
I have 2 timepicker:
```
var pickup_time = $('#id_order_date-pickup_time');
var delivery_time = $('#id_order_date-delivery_time');
pickup_time.timepicker({
                'step': 60,
                'minTime': pickup_hours + ':00',
                'maxTime': '23:00',
                'useSelect': true,
                'timeFormat': 'H:i'
            });
delivery_time.timepicker({
                'step': 60,
                'minTime': delivery_hours + ':00',
                'maxTime': '23:00',
                'useSelect': true,
                'timeFormat': 'H:i'
            });
```
Then use on('change')
```
pickup_time.on('changeTime', function () {
                //alert('ganti nich :P');
                console.log(this.value);
                delivery_time.timepicker('option', 'minTime', '10:00');
                //delivery_time.timepicker({'minTime': this.value});
            });
```
Then another timepicker showup (result 3 timepicker :))
My expectation is one to update second timepicker after change first timepicker

Thanks

**Comment by jonthornton** [comment]
@ibnbay00 can you open a new ticket for this and post a jsFiddle that demonstrates the problem?

**Comment by ibnbay99** [comment]
Sorry, i'm using another script to build select using your plugin and bootstrap-select plugin.
Now to be simple, i just using your plugin.
Thanks...
