### ISSUE TITLE
Can I pass only name of my class as appendTo container?

### ISSUE THREAD

**Issue by rchzh** [jonthornton/jquery-timepicker#578]
I use your beautiful lib with knockout in my app. But I noticed that I can't pass just name of class to which I want `append` timepicker. I should do something like `'.' + containerName` to achive this. 

Am I doing something wrong or it is expected behaviour?

**Comment by jonthornton** [comment]
Yes, this is expected. Classnames need to be prefixed with `.` and IDs need to be prefixed with `#`.
