### ISSUE TITLE
Query on event handling

### ISSUE THREAD

**Issue by praveengrb** [jonthornton/jquery-timepicker#579]
I have two picker window. let us say start time widow (min time:9 am, max time is: 6 pm )and end time window  (min time:9 am, max time is: 6 pm ). if user selects start time as 10 am, then the end time window's min time should change as 10 am. How can i achieve this. 

$(document).ready(function() {			
			$('#thirdPartyStartTime').timepicker({
			    'minTime': '09:30:00',
			    'timeFormat': 'H:i:s',
			    'maxTime': '18:30:00'		  
			});
			$('#thirdPartyStartTime').on('changeTime', function() {
				var val=$(this).val();		
				$('#thirdPartyEndTime').timepicker({
				    'minTime': val,
				    'timeFormat': 'H:i:s',
				    'maxTime': '18:30:00'			    
				});
			});
			
			
});

**Comment by jonthornton** [comment]
Use the `option` method to change existing timepickers.

```javascript
$('#thirdPartyStartTime').on('changeTime', function() {
  var val=$(this).val();
  $('#thirdPartyEndTime').timepicker('option', {
    'minTime': val,
    'timeFormat': 'H:i:s',
    'maxTime': '18:30:00'
  });
});
```
