### ISSUE TITLE
Timepicker with Bootstrap Modal Dialog

### ISSUE THREAD

**Issue by kheinrich188** [jonthornton/jquery-timepicker#580]
When you want to use this very nice time picker with bootstrap modals you have to change following:<br>
In `jquery.timepicker.css`
search for `.ui-timepicker-wrapper {....}` 
and change `z-index:100001` to >= **`10052`**

**Comment by jonthornton** [comment]
Thanks!

**Comment by mio991** [comment]
could we make this the default value pls.

I hit the same problem.
