### ISSUE TITLE
Only first call it works

### ISSUE THREAD

**Issue by anandshri** [jonthornton/jquery-timepicker#581]
$('#booking_date').datepicker({ 
    minDate: 0,
    onSelect: function(dateText, inst) {
      var selectedDate = $(this).val();
      var today = new Date();
      today.setHours(0);today.setMinutes(0);today.setSeconds(0);
      if (Date.parse(today) == Date.parse(selectedDate)) {
          var time_range = getTimeRange();  //["1pm', "2pm"]
       } else {
          var time_range = []
       }
      setTimePicker(time_range);
    }
    
  });
 

function setTimePicker(time_range){
  console.log(time_range)
  $('#booking_time').timepicker({
    'minTime': '8:00am' ,
    'maxTime': '11:00pm' ,
    'showDuration': false,
    'disableTimeRanges': [time_range]
  });
}   

As you can see in above code I want change the disable  timings on time picker. if selected date is today disable the some timings and if not then enables all timings.

Its worked only first call then nothing change.

please let me know what is the issue. or you need more details.

Ancd

**Comment by jonthornton** [comment]
Use the `option` method. 

```javascript
$('#booking_time').timepicker('option', {
  'minTime': '8:00am' ,
  'maxTime': '11:00pm' ,
  'showDuration': false,
  'disableTimeRanges': [time_range]
});
```

**Comment by anandshri** [comment]
Thanks @jonthornton its worked. +1
