### ISSUE TITLE
Publishing to jsDelivr

### ISSUE THREAD

**Issue by ssorallen** [jonthornton/jquery-timepicker#583]
Any chance you could publish the latest release to jsDelivr? The last published release there is 1.3.7: https://www.jsdelivr.com/projects/jquery.timepicker

**Comment by jonthornton** [comment]
It looks like anyone can set this up https://github.com/jsdelivr/jsdelivr#auto-updating

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/

**Comment by archon810** [comment]
1.11.11 is missing from there. Also the whole 1.11 branch is missing from https://cdnjs.com/libraries/jquery-timepicker entirely. Can these not be kept up-to-date with github releases automatically or as a rule somehow?

**Comment by jimaek** [comment]
Is this what you are looking for? 
https://cdn.jsdelivr.net/gh/wvega/timepicker@1.1.1/
https://cdn.jsdelivr.net/gh/wvega/timepicker@1.1.1/jquery.timepicker.min.js

Like I said jsDelivr pulls automatically from npm and github. No need for auto-updates or anything like that

**Comment by archon810** [comment]
@jimaek Obviously not, considering the latest version is 1.11.11 (May 2017), not 1.1.1 (2010).

**Comment by jimaek** [comment]
Can you give me the repo of the file? This is were I was looking https://github.com/wvega/timepicker/releases

**Comment by archon810** [comment]
@jimaek Wat... you're literally commenting on the project. 

https://github.com/jonthornton/jquery-timepicker/releases/tag/1.11.11

**Comment by jimaek** [comment]
lol im tired. Sorry about that

http://cdn.jsdelivr.net/npm/timepicker/
http://cdn.jsdelivr.net/npm/timepicker@1.11.11/jquery.timepicker.min.js

Its all there.

**Comment by archon810** [comment]
Yeah, I raised https://github.com/jonthornton/jquery-timepicker/issues/633, and it's being made more clear there. They need to update the docs for sure.
