### ISSUE TITLE
Adding a custom time at the very end of the list

### ISSUE THREAD

**Issue by jericho1ne** [jonthornton/jquery-timepicker#584]
Howdy,

Any way to append a value at the tail end of the list a-la the "noneOption Example" listed on http://jonthornton.github.io/jquery-timepicker/?  For example, we need 1 hr increments, but we'd also like to have `11:59pm` as the very last selectable option.

- Mihai.

**Comment by jonthornton** [comment]
Hi Mihai, unfortunately custom options can only be added to the top of the list.

**Comment by jonthornton** [comment]
@dogandipcin I only needed the ability to add options to the top when I wrote the plugin - it's a pretty arbitrary decision unfortunately. I don't have much time anymore to add features and am only providing bug fixes at this point.
