### ISSUE TITLE
option to keep input but disable pulldown

### ISSUE THREAD

**Issue by neokio** [jonthornton/jquery-timepicker#586]
Sometimes it's preferable to allow a user to enter a time without distracting them with (or requiring) a scroll and mouse-click. I'd suggest this option could be an excellent enhancement to the plugin:

See [demonstration fiddle here](https://jsfiddle.net/designosis/j6fyhL17/).

```javascript
$('#time').timepicker({
	disablePulldown: true
});
```

A second, unrelated suggestion: Your parser does a great job of interpreting various inputs ... "1", "15","2p" get turned into valid times. When a user writes something unparsable, and then hits enter, I'd suggest clearing the input, rather than leaving their junk in the field.

**Comment by jonthornton** [comment]
Re: no drop down: That's an interesting idea. Have you tried implementing it with [moment.js](https://momentjs.com/) and a `change` handler?

Re: clearing the input: Use a `timeFormatError` handler to achieve this.

**Comment by neokio** [comment]
In the demo fiddle, I clear the input using `keyup` and moment.js ... not sure why I thought that was better than `change` :) I'll give `timeFormatError` a good look now, thank you!

**Comment by jonthornton** [comment]
Great, glad that was helpful!

**Comment by neokio** [comment]
After scouring every method and event, I've ended up with this as my preferred implementation:

    https://jsfiddle.net/designosis/oe6gzn22/

Just showing you in case it amuses you to see how people are adapting your code :)
Thanks again for the insight!
