### ISSUE TITLE
Jquery Timepicker not working on IPAD. Dropdown not showing.

### ISSUE THREAD

**Issue by MandarDasgupta** [jonthornton/jquery-timepicker#594]
The dropdown is not showing for the timpicker in IPAD.  I am not using useSelect as I want to manually change the time as well.

jquery version 2.1.4.js
 
The browser is Safari (8.4.1)

code : 

        $('#tmCheckInSelectedTime').timepicker({
            'minTime': minStartTime,
            'maxTime': maxEndTime,
            'step': 5,
            'timeFormat': 'h:iA',
          });

**Comment by MandarDasgupta** [comment]
Please someone help me.

**Comment by jonthornton** [comment]
Can you post a jsFiddle that demonstrates the problem?

**Comment by MandarDasgupta** [comment]
I will try.

**Comment by maorodriguez** [comment]
The problem is the keyboard of device
