### ISSUE TITLE
weird behaviour on firefox when showing times from 00:00 to X

### ISSUE THREAD

**Issue by jcharlet** [jonthornton/jquery-timepicker#597]
Hi,
I have that issue on Firefox while it works fine on Chrome.
I allow the user to select time using your timePicker, but when the time starts at midnight, I have a weird issue on my Firefox browser, possibly related to timezone. (I'm on Europe/London timezone)

As you can see on image, on Chrome, the input button will correctly display 00:00, 00:30, 01:00, 01:30
while on firefox it shows 23:00 23:30 01:00 01:30

any idea where this comes from? Is it a bug?

![image](https://cloud.githubusercontent.com/assets/1750370/23804845/7f6281be-05b3-11e7-8058-1be9ddacfae3.png)
https://jsfiddle.net/jeremiecharlet/Lttnyd6L/

Thanks,
Jeremie

**Comment by jonthornton** [comment]
Try upgrading to the latest version of jquery-timepicker. That should fix the problem.

**Comment by jcharlet** [comment]
it did! Thanks!
