### ISSUE TITLE
Query - Refresh TimePIcker

### ISSUE THREAD

**Issue by YLD1** [jonthornton/jquery-timepicker#598]
Sorry but the help page redirects me here

Is there a method to refresh the timepicker on an event?

**Comment by jonthornton** [comment]
Can you elaborate on what you mean by refresh the timepicker?

**Comment by YLD1** [comment]
So I have a date picker
and I have a time picker

based on the day of the date picked (e.g. Monday)
I want the time picker to show only available times for that day (e.g. Monday only show 5pm -10pm)

the time loads fine
and I have setup an event to fire when the date is picked, but how do I refresh the ID element holding the class

**Comment by jonthornton** [comment]
Can you explain what you mean by "refresh the ID element holding the class"?

**Comment by YLD1** [comment]
best if i insert the code

so following the tutorial
I have an input element with id 

> disableTimeRangesExample

`<form>

	<input id="disableTimeRangesExample" type="text" class="time ui-timepicker-input" autocomplete="off">    
</form>`


then I reference a script

`<script>
var loadtimes = function(dayName) {
	if (dayName == 'Monday')
        { 
        	$('#disableTimeRangesExample').timepicker({	
		'disableTimeRanges': [
        ['1pm', '2pm'],
        ['3am', '4:01am']
    ]            
});        	
        	 }	else 
        	 {
        	 	$('#disableTimeRangesExample').timepicker({	
		'disableTimeRanges': [
        ['1am', '2am'],
        ['3am', '4:01am']
    ]       
});
        	 }			
}
</script>`


I'm calling the function successfully
I just need to update the Input element

**Comment by YLD1** [comment]
closed it by accident sorry

**Comment by jonthornton** [comment]
Thanks, that's helpful. You need to use the `option` method to change a timepicker that has already been initialized. Like this:

```javascript
// initialize
$('#disableTimeRangesExample').timepicker()

// update based on date selection
var loadtimes = function(dayName) { 
  if (dayName == 'Monday') { 
    $('#disableTimeRangesExample').timepicker('option', { 'disableTimeRanges': [ ['1pm', '2pm'], ['3am', '4:01am'] ] }); 
  } else { 
    $('#disableTimeRangesExample').timepicker('option', { 'disableTimeRanges': [ ['1am', '2am'], ['3am', '4:01am'] ] }); 
  }
}
```
