### ISSUE TITLE
Can no longer enter time from keyboard

### ISSUE THREAD

**Issue by connor-odoherty** [jonthornton/jquery-timepicker#600]
After updating from 1.11.4 to 1.11.10, discovered that manually typing out the time in a timepicker input box no longer behaves as expected. If I attempt to type out '11:00', it autocompletes to '01:00am' after I type the second '1'. Looks like it could be auto-selecting pre-maturely here: https://github.com/jonthornton/jquery-timepicker/commit/b299cd713f48a3435c50ce42f5a0c5640c44981a?

1. 
<img width="169" alt="screen shot 2017-03-28 at 9 40 44 am" src="https://cloud.githubusercontent.com/assets/10620559/24416758/afb5c368-139a-11e7-8530-9186af902a96.png">

2. 
<img width="198" alt="screen shot 2017-03-28 at 9 40 52 am" src="https://cloud.githubusercontent.com/assets/10620559/24416762/b3cf5590-139a-11e7-985b-ea26343c1f72.png">

3. 
<img width="191" alt="screen shot 2017-03-28 at 9 40 57 am" src="https://cloud.githubusercontent.com/assets/10620559/24416767/b8a21152-139a-11e7-9a4c-5a11cefcac6d.png">

**Comment by jonthornton** [comment]
I'm unable to reproduce this on the Timepicker demo page using Mac Chrome or FF. Can you post a jsfiddle that demonstrates the problem?
