### ISSUE TITLE
Why range/format error allow to keep bad values in timepicker field?

### ISSUE THREAD

**Issue by pstephane** [jonthornton/jquery-timepicker#604]
When initializing a timepicker as below:
```
$('#example')
    .timepicker({minTime:'10:00am', maxTime:'12:00pm'});
```
Typing out of range time (`'9am'`) trigger the `timeRangeError` event but the input value contains '9am'.
For some business reasons / restrictions, we not expect that user find a way to enter not allowed time before submitting the form.  

The solution is to catch error events and add some code. To prevent not expected values sent by the form, I must empty timepicker fields value as below :
```
$('#example')
    .timepicker({minTime:'10:00am', maxTime:'12:00pm'})
    .on('timeRangeError', function () {
        $(this).timepicker('setTime', null);
    })
    .on('timeFormatError', function () {
        $(this).timepicker('setTime', null);
    });
```

Is there any reason to keep bad values in fields when triggering these errors?  
The timepicker plugin should empty the fields: what do you think?

**Comment by jonthornton** [comment]
This is by design- allowing the host application to handle validation errors provides the most flexibility. Luckily the code to clear the input is pretty simple if app developers want that behavior.

(Apologies for the comically late reply!)
