### ISSUE TITLE
Programmatically set time

### ISSUE THREAD

**Issue by rknetwork** [jonthornton/jquery-timepicker#607]
According to https://github.com/jonthornton/jquery-timepicker/pull/215 `setTime` with `dateObj` shouldn't trigger events. But it does.

```
var startTime = moment($(this).data('start-time'), 'LT', true).toDate();
$('.start .time').timepicker('setTime', startTime);

```
How do I `setTime` programmatically without triggering any events?

I guess my suggestion is to add `update` method (same as introduced in bootstrap-datepicker).

_I need to have separate events handlers for user actions and other javascript actions._

**Comment by jonthornton** [comment]
Thanks for the heads up! It's fixed in the new version 1.11.11.
