### ISSUE TITLE
Accessing from nodeList

### ISSUE THREAD

**Issue by josepvr** [jonthornton/jquery-timepicker#608]
Hello,
I have a form to set daily schedules for a week where I've created 2 timepickers for each day (start/end).
Now I would like to access each timepicker by using form elements node list but I can't get it working.

Here comes my example:
Method 1: Non working
`
var week_time = document.forms["week_sched"];
week_time.elements["sunday_start_time"].timepicker('setTime',new Date());
`
Method 2: Working
`$('#sunday_start_time').timepicker('setTime',new Date());`

Is it possible access to timepicker using method 1?

Thank you

**Comment by jonthornton** [comment]
If you want to use method 1, you need to wrap the element with jQuery, like this:
`$(week_time.elements["sunday_start_time"]).timepicker('setTime',new Date());`

**Comment by josepvr** [comment]
Thank you!
