### ISSUE TITLE
forceRoundTime with min and Max time

### ISSUE THREAD

**Issue by mohanskumar** [jonthornton/jquery-timepicker#614]
Hi, 

I am having difficulty to force the time with in the dropdown list, lets say for example,
'minTime': '2:00pm',
    'maxTime': '11:30pm',
with this, it allows to enter 9am and doesn't force the value to be in the time range.
any thoughts about it?

this can be replicated in the demo itself http://jonthornton.github.io/jquery-timepicker/

**Comment by jonthornton** [comment]
`minTime` and `maxTime` won't limit keyboard input, however it will emit a `timeRangeError` event so that you can handle input errors yourself.
