### ISSUE TITLE
Localisation & 24 hrs time format for Germany language

### ISSUE THREAD

**Issue by rksbala** [jonthornton/jquery-timepicker#615]
Facing 24hrs time format for Germany language. http://jsfiddle.net/rksbala/1xLmnhpq/1/
**Options:**
{
    show2400: true,
    timeFormat: "H:ia",
    lang: {
      am: 'uhr',
      pm: 'uhr'
    }
}
When I selected '05:00uhr' but in the list '17:00uhr' is highlighted, this value (17:00uhr) only updated.
![image](https://cloud.githubusercontent.com/assets/6780344/26517316/d03ec9b6-42b3-11e7-84a4-56ac4bd88ef4.png)

Can you please suggest what is wrong here?
http://jsfiddle.net/rksbala/1xLmnhpq/1/

**Comment by jonthornton** [comment]
timepicker seems to be getting confused by the text for am and pm being the same. Rather than adding "uhr" with the lang setting, you can do it with timeFormat, like this:
```
$('#sampleInput').timepicker({
  show2400: true,
  timeFormat: "H:i\\u\\h\\r",
});
```

This should fix the odd behavior you're seeing.
