### ISSUE TITLE
Disabling all hours before from the current time based on current date

### ISSUE THREAD

**Issue by prakashroy** [jonthornton/jquery-timepicker#619]
Disabling all hours before from the current time based on current date.

Ex:  if current time  2pm i need to disable all hours before that. 12:00 am to 1pm.

can you suggest how do this using your plugin

**Comment by jonthornton** [comment]
You can pass a Date object with the current time.

```javascript
$('#someInput').timepicker({
  'disableTimeRanges': [['12am', new Date()]]
});
```
