### ISSUE TITLE
Time Picker is not Working in Model popup.

### ISSUE THREAD

**Issue by ymahendrareddy** [jonthornton/jquery-timepicker#621]
When i click time picker it is able to show up the timings in drop down in normal page.
it is not able to show drop down Model pop up.

**Comment by jonthornton** [comment]
Please post a code sample that demonstrates the problem.

**Comment by ymahendrareddy** [comment]
Thanks for your reply. The issue was it was getting hiding behind the pop ups so I have set zindex to max number problem resolvd.

Thanks,
Mahendra
