### ISSUE TITLE
None Option Undefined

### ISSUE THREAD

**Issue by shaoqin2** [jonthornton/jquery-timepicker#622]
I added the noneoption to my picker setting and selecting the none option results in a "undefined" in the input box instead of "none" or "". Is this behavior intended? I have disabled all the event handlers but the issue remains.

**Comment by jonthornton** [comment]
Can you post a code sample that demonstrates the problem?

**Comment by xj42** [comment]
I have come across this also.
$('.time_input').timepicker({
	'className':'span1',
	'noneOption':'----',
	'minTime': '9:00',
    	'maxTime': '23:00',
	'timeFormat':'H:i',
	'scrollDefault':'10:00',
	'show2400':true
});

when i select the '---' in the input box, it changes to 'undefined'

**Comment by jonthornton** [comment]
Sorry for the slow response on this one!
