### ISSUE TITLE
Suggestion - default time range error is to set time to earliest it is allowed to be

### ISSUE THREAD

**Issue by buckmaxwell** [jonthornton/jquery-timepicker#623]
Hi - thanks for this useful widget.  I suggest that the widget gets some default in behavior in the case that the user manually inputs a time outside of the specified range.

Right now, the default is that the user can type in whatever they want even if it's outside the range.  I know you've got a function called OnTimeRange violation or something, but realistically we have to implement this every time.  Why not make it like the date picker widget by default and just auto switch it back to the earliest time it's allowed to be?

**Comment by jonthornton** [comment]
Thanks for the suggestion, and it's really nice to hear you find the widget useful. The reason I didn't build this functionality into the timepicker is to keep the widget as light as possible in terms of code size and complexity. Not every developer would want the feature to work this way, so I simply left the hooks for devs to build their own version.
