### ISSUE TITLE
Potential issue with IE Edge

### ISSUE THREAD

**Issue by Turkey2349** [jonthornton/jquery-timepicker#624]
We've logged a question on StackOverflow: https://stackoverflow.com/questions/44703034/edge-sending-one-field-in-ajax-request-with-bad-characters-%C3%A2%E2%82%AC%C5%BD-how-to-omit

After trying every approach we could think of, I think at length, the problem may be with the way the plugin initializes time and date controls with default values.

In a nutshell, only with Edge do we see the values coming back to the server with extraneous ascii or unicode encoded characters  Please see the SO question for a longer explanation.

**Comment by jonthornton** [comment]
Have you been able to confirm the char encoding issue client-side, or tested against a different backend? 

In your SO example, the date string contained extraneous from the datepicker datepicker as well as the timepicker. Does the date string contain extra chars if you don't concatenate it with the time string?

**Comment by Turkey2349** [comment]
No it has not been tested against a different backend, but I'll see what I can do there.

Yes, the date string does still contain the extra chars even if it's not concatenated with the time string.

**Comment by jonthornton** [comment]
Datepicker and timepicker don't share any code (besides jQuery), which would suggest the issue lies somewhere else.
