### ISSUE TITLE
15 minute intervals

### ISSUE THREAD

**Issue by edwardgoodnow** [jonthornton/jquery-timepicker#626]
only shows xx:00 and xx:15 when using example code ....no xx:30 or xx:45
 $('#event_time').timepicker({'timeFormat': 'h:i A',
		   setTime: new Date(),
		   'step': function(i) {
        return (i%2) ? 15 : 45;
    },
                       'minTime': '2:00 PM'
                    });

**Comment by moyuru** [comment]
see stepExample**1**  not stepExample2
$('#event_time').timepicker({'timeFormat': 'h:i A', 'step':15, 'minTime': '2:00 PM'});
