### ISSUE TITLE
Current date is updated when enter/type time in v1.11.10 not in v1.6.6

### ISSUE THREAD

**Issue by rksbala** [jonthornton/jquery-timepicker#628]
Hi,

I am using jquery-timepicker v1.11.10 with Angular directive (https://github.com/Recras/angular-jquery-timepicker)

**Issue:** Current date is updated when enter/type time.
e.g: Set date "March 29, 2015 11:00:00" then user enter/type the time, this date was changed into current date. Tried with v1.6.6, this issue not there in ver jquery-timepicker v1.6.6.

**JS fiddle:**
jquery-timepicker v1.11.10 -- https://jsfiddle.net/crfbkqxn/2/
jquery-timepicker v1.6.6 -- https://jsfiddle.net/crfbkqxn/3/

![image](https://user-images.githubusercontent.com/6780344/28415656-4b8040ca-6d6e-11e7-8c65-e0afbff6a017.png)

**Comment by jonthornton** [comment]
Disclaimer: The Timepicker directive is not part of this project. I didn't write it and I don't know how it works.

It appears that `someDateObject` is being passed into the timepicker's `getTime` method, and also being set with the result of `getTime`. When the timepicker is cleared, `getTime` returns `null`, which also sets `someDateObject` to `null`.

The solution would be to not reassign the date object that gets passed into `getTime`.
