### ISSUE TITLE
Possible to have disable time ranges per day?

### ISSUE THREAD

**Issue by dupls** [jonthornton/jquery-timepicker#630]
I have a booking form which has certain block out times, which are different from day to day. Is there a script that I can declare these dates and times to exclude or can I only block 'all hours' using the disableTimeRanges function?
Otherwise, great job! Easy to implement.

**Comment by jonthornton** [comment]
`disableTimeRanges` is your best bet. You can get pretty fine grained with it.

```javascript
$('#someInput').timepicker({
  disableTimeRanges: [
    ['9:00am', '9:30am'],
    ['11:00am', '12:00pm'],
    ['4:30pm', '5:30pm']
  ]
});
```

You could probably put the availability info in a dictionary and write a function that updates the timepicker settings based on this. Best of luck with the project!
