### ISSUE TITLE
NPM/GitHub naming conflict

### ISSUE THREAD

**Issue by spikeheap** [jonthornton/jquery-timepicker#631]
The NPM package for this repo (`jquery-timepicker`) is called [timepicker](https://www.npmjs.com/package/timepicker), however there is [jquery-timepicker](https://www.npmjs.com/package/jquery-timepicker).

Installing the `jquery-timepicker` NPM package (by mistake) gives you a time picker which looks somewhat like this project's time picker, but with (obviously) different setup and behaviours.

To make matter worse, both libraries add timepicker functionality to an input in the same way, so it's not immediately obvious that it's the wrong library. 

Would it be feasible to rename this repository to `timepicker` to match the NPM package?

If not, documenting the NPM installation process here (and in DatePair, where I first encountered this package) would reduce the chance of erroneously installing the other package.

**Comment by jonthornton** [comment]
I hear ya, I agree it's confusing. Unfortunately SEO concerns and further confusion prevent me from renaming this project.

The readme links to the npm repo from the [packaging section](https://github.com/jonthornton/jquery-timepicker#packaging). Any suggestion on how to improve the documentation?
