### ISSUE TITLE
How to I add only a range of Hours like from 9:00 to 17:00

### ISSUE THREAD

**Issue by fidabhittani** [jonthornton/jquery-timepicker#632]
I wanted to know if there is any option where I can show only the hours in the end time relative to the selected start time.

Lets say I have a selected time : `05:00`
I would want to show the the end time drop down which will start from `05:00` and will be uptill `17:00` which would make 9 hours duration in total.

**Comment by KhalilMohammad** [comment]
Did you find a solution for this?
