### ISSUE TITLE
Attach the timepicker to another element

### ISSUE THREAD

**Issue by Erowlin** [jonthornton/jquery-timepicker#635]
Hey, 

I would like to be able to attach / position the Timepicker to another element, while still using an hidden input so it can stores the value somewhere (and it does not fuck with `datepair` library which **mandatory** needs an input as a timepicker. 

Here is a JSFiddle to show that the Timepicker cannot be attached to something else: 
http://jsfiddle.net/nv736gbv/5/

<img width="393" alt="screen shot 2017-08-24 at 11 03 05" src="https://user-images.githubusercontent.com/1775878/29658616-dff923da-88bb-11e7-94eb-e533a30e97de.png">

As you can see, when clicking on the span "click me", the timepicker is attached to the hidden input. That's the proper behaviour, however it would be nice in the library to be able to set it's "attach point" (on which element the timepicker should be displayed). 

I already tried the `appendTo` option, without success. 

Hope it makes sense. 

Thanks !

**Comment by Erowlin** [comment]
Ok, I have an absolute UGLY fix so everything works properly. It would be nice that the library support that option by default. 

Here is the hack I used. Let me know if you add an option to support that feature. Thanks. 

http://jsfiddle.net/nv736gbv/10/

<img width="373" alt="screen shot 2017-08-24 at 11 31 44" src="https://user-images.githubusercontent.com/1775878/29659871-d474440a-88bf-11e7-9d41-d5aa4cf59a23.png">

**Comment by gicalle** [comment]
Rather rude question, but anyway.
bind the timepicker to your span and copy the selectedtime to your hidden input...

```javascript
$(function() {
	var timePicker = $('.my-date-span').timepicker();

	timePicker.on('selectTime', function() {
		myTime = moment($(this).timepicker('getTime')).format('HH:mm');

		console.log(myTime);
		$('#example').val(myTime);

		$('.my-date-span').html("Click me : " + $('#example').val() );
		$('#example').show();
	});
});
```

**Comment by Erowlin** [comment]
Sorry, wasn't meant to be rude at all :). 

Is it gonna work properly with the pair library? 

Thanks.

**Comment by jonthornton** [comment]
@Erowlin you'll need to write a custom `updateTime` function for datepair.js, but it's doable.

**Comment by jonthornton** [comment]
Thank you for posting the full working example, btw. It's always more fun to answer answerable questions :)

**Comment by Erowlin** [comment]
Thanks for the update @jonthornton. The documentation of pair.js may need to be updated to precise that the time picker MUST be attached to an input. 

Right now, there is a conflict with the two libraries: 
- In timepicker.js, it says that it can be attached to any element (not only inputs)
- In datepair.js, nothing mention the fact that without an input, it does not work. 

Thanks !

**Comment by jonthornton** [comment]
Good point! Updated docs here https://github.com/jonthornton/Datepair.js/commit/3e23953facf1aa4e09d3c008bb0ef2b752821942

**Comment by Erowlin** [comment]
Thanks @jonthornton :). Closing the issue.
