### ISSUE TITLE
Mobile Safari browser - after selecting a time, the box keeps reopening

### ISSUE THREAD

**Issue by gwalshington** [jonthornton/jquery-timepicker#637]
Only on a mobile device, and in safari browser. After selecting a time, if you click anywhere else on the screen, the dropdown reopens

I've tried adding `closeOnWindowScroll: true` but it does not resolve the issue. I've also tried adding a focus to another field, but that also doesn't work for me.

**Comment by Tusko** [comment]
+1

**Comment by jonthornton** [comment]
I'm having trouble reproducing this bug. Can you provide details on which device and Safari version you're using, and exact steps to reproduce?
