### ISSUE TITLE
Dynamically created inputs

### ISSUE THREAD

**Issue by hoangphison** [jonthornton/jquery-timepicker#638]
Hi, i want to use inputmask in my project with that [bootstrap snippet](http://bootsnipp.com/snippets/featured/multiple-fields). But time picker and Datepair.js doesn't work with new inputs.
And i don't know how do it, please help me. Thanks!

Sorry for my bad english.

**Comment by jonthornton** [comment]
You'll need to bind Timepicker and Datepair when you create the new inputs. I'm sorry I can't provide more help.
