### ISSUE TITLE
setTime does not work with useSelect option

### ISSUE THREAD

**Issue by njall** [jonthornton/jquery-timepicker#641]
Hi,

I setup a timepicker with the useSelect option. I want to be able to set the value/text of this from an event - but the setTime option doesn't seem to work and there is no ID on the select element for me to set it with. Any help would be much appreciated!

```
$('#mydiv').timepicker({
            useSelect: true
}) 
$('#mydiv').timepicker('setTime', new Date());

<input id='mydiv'/>

```

**Comment by njall** [comment]
I worked around it by wrapping in a div, but would like to know if setTime should work for useSelect option?

```
<div class='blah'>
<input id='mydiv'>
</div>

$('.blah select').val('3 pm')
```

**Comment by Erowlin** [comment]
+1

**Comment by jonthornton** [comment]
Thanks for raising this issue! Should be fixed now.
