### ISSUE TITLE
Duration being shown on both start and end

### ISSUE THREAD

**Issue by KrunchMuffin** [jonthornton/jquery-timepicker#643]
It initializes fine, but after i do the following...

`var newtime = moment(amShift,'h:mm a').add(15,'minutes')`
`$('#ShiftTimeIn').timepicker('option', 'minTime', newtime.format('h:mm a'))`

duration shows up in both start and end times and they are different.

![image](https://user-images.githubusercontent.com/1037197/30728885-5b2a3d22-9f29-11e7-87ed-4d5de192571a.png)
![image](https://user-images.githubusercontent.com/1037197/30728892-64177b0c-9f29-11e7-9057-ddfdb031b920.png)

http://jsfiddle.net/fv9m5my0/30/

**Comment by KrunchMuffin** [comment]
As soon as I posted this, I thought to myself, hmmm... what if I just put showDuration in a data attribute in the end time only. What do you know, it worked. Not sure tho if this would still be a bug or not. Because all other usage the duration never shows in start.

**Comment by jonthornton** [comment]
Thanks for sharing this! `showDuration` gets activated anytime you set a `minTim` - that's why it was showing on the start time picker. Glad you figured out a solution!

**Comment by KrunchMuffin** [comment]
Ok, I get that, but should they not be the same durations? In both screens they are set for 9pm - 2am top one shows 9hrs whereas the bottom shows 5hrs. Where is the 9hrs calculated from?

**Comment by jonthornton** [comment]
It's hard to say without all of the application's source code. Wish I explain more.
