### ISSUE TITLE
Suggestion: scrollDefault now, but when typing in time, default to AM

### ISSUE THREAD

**Issue by whiteazn** [jonthornton/jquery-timepicker#644]
I was wondering if it was possible to do something like this.

Right now I have something like this:

`$('.time').timepicker({
	'timeFormat' : 'h:i a',
	'step' : 5,
	'forceRoundTime' : false,
	'scrollDefault': 'now'
});`

So, when I click on box, it will show a time starting at 2:05pm (current time is 2:08pm)

But when I start typing, say, "08" (as to type 08:00), it will then suggest and highlight/enter 08:00 pm.

But I was hoping to make it show "08:00 am" instead, despite current time being pm.  Looks like when I type in a value, it goes to the next value in the list after current time, which is obviously going to be 08:00 pm.

Is there a way to do this?  I would like scrollDefault: now be the main behavior (as that would be fine in most cases), but then if not current time, user will be entering in a time manually, and in those cases, will be all AM times.

**Comment by jonthornton** [comment]
No, unfortunately it's not currently possible to customize how autocomplete works. If you'd like to take a shot at modifying the plugin source, the relevant code will be found in the `_time2int` function.
