### ISSUE TITLE
Timepicker retains same values of disableTimeRanges even on date change

### ISSUE THREAD

**Issue by shelleyvs** [jonthornton/jquery-timepicker#645]
I have the timepicker which i have integrated with jQuery Datepicker plugin. On selecting the date i have made a on change function which runs an ajax request and provides JSON values of disableTimeRanges. 

```
<script type="text/javascript">
$.ajaxSetup({ cache: false });
$('#consultdate').change(function() {
consultdate = $('#consultdate').val();
userid= '<?php echo $nurse_id;?>';
cat = '<?php echo $category;?>';
//alert(consultdate);
$.ajax({
type: "POST",
url: 'qry/date-time_qry.php',
cache: false,
dataType : "text",
data: {consultdate : consultdate, userid : userid, cat : cat },
success: function(data)
{
if (!$('input#consulttime').data("set")) {
//alert(data);
$('input#consulttime').prop("disabled", false);
$('input#consulttime').timepicker({'timeFormat': 'h:i A','disableTextInput': true, 'minTime': '<?php echo $consultation_start; ?>','maxTime': '<?php echo $consultation_end; ?>','step': 15,'disableTimeRanges':JSON.parse(data)});
}
},
error : function() {
alert("Error while loading data");
}
});
});
</script>
```
The issue is that once i select a date the timepicker retains the "disableTimeRanges" irrespective of what i do to clear cache etc..
`$.ajaxSetup({ cache: false });`

Is it some bug?? How can i reset the disableTimeRanges on date change.

**Comment by gicalle** [comment]
once initialized, remove the previous timepicker -timepicker('remove') and re-initialize?

`$('#disableTimeRangesExample').timepicker('remove').timepicker({'disableTimeRanges': [
        ['1am', '2am'],
        ['3am', '6:01am']
    ]
});`

**Comment by shelleyvs** [comment]
@gicalle Thank you for the solution.

**Comment by jonthornton** [comment]
@shelleyvs you probably want to use the `option` method for this https://github.com/jonthornton/jquery-timepicker#methods
