### ISSUE TITLE
Repopulating timepicker with times earlier than scrollDefault

### ISSUE THREAD

**Issue by skenny** [jonthornton/jquery-timepicker#647]
I have a timepicker initialized with the following options:

{
    timeFormat: 'g:i A',
    scrollDefault: '08:00',
    step: 15
}

When repopulating the input on page load, if the time value is earlier than 8:00AM, the time appears as PM.  For example, if I previously entered "7:30 AM" and then reload the page, I see "7:30 PM".

I tested this with various times and various scrollDefault values and it is consistent.

Removing the scrollDefault option fixes the issue.

**Comment by m-alikhani** [comment]
I have a same problem
when set step option to other value, 'scrollDefault' option not working.

https://jsfiddle.net/m_alikhani/uejx9vrn/14/

**Comment by jonthornton** [comment]
I'm not able to reproduce this bug in the current version of timepicker.
