### ISSUE TITLE
Disable/Hide AM & PM in duration & default on selection

### ISSUE THREAD

**Issue by weedkiller** [jonthornton/jquery-timepicker#651]
Hi, I have user who just want to **enter amount of time worked only, i.e. no AM or PM**, i.e. how long and _not_ when for 8HRs, or 14 hrs etc.

I was unable to disable the AM & PM text, can you please share the setting/example to disable it.

Also 

- [ ] In duration, how to display only time entry, not AM/PM or dates
- [ ] how to show default hours: for e.g. on select box, `default to 08:00 hrs.` no AM or PM
- [ ] Different color for HH:MM hours (Blue) and Mins (green)
- [ ] saw your example with non-input, I was trying to workout how to show a button like below, to click so that it fills or clears, using toggle. Check, X mark toggle on the right of the box.
 `https://github.com/kbwood/timeentry/blob/master/jquery.timeentry.js`
![image](https://user-images.githubusercontent.com/21086190/34395645-00141932-eb30-11e7-9288-dc1586832120.png)

thanks

**Comment by jonthornton** [comment]
jquery-timepicker might not be the best tool for the job here. If you're looking to capture a time _duration_, I'd recommend a simple select element. jquery-timepicker is design for selecting a specific time of day, not for expressing an amount of time.

You can hide the AM/PM with the timeFormat option: `$('#someInput').timepicker({ 'timeFormat': 'h:i' })'.
