### ISSUE TITLE
How to set the time to 24:00:00 "programmatically"

### ISSUE THREAD

**Issue by KishoreBarik** [jonthornton/jquery-timepicker#656]
I have the option 24:00:00 in the dropdown selection. However I am not able to set the value to 24:00:00 programmatically on click of a button.

**Note:** Using v1.4.6
I can see 24:00:00 as in dropdown by using {timeFormat: 'H:i:s'} as option only

**Comment by jonthornton** [comment]
This should work now. Initialize a timepicker like this
```
$('#basicExample').timepicker({
  'timeFormat': 'H:i',
  'show2400': true
});
```

And then programmatically set the time like this
```
$('#basicExample').timepicker('setTime', '24:00'); 
```
