### ISSUE TITLE
How can I print the "showDuration" variable in PHP

### ISSUE THREAD

**Issue by MorenoHub** [jonthornton/jquery-timepicker#657]
The code works perfectly for me. I only want to show the duration in a php page, instead inside the dropdown list.
One more question, it is possible to subtract time then? (Like a lounch break).

Thanks

**Comment by jonthornton** [comment]
You'll need to pass the `showDuration` and any other values back to the server as query parameters. I'm not going to be able to help you with this- server-side scope is beyond the scope of what I can provide support for.

**Comment by MorenoHub** [comment]
Ok.  I understand. I have to work the query inside the JS file an then send to php again. I think so. Thanks
