### ISSUE TITLE
Dropdown does not align properly when using noneOption and MinTime together

### ISSUE THREAD

**Issue by Zelig880** [jonthornton/jquery-timepicker#661]
If timepicker configuration includes a couple of none options and a MinDate, when clicking on the input field, the dropdown will scroll down to and just show the last NoneOption instead than start from the top.

An example code is:
`
$("#timepickerInput").timepicker({
                "noneOption": [
                    {
                        "label": "OFF",
                        "value": "OFF",
                        "className": "black"
                    },
                    {
                        "label": "HOL",
                        "value": "HOL",
                        "className": "green"
                    },
                    {
                        "label": "EDU",
                        "value": "EDU",
                        "className": "yellow"
                    },
                    {
                        "label": "BANK",
                        "value": "BANK",
                        "className": "blue"
                    },
                    {
                        "label": "SICK",
                        "value": "SICK",
                        "className": "red"
                    }
                ],
                "timeFormat": "H:i",
                "minTime": "8:00",
                "maxTime": "23:30"
            });`

This will show:
![image](https://user-images.githubusercontent.com/9040770/36172536-219665da-10fe-11e8-8bad-8f22763a123a.png)

instead than:

![image](https://user-images.githubusercontent.com/9040770/36172566-34788c96-10fe-11e8-961c-57f0ad3a5243.png)

Can replicate. The only way to solve the issue if to remove the MinTime

**Comment by jonthornton** [comment]
You can fix this by setting `scrollDefault` to your first noneOption, like this:
```
$("#timepickerInput").timepicker({
  "noneOption": [ { "label": "OFF", "value": "OFF", "className": "black" }, { "label": "HOL", "value": "HOL", "className": "green" }, { "label": "EDU", "value": "EDU", "className": "yellow" }, { "label": "BANK", "value": "BANK", "className": "blue" }, { "label": "SICK", "value": "SICK", "className": "red" } ],
  "timeFormat": "H:i",
  "minTime": "8:00", 
  "maxTime": "23:30",
  "scrollDefault": "OFF" });
```
