### ISSUE TITLE
options not working

### ISSUE THREAD

**Issue by zenuke** [jonthornton/jquery-timepicker#663]
Trying to use this in an MVC project. It works with the defaults but adding any options causes it to either not work at all or the options used are not used. 

so $("#something").timepicker() works just fine but say doing $("#something").timepicker({'step':15}) does not and just causes the default settings.

CSS is loaded if that matters.

**Comment by jonthornton** [comment]
@zenuke can you post a jsFiddle or some other working demo of the problem?
