### ISSUE TITLE
disableTimeRanges not changing 

### ISSUE THREAD

**Issue by anamicab** [jonthornton/jquery-timepicker#664]
# Function which i have created 
            **function disableTime(timeDisabled) {
                console.log(timeDisabled);
                $('#timepicker_input').timepicker({ 
                    'setTime': new Date(),
                    'scrollDefault': 'now',
                    'disableTimeRanges':timeDisabled,
                    'appendTo': ".time-container"
                   });
         }**

Here, **timeDisabled** is an array and which is different everytime but i am getting the first data which list have inflated.
Its not refreshing the list again.

**Comment by FalkoJoseph** [comment]
Same problem here, would like to know :)

**Comment by jonthornton** [comment]
You need to use the `option` method when updating settings for an existing timepicker. Your code would look like:
```
function disableTime(timeDisabled) {
  $('#timepicker_input').timepicker('option', {
    'disableTimeRanges':timeDisabled
  });
}
```
