### ISSUE TITLE
no style box container

### ISSUE THREAD

**Issue by daisys77** [jonthornton/jquery-timepicker#666]
can you tell me what i can do to get to get this code to work. it doesnt appear in abox just all over the screen. i upload image.

                            <div class="demo">
                           
                                    <input id="durationExample" type="text" class="time" />
                                </p>
                            </div>
                            <script>
                                $(function() {
                                    $('#durationExample').timepicker({
                                        'minTime': '2:00pm',
                                        'maxTime': '11:30pm',
                                        'showDuration': true
                                    });
                                });
 
</script>

[IMG]http://i66.tinypic.com/2e5uuk1.png[/IMG]

**Comment by jonthornton** [comment]
You'll need to post a live example of the problem - there's not enough info here for me to help.
