### ISSUE TITLE
Disable Time Ranges for "24 Hours" Format is not working. 

### ISSUE THREAD

**Issue by furqan-shakir** [jonthornton/jquery-timepicker#668]
Hi, 
I created the date picker with 24 Hours Format, Every thing was fine until I want to disable a rang of times:
` $('#txtNightOverNightShiftStartTime').timepicker({
                    'disableTimeRanges': [
                        ['6:01', '16:59']
                    ]
                });`
When I call the previous code, the times list shows times like AM/PM format!

**Comment by jonthornton** [comment]
This code is re-initializing the timepicker without 24 hour formatting: `$('#txtNightOverNightShiftStartTime').timepicker({ 'disableTimeRanges': [ ['6:01', '16:59'] ] })`

Try it like this:
```
$('#txtNightOverNightShiftStartTime').timepicker({ 
  'disableTimeRanges': [ ['6:01', '16:59'] ],
  'timeFormat': 'H:i'
})
```
