### ISSUE TITLE
Time not disabling if mintime is in the middle of a range

### ISSUE THREAD

**Issue by eric-mathison** [jonthornton/jquery-timepicker#669]
I have a function used for minTime rounding the current time to the next half hour. If this time is in the middle of the start and end values in the disabletimeranges array, that time isn't disabling. The next step time is disabling though, if also in the range. 

For example: current time is 17:35. My function would round the time to 18:00. Mintime then would be set to 18:00. 

Say i have an array ["5:00pm", "8:00pm"] in disabledtimeranges...

The 18:00 (mintime) would be selectable and the other times, 18:30, 19:00, and 19:30 would be disabled (as I would expect).

**Comment by jonthornton** [comment]
This should be fixed in the latest release.
