### ISSUE TITLE
Setting useSelect to true generates an unnamed select box

### ISSUE THREAD

**Issue by alogim** [jonthornton/jquery-timepicker#670]
Whenever I set `"useSelect": true`, it automatically generates an unnamed select box, that is, a select box with class `ui-timepicker-select` but without name or id.
This is a problem for me, since I am using jQuery Validation Plugin to validate a form, and it complains about unnamed field on submitting. Also, it gives problem to show the error/success feedback, since it has no name.

Is there a workaround to this?

**Comment by jonthornton** [comment]
Thanks for the heads up! This should be fixed now. The select field generated for useSelect will be named ui-timepicker-parentName, where parentName is the name of the parent input.
