### ISSUE TITLE
Javascript timepicker range update

### ISSUE THREAD

**Issue by tsapina** [jonthornton/jquery-timepicker#679]
When user first time select date from **datepicker** then i get data from server and put them into array in right format. This array i use for **timepicker** in **disableTimeRanges**. That works when user click first time but when user change date second time then disableTimeRanges wont update so it stay same as first time.

Is there way to "reset" timepicker when user click on datepicker?

`$("#datefrom").datepicker({
    dateFormat: 'dd-mm-yy',
    onSelect: function (date) {
       $.post("ajax-date-check.php", {'date': date}, function(result){

            var ret = result.replace(/"/g,'');
            var length = ret.length; 
            var string = ret.slice(1, length-1);
            var array = JSON
            .parse('[' + string.replace(/'/g, '"') + ']')
       .reduce((r, s, i) => r.concat([i % 2 ? r.pop().concat(s) : [s]]), 
        []);

        $('.timepicker1').timepicker({
            'timeFormat': 'H:i',
            'minTime': '8:00am',
            'maxTime': '8:00pm',
            'disableTimeRanges': array,
            'show2400': true
        });
  });

  }
});`

**Comment by jonthornton** [comment]
Use the `option` method to update a timepicker that's already been initialized:

`$('#optionExample').timepicker('option', 'disableTimeRanges', array);`
