### ISSUE TITLE
when I press a button add 45 minutes

### ISSUE THREAD

**Issue by adonet** [jonthornton/jquery-timepicker#680]
How can I do so when I press a button add 45 minutes ?

 document.getElementById("add_45").onclick  = function()
   {

   }

**Comment by adonet** [comment]
document.getElementById("boton_1_mas").onclick  = function()
   {

      hora_valor = document.getElementById('hora').value;
	  var d = new Date("1984/03/29 "+hora_valor);
      var hours=d.getHours();
      var minutes=Math.round(d.getMinutes());
      var ampm = hours >= 12 ? 'PM' : 'AM';
      var Time=hours+':'+minutes;
      var DisplayTime=addMinutos(Time, 45);


       $('#hora').timepicker('setTime', DisplayTime);
   }


   function addMinutos(time/*"hh:mm"*/, minsToAdd/*"N"*/) 
{
        function z(n)
        {
           return (n<10? '0':'') + n;
        }
        var bits = time.split(':');
        var mins = bits[0]*60 + (+bits[1]) + (+minsToAdd);
        return z(mins%(24*60)/60 | 0) + ':' + z(mins%60); 
 }

**Comment by jonthornton** [comment]
Could you try restating the question? I don't understand.
