### ISSUE TITLE
only works on page load

### ISSUE THREAD

**Issue by 54696d20** [jonthornton/jquery-timepicker#684]
I have a Start and End time. If the page loads. I have a Array that records selected dates. If those dates are selected: `//disable selected times
                $('#startTime').timepicker({
                    'step': 15,    
                    'disableTimeRanges': disableTimes
                });`
If the page loads. I add an option to select another range. It calls a function to populate that div after selected start and end; however, if the page doesn't load, those selected dates don't get disabled.

Any idea's?

Thanks

**Comment by ShajaatK** [comment]
If I am not wrong by 'selected dates dont get disabled' you mean 

> times?

If you need to add fresh set of disableTimeRanges then you can achieve it by removing the timepicker and then do the re-binding by supplying new set of disabled time ranges.
`$(element).timepicker('remove');`
while binding dynamically you need to pass array of time ranges, make sure that it is in pair of start time and end time each.

**Comment by harrybailey** [comment]
Consider instead 
`		$('#timepicker').timepicker('option', {
			'disableTimeRanges':newRange
		});`
