### ISSUE TITLE
$.fn.timepicker.defaults doesn't work.

### ISSUE THREAD

**Issue by GoldenFlamePhoenix** [jonthornton/jquery-timepicker#689]
i tried $.fn.timepicker.defaults.step = 15 and it gives error 
![1](https://user-images.githubusercontent.com/36264717/51082962-3157f980-1737-11e9-960f-e2d98b96f141.PNG)

Then i tried this piece of code it didn't give any error but also it didn't do any thing. 

$.fn.timepicker.defaults = {
            step: 15
};

And non of this work. So how can i set default values for timepicker.

**Comment by gicalle** [comment]
from the example page
`$('#stepExample1').timepicker({ 'step': 15 });`

just initialize your timepicker with the wanted settings.

**Comment by Sergio1C** [comment]
I want use global configuration to all instances (how [here](https://github.com/jonthornton/jquery-timepicker)) but in console i have:

`$.fn.timepicker.defaults()
Uncaught TypeError: $.fn.timepicker.defaults is not a function at <anonymous>`

**Comment by jonthornton** [comment]
Global configuration options aren't supported - `$.fn.timepicker.defaults` isn't intended to be modified outside the library. I recommend @gicalle's approach.

**Comment by bytestream** [comment]
This should be a feature request not a closed question. The suggested solution only works for a specific element. It would be highly beneficial to be able to set global defaults, particularly for the `lang` object.

Suggest to reopen.

It looks like a pretty simple case of renaming https://github.com/jonthornton/jquery-timepicker/blob/master/jquery.timepicker.js#L37 to `$.fn.timepicker.defaults` and moving it to the end of the file (after the plugin entry).

Happy to submit PR
