### ISSUE TITLE
re-loading timepicker options - Object doesn't support property or method 'timepicker'

### ISSUE THREAD

**Issue by VictorCompany** [jonthornton/jquery-timepicker#690]
Hi, I am trying this on an ASP.NET MVC application. There is an issue while changing timpicker after the page once loads.  Initial load timpicker is attached to the input control and works, but on change event  when i want to change the options for timepicker, i keep getting the javascript error:  
JavaScript runtime error: 
**Object  doesn't support property or method 'timepicker'.** 

The line that gives error is:  $('#EndTime').timepicker('option', 'minTime', '14:00');

I was trying to see any problem in referencing the JQuery libraries, but can't get this error to go away. Appreciate a likely fix. Thank you.

My code:

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>

                <input type="text" id="EffectiveTime" name="EffectiveTime" placeholder="20:00"   class="form-control time" />
                <input type="text" id="EndTime" name="EndTime" placeholder="20:00"   class="form-control time" />

<script type="text/javascript">

    $('#EffectiveTime').timepicker({
        timeFormat: 'H:i',
        step: 1,
        minTime: 0,
        scrolldefault: '00:00',
        zindex: 100,
        orientation:'b'
    });

    $('#EndTime').timepicker({
        timeFormat: 'H:i',
        step: 1,
        minTime: 0,
        scrolldefault: '17:00',
        zindex: 100,
        orientation:'b'
    });
    $('#EffectiveTime').on('change', function () {

        $('#EndTime').timepicker('option', 'minTime', '14:00');            

    });

</script>

**Comment by VictorCompany** [comment]
Also want to mention, likely because of the same cause, the timepicker can also not be attached under the $( document ).ready(). As soon as I place the $('#EffectiveTime').timepicker() under ready() function same error occurs: **Object  doesn't support property or method 'timepicker'.** . Likely due to Jquery library referencing.

**Comment by jonthornton** [comment]
Hi, I wish I could help but too much of this involves your application. If you can isolate the error in a jsfiddle I can definitely take a closer look.

**Comment by VictorCompany** [comment]
Hi jonthornton, Thank you for getting back. 

Likely this is environment related.  But I have tried with a blank project on Asp.net MVC and i get the issues.
In jsfiddle I don't get the error(regarding timepicker() previous post) when document.ready() function executes, in ASP.net page i use the exact same code. Also, in both jsfiddle and asp.net MVC code the 'change' function is not getting attached to the timepicker controls. I wanted to update the second control. I wanted to understand why ASP.NET MVC environment in Visual Studio giving the problem explained in the original post.

Sharing the link from JsFiddle:

https://jsfiddle.net/m42p6bgq/4/

**Comment by jonthornton** [comment]
The code in the jsfiddle looks correct - the onchange event fired when I tested it 🤷‍♂️
