### ISSUE TITLE
step function is being ignored

### ISSUE THREAD

**Issue by jasonhall0612** [jonthornton/jquery-timepicker#693]
Whenever I enter a time of say 10:34 the drop down has the next time at 10:34 and then 11:04 etc.. I have the step at 15 but it seems to ignore that. I want if say my time is 10:34 my next time in the list would be 10:45 and then 11:00 and then 11:15.

var times = ['#ORDERTIME', '#READYTIME', '#PICKTIME', '#DISPTIME', '#DTIME'];
        $.each(times, function(index, value) {
            $(value).timepicker({
                'minTime': '00:00',
                'maxTime': '23:59',
                'timeFormat': 'HH:mm',
                'scrollDefault': 'now',
                'forceRoundTime': true,
                'step': 15,
                'show2400': true,
                'useSelect': true
            });
        });

**Comment by jonthornton** [comment]
Hi Jason, I don't see any obvious errors with the code you posted. If you post a jsfiddle with a working example, I can investigate whether this might be a timepicker bug.
