### ISSUE TITLE
change the  place of the timepicker

### ISSUE THREAD

**Issue by tamarshankolevsky** [jonthornton/jquery-timepicker#694]

**Comment by tamarshankolevsky** [comment]
How to put the time picker right align and not in the left of the element?
my code:
ts:
 selector.timepicker(
                    {
                        'timeFormat': 'H:i',
                        'step': 5,
                        'noneOption':"className:'a'",
                    }
                );
html:
 <input type="text" maxlength="5" class="form-control js-timepicker" (keyup)="onKey($event)" name="end_time_to" formControlName="end_time_to">

**Comment by jonthornton** [comment]
Try this: `selector.timepicker({orientation: 'r'});`
