### ISSUE TITLE
Setting minTime using a jscript variable and scrollDefault value using custom value

### ISSUE THREAD

**Issue by rohantapiyawala** [jonthornton/jquery-timepicker#695]
Im using this repository for a project im working on right now, which picks date (another plugin) and this library for time picker for a meeting to setup. 

I use 2 timepicker inputs, one to fetch the time for the meeting and other to fetch the duration from that time. For 2nd timepicker I want to set the minTime value as the value selected from first timepicker and max value = minTime + 12hrs 

Any help on how to set that? my code:

```

$('#timePicker').timepicker({ 
	'forceRoundTime': true,
	'timeFormat': 'h:i a',
	'scrollDefault': 'now' 
});
var timeSelected;

$('#timePicker').on('changeTime', function() {
	timeSelected = 'Time selected: ' + $(this).val();
	console.log(timeSelected);
	$('#durationPicker').timepicker({ 
		'forceRoundTime': true,
		'timeFormat': 'h:i a',
		'scrollDefault': true,
		'minTime': timeSelected,
		'maxTime': '11:30pm',
		'showDuration': true 
	});
});

```

Also want to the set the "scrollDefault = current time + 2 hrs", any pointers on that as well. 

Please do reply back, its kinda urgent. 

Thank you.

**Comment by jonthornton** [comment]
It sounds like https://github.com/jonthornton/Datepair.js might solve your problem

**Comment by judemanutd** [comment]
For anyone looking for the answer to synchronize start and end pickers with time only 

```javascript
$(".ui-timepicker-input").on("changeTime", function() {
      var ele = $(this);
      var selected_time = ele.val();
      var time = moment(selected_time, ["h:mma"]);

      var ele_other = $("#end_date_picker");

      if (type === "start") {
        // set end date
        ele_other.timepicker("option", {
          minTime: time.format("h:mma"),
          maxTime: "11:30pm",
          forceRoundTime: true,
        });
      } else {
        // set start date
        ele_other.timepicker("option", {
          minTime: "12:00am",
          maxTime: time.format("h:mma"),
          forceRoundTime: true,
        });
      }
 });
```
