### ISSUE TITLE
Re enable, disabled hours

### ISSUE THREAD

**Issue by minijavi19** [jonthornton/jquery-timepicker#696]
I need to schedule a delivery from a store, when you select today the hours that have already passed get disabled with 
`.timepicker({
                    'disableTimeRanges': [
                        ['12am', e]
                    ]
                });`

but when I select tomorrow or any other day, the options stay disabled and even if I call .timepicker() again they stay the same, any solution to this? Thanks in advance.

**Comment by jonthornton** [comment]
Try `.timepicker(`option`, { 'disableTimeRanges': [ ['12am', e] ] });`
