### ISSUE TITLE
$(...).timepicker is not a function error

### ISSUE THREAD

**Issue by xphoenyx** [jonthornton/jquery-timepicker#699]
Hello @jonthornton, I just found that starting from version 1.11.14, timepicker is simply not being attached to $.fn scope. I did different checks to ensure this is not my fault with no luck, then I downgraded to version 1.11.12 and the plugin started working again.

**Comment by jonthornton** [comment]
The demo at http://www.jonthornton.com/jquery-timepicker/ is running on version 1.11.15. Does the problem go away if you upgrade?

**Comment by xphoenyx** [comment]
Ok, that's odd. When I encountered that issue, I also went checking plugin demo page and found that version 1.11.12 was in use on that moment. But yes, now it appears to be 1.11.15. Anyways, that doesn't really clarify the cause of the "not a function" error.

Is there any extra info I can provide you for better problem understanding? Or should I check somewhere else?

**Comment by xphoenyx** [comment]
I just upgraded to 1.11.15 just to ensure if problem still exists and voila - it is gone! :) Can't really tell what happened, but the issue seems to be resolved, so closing it now. Thank you for your response and for this amazing plugin!
