### ISSUE TITLE
Timepicker input dropdown mismatch

### ISSUE THREAD

**Issue by HCuevas14** [jonthornton/jquery-timepicker#700]
When typing in times without the colon the dropdown does not always display the correct amounts. For example when you type 83 you would expect the dropdown to display 8:30, but instead the dropdown selects 11:00 AM. This is made worse by the fact that if you click outside of the input, 11:00 AM is then put into the input.

**Comment by jonthornton** [comment]
This is finally going to get fixed in the next release.
