### ISSUE TITLE
if statement on input

### ISSUE THREAD

**Issue by MaxAntony4** [jonthornton/jquery-timepicker#701]
it is the situation,
the business opens at 12:00 - 23:00 at the weekend and public holidays but 14:00 - 23:00 at the weekdays.

First is there a way to input a date on the script so it is counted as holidays?
The second after the customer choose weekend or "set holidays" on the date picker
the time picker's drop-down list automatically remove the choices of 12:00 - 13:45 
and the interval should be 15mins

**Comment by jonthornton** [comment]
Hi @MaxAntony4, your app's code will need to keep track of the date and update available times using jquery-timepicker's `option` method.
