### ISSUE TITLE
Using REQUIRED with timepicker

### ISSUE THREAD

**Issue by EdCloutier** [jonthornton/jquery-timepicker#706]
I've used this plugin for a while successfully, but one bootstrap-based project needed the time field as "required". eg:
<input name="formEventOpeningTime" class="time timepicker" type="text" style="width:75px" required />

Setting the REQUIRED field in the timepicker form caused it to be flagged before the form was actually submitted. Is there any way to have the required highlight on show if the form was submitted?

**Comment by jonthornton** [comment]
Hi Ed, this seems like a bug in timepicker. I just pushed up a new version (https://github.com/jonthornton/jquery-timepicker/commit/912891f74af93371d6f38b5f8c1cd7af3459e29f). Can you see if it fixes the problem you're seeing?

**Comment by EdCloutier** [comment]
Perfect: my tests now show the issue is resolved. Thanks for your quick response!
