### ISSUE TITLE
Unique IDs for timepicker Divs displayed

### ISSUE THREAD

**Issue by djmike3404** [jonthornton/jquery-timepicker#709]
Allowing the option to give unique IDs to the timepicker div displayed would be nice as this is why I dumped the use of it. Not being able to track which timepicker drop down is open or closed when using multiple was a necessity.

**Comment by jonthornton** [comment]
Can you explain your use case a bit more or give an example of how Timepicker didn't work for your situation?

**Comment by djmike3404** [comment]
Sure jon. I have a hidden menu that comes up with the fields that timepicker would have been used for. I have to track if the menu is open by the div id and the .style.display value. I also has to track if a click occurs outside of the menu div to close it. I needed to be about to assign ids to the divs for 2 seperate timepicker inputs to keep the menu open while either of the timepicker inputs was used with a simple if statement as this cause the menu to close everytime because I was technically clicking outside of the menu div

**Comment by jonthornton** [comment]
Hey, sorry for disappearing. Crazy times!

So I think you have two options that don't depend on assigning an ID to the timepicker dropdown.

Let's assume you have this DOM:
```
<div id="someWebApp">
  <div id="hiddenMenu">
    <div id="time1Wrapper">
      <input type="text" id="time1" />
    </div>
    <div id="time2wrapper">
      <input type="text" id="time2" />
    </div>
  </div
  ... more stuff here
</div>
```

*First option* involves use of `appendTo`. Initialize the timepickers like this
```
$('#time1').timepicker({
  'appendTo': $('#time1wrapper')
});
```

and you'll be able to select the time1 drowndown with `$('#time1wrapper .ui-timepicker-wrapper')`. You can then use `$('#time1wrapper .ui-timepicker-wrapper').is(':visible')`.

*Second option* is to use a lock. 
```
var timepickerOpen = false; // this is global

function closeHiddenMenu() {
  if (!timepickerOpen) {
    // hide the menu
  }
}

$('#hiddenMenuTimeInput1').timepicker(); // init with whatever options you want
$('#hiddenMenuTimeInput1').on('showTimepicker' function() {
  timepickerOpen = true;
}).on('hideTimepicker', function() {
  timepickerOpen = false;
});
```

Assuming changing `appendTo` doesn't mess with your app, I'd go with that approach.
