### ISSUE TITLE
Syntax error in regular expression

### ISSUE THREAD

**Issue by tychokamphuis-accommodatiehuur** [jonthornton/jquery-timepicker#710]
Hi.

The new 1.13.2 updates conflicts with IE11 and Edge, as the 'u' flag is not supported for these browsers, see https://kangax.github.io/compat-table/es6/#test-RegExp_y_and_u_flags.

Therefore I suggest removing this flag for the best compatibility.

![image](https://user-images.githubusercontent.com/40304728/76744204-2900b180-6774-11ea-8e07-d28d5cb249f0.png)

**Comment by jonthornton** [comment]
Thanks for the heads up!
