### ISSUE TITLE
useSelect not taking value from database (was previously)

### ISSUE THREAD

**Issue by MichaelEC** [jonthornton/jquery-timepicker#711]
Not sure what's happening here!

I choose the useSelect option to make the input field act like a dropdown and I'm struggling to get the database value into the select box.

HTML:

```
      echo "<td><center style='border-bottom: 1px solid; border-color: $color_5;'><input style='text-align:center;' type='text' class='some-time-inputs' value='$lstr_sd_start' name='start_status'></td>";
      echo "<td><center style='border-bottom: 1px solid; border-color: $color_6;'><input style='text-align:center;' type='text' class='some-time-inputs' value='$lstr_sd_end' name='end_status'></td>";>

```
JS:

```
$('.some-time-inputs').timepicker(   { 'timeFormat': 'H:i',
    'listWidth' : 1,
     'useSelect' : true,
    'step' : 5} );
```

The value is getting saved when I choose it in the dropdown list as I can see it on the inspect.

https://gyazo.com/06e3b53b447c68473461812a189a6950

https://gyazo.com/a5844a60089b50739958348fce32d426

**Comment by jonthornton** [comment]
Try it again with the new version 1.13.4. There was a bug in 1.13.3 that might cause this.

**Comment by MichaelEC** [comment]
Hey Jon,

That's great - all working now! Thanks a lot for the heads up!
