### ISSUE TITLE
Latest version does not autocomplete manual data

### ISSUE THREAD

**Issue by prairieit** [jonthornton/jquery-timepicker#712]
Previous versions would autocomplete/auto format the input field when manually typing data.
Previously, typing 443 in the timepicker would default to 4:43 AM as demonstrated with the basic example on the demo page running v1.11.15

Latest version (v1.13.3) this does not work at all

**Comment by matevzperko** [comment]
In version 1.13.3 there is an error in regular expression in function _time2int in line 1248.
Double backslash in "\\W" must be replaced with single one "\W" in both occurrences.
