### ISSUE TITLE
How to dynamically set duration start time?

### ISSUE THREAD

**Issue by realuser** [jonthornton/jquery-timepicker#714]
I have two inputs a start and stop time.  I want to show a duration on the stop time input which uses the start time as the basis.

Here's what I'm trying:
```
<input id="startTime" type="text" />
<input id="endTime" type="text" />

$(document).ready(function () {

  $('#startTime').timepicker({ 
           scrollDefault: '7pm',
           timeFormat: 'g:ia'
   });
    
  $('#endTime').timepicker({ 
        //durationTime: $('#startTime').val(),
        durationTime: '12am',
        scrollDefault: '8pm',
        showDuration: true,
        timeFormat: 'g:ia'
  });
  
  $('#startTime').change(function () {
  	$('#endTime').timepicker('option', 'durationTime', $('#startTime').val());
  });

 });
```

When I do this no duration is shown.  If I don't try to dynamically set the durationTime then a duration is shown. 

https://jsfiddle.net/5m6pra0q/4/

How do I do this?

**Comment by jonthornton** [comment]
Your code is fine; this was broken by the bug mentioned in #712.

You can simplify a bit and pass a dynamic value in config by using a function, like this:
```
  $('#endTime').timepicker({ 
        durationTime: function() { return $('#startTime').val() },
        scrollDefault: '8pm',
        showDuration: true,
        timeFormat: 'g:ia'
  });
```

You won't need the `change` handler to update `durationTime` in this case.
