### ISSUE TITLE
Max time is not working correctly

### ISSUE THREAD

**Issue by geekdevs** [jonthornton/jquery-timepicker#716]
I have this setup:

```
{
  timeFormat: 'H:i',
  interval: 15,
  minTime: '7:45',
  maxTime: '14:30',
}
```

But I only see time range 7:45 -> 14:15 (14:30 option is lost).
It shows fine if I e.g. set `minTime: '7:30'` or `maxTime: '14:45'`

**Comment by jonthornton** [comment]
Try changing `interval` to `step`.

```
{
  timeFormat: 'H:i',
  step: 15,
  minTime: '7:45',
  maxTime: '14:30',
}
```

**Comment by geekdevs** [comment]
That worked - my mistake, thank you.
