### ISSUE TITLE
Error: Can't resolve 'timepicker/jquery.timepicker.css'

### ISSUE THREAD

**Issue by mas-iota** [jonthornton/jquery-timepicker#719]
This is happening after re-installing node_modules.
The version specified in package.json is: **^1.11.12**

And this is how we import:
```
import 'timepicker';
import 'timepicker/jquery.timepicker.css';
```

Now omitting the caret^ from the version will force install 1.11.12 and solves the problem.
Isn't the newly installed version should be backward compatible with 1.11.12?

**Comment by devagrawal09** [comment]
Looks like its not. You have to import from `/dist` to import the built files.

**Comment by jonthornton** [comment]
That's correct, @mas-iota you'll need to update the import statement to `import 'timepicker/dist/jquery.timepicker.css';`. Apologies for this breaking change! The source code structure changed a lot recently, but the plugin API should be unchanged aside from import structure.

**Comment by jonthornton** [comment]
After sleeping on it I realized this could be fixed by changing where the build output goes, which should preserve backwards compatibility.
