### ISSUE TITLE
Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by harryy2510** [jonthornton/jquery-timepicker#721]
Hi,
This error occurred after upgrading to latest version. 

![image](https://user-images.githubusercontent.com/7416971/81380306-4b85ca00-9128-11ea-86ab-2b34efb045ab.png)

When I checked for the source of error, found this
![image](https://user-images.githubusercontent.com/7416971/81380367-6b1cf280-9128-11ea-9d8f-372f7012fae6.png)

`if (settings.disableTimeRanges.length > 0) {`

I think before checking the length should we check if disabledTimes is even defined? I was passing props from parent and it passed undefined to the timepicker

**Comment by jonthornton** [comment]
Hi @harryy2510, can you explain how to reproduce this error? `disableTimeRanges` is supposed to default to an empty array when not set.

**Comment by jonthornton** [comment]
Closed by https://github.com/jonthornton/jquery-timepicker/commit/f78442fa66d45b6c1b344144743d60dcae0c4753. Thanks for reporting this!
