### ISSUE TITLE
jquery.timepicker.min.css no longer in package root

### ISSUE THREAD

**Issue by matteralus** [jonthornton/jquery-timepicker#723]
Got dropped somewhere after 1.13.4

**Comment by jonthornton** [comment]
Thanks for the heads up. Great username 🤘

**Comment by matteralus** [comment]
Haha, no problem man 👍

**Comment by aphix** [comment]
FYI, @jonthornton I just hit this today: I believe you forgot you add the jquery.timepicker.min.css file to the "files" array in the package.json here: https://github.com/jonthornton/jquery-timepicker/commit/2d497cbb61071f4edd5409f9d3dbe67a9d5f7219#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32-R36

Cheers, & thanks for your time on the project.

**Comment by jonthornton** [comment]
Thanks @aphix !
