### ISSUE TITLE
When entering 00:00, the timepicker resolves to the first 12:00 (AM or PM)

### ISSUE THREAD

**Issue by tsorber** [jonthornton/jquery-timepicker#725]
I have a timepicker that is displaying times from 1:00 AM - 12:00 AM (24 hours, by 1 hour increments).  
The issue is when 00:00 is entered into the second timepicker, it resolves to 12:00 PM, rather than AM.  It seems like when 00:00 is entered, it resolves to the nearest 12:00 (AM or PM) value.

**Comment by jonthornton** [comment]
Can you share a working example of the problem? I'm having trouble reproducing it.

**Comment by tsorber** [comment]
I have a decent example created in jfiddle.  Let me know if you can reach it.
http://jsfiddle.net/tsorber/3h5b7v04/11/

Initially, there is not a duration on the end-time dropdown.  This allows 12:00 to resolve to 12:00PM and 00:00 to resolve to 12:00AM.  
To replicate the issue, select a time from the end-time dropdown (i.e. 1:00AM).  This will create a duration text within the dropdown by adding the showDuration, durationTime, and minTime properties.  Now when you attempt 12:00 and 00:00, both will resolve to 12:00PM.

**Comment by jonthornton** [comment]
Thanks, that made it easy to see what was going on. Version 1.13.14 should fix the problem.
