### ISSUE TITLE
$('#spanExample').val() does not work

### ISSUE THREAD

**Issue by Silex** [jonthornton/jquery-timepicker#727]
Hello,

We cannot retrieve the value of non-input elements.

On https://www.jonthornton.com/jquery-timepicker/, the only way I found out that works is `$('#spanExample').data('uiTimepickerValue')`.

**Comment by markvantilburg** [comment]
What does this return?
$('#spanExample').html()

**Comment by Silex** [comment]
It returns `""`.

You can try it yourself at https://www.jonthornton.com/jquery-timepicker/ scroll to "Non-input Example" pick a time then fire up the dev console and test `$('#spanExample').html()` or `$('#spanExample').val()` and see they don't work while `$('#spanExample').data('uiTimepickerValue')` does.

**Comment by markvantilburg** [comment]
The time picker does not put any time into the 'red-square'. Is it supposed to hide the selected time from the end user?

**Comment by Silex** [comment]
I think so?

**Comment by jonthornton** [comment]
The documentation for this feature isn't great, sorry for the confusion.

If you attach timepicker to a non-input element, `$.val()` isn't going to work. The most reliable way to get the time value in that situation will be timpicker's `getTime` or `getSecondsFromMidnight` methods.

**Comment by Silex** [comment]
Thanks :+1:
