### ISSUE TITLE
Incompatible with IE11 using jQuery 3.5.1

### ISSUE THREAD

**Issue by RhesusRheen** [jonthornton/jquery-timepicker#739]
The current version does not work on IE11 when using jQuery 3.5.1, it throws errors due to the use of the following:

- new Event()
- Number.isNaN()
- Number.parseInt()

I would recommend dropping the Number prefixes and using CustomEvent() with a polyfill for IE11 (https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)

**Comment by jonthornton** [comment]
Thanks for raising this! Could you verify the fix in this PR? https://github.com/jonthornton/jquery-timepicker/pull/741 I'm working with a Mac and don't have an IE VM handy.

**Comment by jonthornton** [comment]
Closing this since Microsoft announced end of support dates for IE11 https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-support-end-dates
