### ISSUE TITLE
Accepts Improper text

### ISSUE THREAD

**Issue by huzaifa-khambaty** [jonthornton/jquery-timepicker#740]
When typing 12:00 it converts 12:00am this is fine.
but when i type 12:0 it do not converts. Plugin also accept other characters like abcd

**Comment by lexasorokin** [comment]
+1

**Comment by jonthornton** [comment]
Thanks for raising this! Converting `12:0` has been fixed.

Accepting other invalid input is by design. Your app can use timepicker's `timeFormatError` event to detect and handle invalid input.
