### ISSUE TITLE
Issues if 00:00 or 12:00 AM

### ISSUE THREAD

**Issue by 123445666** [jonthornton/jquery-timepicker#742]
When input 00:00 or 12:00 AM. It's changing value to 0

**Comment by 123445666** [comment]
the issue of the version 1.13.15.

**Comment by jonthornton** [comment]
This should be fixed in 1.13.16

**Comment by bulauza** [comment]
I use ver1.13.16，but I seem to be experiencing the same problem.

**Comment by jonthornton** [comment]
@bulauza I'm unable to reproduce the error myself. Can you post a jsfiddle and instructions that demonstrate the error?

**Comment by bulauza** [comment]
@jonthornton 
When select 00:00, this issue will happen.
jsfiddle is [here](https://jsfiddle.net/yxg270ma/).

**Comment by jonthornton** [comment]
@bulauza thank you! Try https://github.com/jonthornton/jquery-timepicker/releases/tag/1.13.17

**Comment by bulauza** [comment]
@jonthornton LGTM. Thank you!
