### ISSUE TITLE
Change event not firing using event delegation

### ISSUE THREAD

**Issue by jmross** [jonthornton/jquery-timepicker#745]
After upgrading to version 1.13.16 from 1.13.14, events aren't firing when using event delegation when I change the time.

Here's an example:

http://jsfiddle.net/56npLyth/

The event fires when changing the second input which isn't a timepicker.

Using 1.13.14, 'test' is outputted to the console when selecting a time in the timepicker.

I've tried other events like 'selectTime' and 'changeTime' as well but they don't seem to be firing either.

It seems to fire if I type in the input. Using the timepicker dropdown doesn't fire the event though.

Thanks

**Comment by jonthornton** [comment]
@jmross thank you for reporting this! It seems I made an incorrect assumption about the `CustomEvent` API. Should be fixed in the latest release.
