### ISSUE TITLE
hrs only 

### ISSUE THREAD

**Issue by papyr** [jonthornton/jquery-timepicker#748]
Hello, this is really nice 👍 I am trying to replace text fields with your timepicker, becuase user may accidentally enter commas, etc.

It would be great to have your timepicker for hors only, like screenshot

 I have a timesheet, with many rows / cells in a week, how do I allow hrs only (someone may pick 4 hrs of work) on the time sheet
![image](https://user-images.githubusercontent.com/12733414/110715584-8686dd00-81d3-11eb-8b05-0223b547ec7b.png)

I also want to get the hrs entered and make sure it does not exceed 24 hrs in day.

**Comment by jonthornton** [comment]
`$('#someInput').timepicker({step: 60})` would limit the options to only hours
