### ISSUE TITLE
Array returns 'Today' String in date picker

### ISSUE THREAD

**Issue by ELkoos** [jonthornton/jquery-timepicker#751]
Hello. I recently installed Food Online Premium (Woocommerce plugin) which uses Your timepicker to display delivery time/date. Problem is, I can't get any response from that plugins dev team regarding that when I have set it to display clients choice on delivery date, it generates array with string instead of date. Since I am not to savvy with debugging whole code myself, I thought I ask here: timepicker generates correct array, but instead of giving back all info in my chosen date format, current day is just pronounced 'Today', which then causes problems with orders for obvious reasons (it stays 'Today' in order details, because Food Online devs are too lazy to fix this). Is there any info anyone can provide me/poke me to right direction?

**Comment by jonthornton** [comment]
I'm sorry, I'm not familiar with that plugin.
