### ISSUE TITLE
Time Picker with Duration shows horizontal scroll bar when using step:15

### ISSUE THREAD

**Issue by mdolnik-eelzee** [jonthornton/jquery-timepicker#767]
When using the same code as the demo for [Datepair Plugin Example](https://www.jonthornton.com/jquery-timepicker) with the only difference being that the `step` value is set to 15 then the width of the dropdown is too narrow for the duration text causing a horizonal scrollbar to appear.

![2021-09-21_11h44_26](https://user-images.githubusercontent.com/20405268/134253437-3077e811-bde1-42c6-8ec2-e75747ce0df1.png)

In the CSS code there seems to be provisions for step 30 and step 60, but not 15 or any other values.

https://github.com/jonthornton/jquery-timepicker/blob/24d8ea33b41aee3baf9d0562c43ed4f392202c05/jquery.timepicker.css#L15-L22

Rather than having `.ui-timepicker-wrapper.ui-timepicker-with-duration` set to `width: 13em;` is it possible to set it to `width: auto`? This resolves the issue for me.

![2021-09-21_11h46_39](https://user-images.githubusercontent.com/20405268/134253578-39390e54-f7ad-4034-8e9b-d555eb680e25.png)

Also: The above solution works on Chrome, on Firefox I also need to add:
```
.ui-timepicker-wrapper .ui-timepicker-list li {
    padding-right: 2rem;
}
```

**Comment by jonthornton** [comment]
Thank you for the comprehensive bug report! This fix will go out with the next release.
