### ISSUE TITLE
characters not escape between time

### ISSUE THREAD

**Issue by RoomLea** [jonthornton/jquery-timepicker#774]
characters are not escape between time. when adding raw text. it is not removing(escaping)
eg: 10:30 AM 
after adding characters: 1aaaa0:3aaaaa0 AM . characters are not escaping. can you please help?

**Comment by jonthornton** [comment]
Timepicker doesn't remove invalid input characters itself, though it'll tell you they're there with a `timeFormatError` event. You'll need to find another solution to remove the invalid characters.
