### ISSUE TITLE
JQuery 

### ISSUE THREAD

**Issue by WeslleyDeSouza** [jonthornton/jquery-timepicker#779]
Really nice timepicker!! 
Are you planing to remove JQuery?

**Comment by jonthornton** [comment]
If I ever get the time to rewrite this component, yeah, v2 would not have a dependency on jquery. For now though I only have enough time to make bug fixes and small improvements to support people using the jquery version.

**Comment by PRO-BROS** [comment]
Superb! You can learn [coding by clicking here](https://prhocoding.com/).
