### ISSUE TITLE
Set defaultTime as selected or Input Value

### ISSUE THREAD

**Issue by oudin** [jonthornton/jquery-timepicker#784]
Hi 

I would like to set a 'defaultTime' as selected or as the input value. For example, I would like to make 10:00 Am the default or selected time and the user can then choose to select another time if they wish.

You can see an example of this in the following plugin [https://timepicker.co/](https://timepicker.co/)

Your plugin already has most of the about plugin features but is it possible to set a defaultTime?

**Comment by jonthornton** [comment]
This plugin doesn't have that functionality, but it would be compatible with your own code setting the default time.
