### ISSUE TITLE
setTime allows time from disabledTimeRanges

### ISSUE THREAD

**Issue by salesigniter** [jonthornton/jquery-timepicker#785]
It seems that setTime allows setting a time that is disabled by disabledTimeRanges shouldn't it not allow this? 

Any suggestions on how to implement a fix for this if this is intended, like a function that checks if the time is disabled and doesn't allow selecting it? 

I have code like:

```
// Correctly disables 1pm to 4:30pm
this.timepickerto.timepicker('option','disableTimeRanges',[['1:00pm','5:00pm]]);

// ToDate time is 1pm, it allows selecting this disabled time
this.timepickerto.timepicker('setTime', ToDate)
```

**Comment by jonthornton** [comment]
Thanks for the heads up! This is unintended- it should dispatch a timeRangeError event. It'll be fixed in the next release.
