### ISSUE TITLE
Second is always 00

### ISSUE THREAD

**Issue by dev-santosh** [jonthornton/jquery-timepicker#786]
When the time format is h:m:s A,
Second, is always 00 in the selection dropdown.
Any particular condition which is missing.
$('#ELE').timepicker({
                timeFormat: 'h:i:s A',
                step: 15
            });

**Comment by jonthornton** [comment]
Due to some poor implementation decisions made a while ago (by me 😄), jquery-timepicker manages internal state in minute resolution. It literally can't understand seconds. I hope to eventually remedy this in a rewrite one day, but it won't be a quick fix.
