### ISSUE TITLE
localization issue with pm formats ending in "a" or "p"

### ISSUE THREAD

**Issue by warrenspence** [jonthornton/jquery-timepicker#787]
### Problem
If you provide a `lang` configuration that has `pm` format ending in `p` then all PM values you select from the dropdown get treated as AM values.

### Sequence of events
- Configure the timepicker with a `lang`  setting that has `pm: "pop."` and `PM: "pop."`
- Select the option `9:00 pop.` from the dropdown
- The `time2int` function will execute with a `timeString` value of `9:00 pop.`
- Line 432 changes `timeString` to `9:00pop`
- Line 434 detects that the string finishes with a `p` so it adds `m` to the `timeString`, its value is now `9:00popm`
- Line 445 parses the `timeString` and determines the `ampm` string is `popm`
- Line 471 checks the value of `ampm` against the configured `lang.pm` setting of `pop.` and decides that it is not PM, so its AM

### Suggested fix
The code on line 434 should only be executed if you are using english style AM/PM values:
```
// if the current language is am/pm, and if the last character is an "a" or "p", add the "m"
if ((this.settings.lang.am === "am") && (timeString.slice(-1) == "a" || timeString.slice(-1) == "p")) {
  timeString += "m";
}
```

**Comment by jonthornton** [comment]
Wow, this is really awesome debugging- thank you! The fix you suggested will be included in the next release.
