### ISSUE TITLE
noneOption with custom value no longer works as of version 1.13.19

### ISSUE THREAD

**Issue by bkosborne** [jonthornton/jquery-timepicker#788]
I upgraded from 1.13.18 to 1.13.19 and `noneOption` stopped working as expected. In the README, this option is described like this:

> Adds one or more custom options to the top of the dropdown. Can accept several different value types:
Boolean (true): Adds a "None" option that results in an empty input value
String: Adds an option with a custom label that results in an empty input value
Object: Similar to string, but allows customizing the element's class name and the resulting input value. Can contain label, value, and className properties. value must be a string type.
Array: An array of strings or objects to add multiple non-time options
default: false

With the following settings, the select option value that's generated is identical to the label, and it ignores the custom value I set:

```
$(function(){
   $('#example').timepicker({
     'timeFormat': 'h:i A',
     'step': '15',
     'useSelect': true,
     'scrollDefault': '09:00',
     'noneOption': {
       'value': 'some_value',
       'label': 'Select time'
     }
   }); 
});
```

This produces output like this:

```
<select class="ui-timepicker-select">
<option value="Select time">Select time</option>
<option value="12:00 AM">12:00 AM</option>
<option value="12:15 AM">12:15 AM</option>
...
</select>
```

When it should be like this:

```
<select class="ui-timepicker-select">
<option value="some_value">Select time</option>
<option value="12:00 AM">12:00 AM</option>
<option value="12:15 AM">12:15 AM</option>
...
</select>
```

Here's a JS Fiddle that loads version 1.13.19 that demonstrates the issue: http://jsfiddle.net/e2bhpyma/
Here's a JS Fiddle that loads version 1.13.18 where it works as expected: https://jsfiddle.net/ze5jvkgf/

**Comment by jonthornton** [comment]
Thank you for the easy-to-follow bug report! This will be fixed in an upcoming release.

**Comment by bkosborne** [comment]
Can this please be ropened @jonthornton ? I just tested this with 14.1.0 and it's still not working.

Here's the JS fiddle demonstrating the problem: https://jsfiddle.net/yqghtj54/

**Comment by bkosborne** [comment]
@gicalle oops, sorry about that. Updated my comment with the correct link, which shows it is actually working, so now I'm not sure what I had wrong. But you can see it does have an unrelated problem, which is that the drop-down options list values start off in the correct format, but then change to showing number of seconds.
