### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by sdw** [jonthornton/jquery-timepicker#83]
I'm having problem with timezones in the date picker...

My browser is in GMT +1.

When I select a time from the drop down, the time is put into the input box.

When I click away, the time is updated - to 1 hour ahead of the selected time.

**Comment by fluxsaas** [comment]
did you guys happend to solve this problem? i have the same/similar problem:

in timzeone london: (GMT+0800) it works fine.

![screenshot 2016-03-15 19 25 33](https://cloud.githubusercontent.com/assets/13223/13776190/efbf9a0a-eafc-11e5-93c8-468b2227f7d8.png)


in timzeone sydney/australia: (GMT+1100 (AEDT)) it does not work:

![screenshot 2016-03-15 22 13 20](https://cloud.githubusercontent.com/assets/13223/13775922/60bee69a-eafb-11e5-9169-0f4de29621bf.png)

it seems it does not work if the timezone diff is greater then GMT+1000

in timezone broken hill/Australia: (GMT+1030 (ACDT))

![screenshot 2016-03-15 21 53 12](https://cloud.githubusercontent.com/assets/13223/13776137/964723f8-eafc-11e5-985f-5d1d1c8d2b5b.png)

**Comment by fluxsaas** [comment]
it seems that: 

    _int2time

has a problem, given time string: 14:00, and timezone GMT+1100 (AEDT)

````
var _baseDate = new Date(1970, 0, 1, 0, 0, 0);
var seconds = 14*60*60;
var time = new Date(_baseDate.valueOf() + (seconds*1000));
````

gives you the time:

`````
Thu Jan 01 1970 13:00:00 GMT+1000 (AEST)
````

it seems, everything later than 10:00 results in a problem:

````
var _baseDate = new Date(1970, 0, 1, 0, 0, 0);
a = new Date(_baseDate.valueOf())
a.setSeconds(10*60*60)

=> Thu Jan 01 1970 10:00:00 GMT+1100 (AEDT)
````

later than 10:00

````
var _baseDate = new Date(1970, 0, 1, 0, 0, 0);
a = new Date(_baseDate.valueOf())
a.setSeconds(11*60*60)

=> Thu Jan 01 1970 11:00:00 GMT+1000 (AEST)
````

**Comment by fluxsaas** [comment]
the solution i have is following:

`````javascript
    function _int2time(seconds, settings)
    {
        if (seconds === null) {
            return null;
        }

        // calculate seconds, minutes, hours
        var duration = seconds*1000
        var milliseconds = parseInt((duration%1000)/100)
            , seconds = parseInt((duration/1000)%60)
            , minutes = parseInt((duration/(1000*60))%60)
            , hours = parseInt((duration/(1000*60*60))%24);

        hours = (hours < 10) ? "0" + hours : hours;
        minutes = (minutes < 10) ? "0" + minutes : minutes;
        seconds = (seconds < 10) ? "0" + seconds : seconds;

        // set date object
        var time = new Date(1970, 0, 1, hours, minutes, seconds, 0);
`````

**Comment by fluxsaas** [comment]
i have opend a proper issue #494 with a summery.
